var searchData=
[
  ['parallel',['Parallel',['../class_system_1_1_threading_1_1_tasks_1_1_parallel.html',1,'System::Threading::Tasks']]],
  ['parallelenumerable',['ParallelEnumerable',['../class_system_1_1_linq_1_1_parallel_enumerable.html',1,'System::Linq']]],
  ['parallelloopresult',['ParallelLoopResult',['../struct_system_1_1_threading_1_1_tasks_1_1_parallel_loop_result.html',1,'System::Threading::Tasks']]],
  ['parallelloopstate',['ParallelLoopState',['../class_system_1_1_threading_1_1_tasks_1_1_parallel_loop_state.html',1,'System::Threading::Tasks']]],
  ['paralleloptions',['ParallelOptions',['../class_system_1_1_threading_1_1_tasks_1_1_parallel_options.html',1,'System::Threading::Tasks']]],
  ['parallelquery',['ParallelQuery',['../class_system_1_1_linq_1_1_parallel_query.html',1,'System.Linq.ParallelQuery'],['../class_system_1_1_linq_1_1_parallel_query.html',1,'System.Linq.ParallelQuery&lt; TSource &gt;']]],
  ['parallelquery_3c_20int_20_3e',['ParallelQuery&lt; int &gt;',['../class_system_1_1_linq_1_1_parallel_query.html',1,'System::Linq']]],
  ['parallelquery_3c_20object_20_3e',['ParallelQuery&lt; object &gt;',['../class_system_1_1_linq_1_1_parallel_query.html',1,'System::Linq']]],
  ['parallelquery_3c_20t_20_3e',['ParallelQuery&lt; T &gt;',['../class_system_1_1_linq_1_1_parallel_query.html',1,'System::Linq']]],
  ['parallelquery_3c_20toutput_20_3e',['ParallelQuery&lt; TOutput &gt;',['../class_system_1_1_linq_1_1_parallel_query.html',1,'System::Linq']]],
  ['parallelquery_3c_20tresult_20_3e',['ParallelQuery&lt; TResult &gt;',['../class_system_1_1_linq_1_1_parallel_query.html',1,'System::Linq']]],
  ['parallelquery_3c_20tsource_20_3e',['ParallelQuery&lt; TSource &gt;',['../class_system_1_1_linq_1_1_parallel_query.html',1,'System::Linq']]],
  ['paramarrayattribute',['ParamArrayAttribute',['../class_system_1_1_param_array_attribute.html',1,'System']]],
  ['paramdesc',['PARAMDESC',['../struct_system_1_1_runtime_1_1_interop_services_1_1_p_a_r_a_m_d_e_s_c.html',1,'System.Runtime.InteropServices.PARAMDESC'],['../struct_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_p_a_r_a_m_d_e_s_c.html',1,'System.Runtime.InteropServices.ComTypes.PARAMDESC']]],
  ['parameterbuilder',['ParameterBuilder',['../class_system_1_1_reflection_1_1_emit_1_1_parameter_builder.html',1,'System::Reflection::Emit']]],
  ['parameterexpression',['ParameterExpression',['../class_system_1_1_linq_1_1_expressions_1_1_parameter_expression.html',1,'System::Linq::Expressions']]],
  ['parameterinfo',['ParameterInfo',['../class_system_1_1_reflection_1_1_parameter_info.html',1,'System::Reflection']]],
  ['parametermodifier',['ParameterModifier',['../struct_system_1_1_reflection_1_1_parameter_modifier.html',1,'System::Reflection']]],
  ['parametertoken',['ParameterToken',['../struct_system_1_1_reflection_1_1_emit_1_1_parameter_token.html',1,'System::Reflection::Emit']]],
  ['parenthesizepropertynameattribute',['ParenthesizePropertyNameAttribute',['../class_system_1_1_component_model_1_1_parenthesize_property_name_attribute.html',1,'System::ComponentModel']]],
  ['partitioner',['Partitioner',['../class_system_1_1_collections_1_1_concurrent_1_1_partitioner.html',1,'System::Collections::Concurrent']]],
  ['partitioner_3c_20telement_20_3e',['Partitioner&lt; TElement &gt;',['../class_system_1_1_collections_1_1_concurrent_1_1_partitioner.html',1,'System::Collections::Concurrent']]],
  ['passwordderivebytes',['PasswordDeriveBytes',['../class_system_1_1_security_1_1_cryptography_1_1_password_derive_bytes.html',1,'System::Security::Cryptography']]],
  ['passwordpropertytextattribute',['PasswordPropertyTextAttribute',['../class_system_1_1_component_model_1_1_password_property_text_attribute.html',1,'System::ComponentModel']]],
  ['path',['Path',['../class_system_1_1_i_o_1_1_path.html',1,'System::IO']]],
  ['pathtoolongexception',['PathTooLongException',['../class_system_1_1_i_o_1_1_path_too_long_exception.html',1,'System::IO']]],
  ['performancecounter',['PerformanceCounter',['../class_system_1_1_diagnostics_1_1_performance_counter.html',1,'System::Diagnostics']]],
  ['performancecountercategory',['PerformanceCounterCategory',['../class_system_1_1_diagnostics_1_1_performance_counter_category.html',1,'System::Diagnostics']]],
  ['performancecountermanager',['PerformanceCounterManager',['../class_system_1_1_diagnostics_1_1_performance_counter_manager.html',1,'System::Diagnostics']]],
  ['performancecounterpermission',['PerformanceCounterPermission',['../class_system_1_1_diagnostics_1_1_performance_counter_permission.html',1,'System::Diagnostics']]],
  ['performancecounterpermissionattribute',['PerformanceCounterPermissionAttribute',['../class_system_1_1_diagnostics_1_1_performance_counter_permission_attribute.html',1,'System::Diagnostics']]],
  ['performancecounterpermissionentry',['PerformanceCounterPermissionEntry',['../class_system_1_1_diagnostics_1_1_performance_counter_permission_entry.html',1,'System::Diagnostics']]],
  ['performancecounterpermissionentrycollection',['PerformanceCounterPermissionEntryCollection',['../class_system_1_1_diagnostics_1_1_performance_counter_permission_entry_collection.html',1,'System::Diagnostics']]],
  ['performancecounterselement',['PerformanceCountersElement',['../class_system_1_1_net_1_1_configuration_1_1_performance_counters_element.html',1,'System::Net::Configuration']]],
  ['permissionrequestevidence',['PermissionRequestEvidence',['../class_system_1_1_security_1_1_policy_1_1_permission_request_evidence.html',1,'System::Security::Policy']]],
  ['permissionset',['PermissionSet',['../class_system_1_1_security_1_1_permission_set.html',1,'System::Security']]],
  ['permissionsetattribute',['PermissionSetAttribute',['../class_system_1_1_security_1_1_permissions_1_1_permission_set_attribute.html',1,'System::Security::Permissions']]],
  ['persiancalendar',['PersianCalendar',['../class_system_1_1_globalization_1_1_persian_calendar.html',1,'System::Globalization']]],
  ['physicaladdress',['PhysicalAddress',['../class_system_1_1_net_1_1_network_information_1_1_physical_address.html',1,'System::Net::NetworkInformation']]],
  ['ping',['Ping',['../class_system_1_1_net_1_1_network_information_1_1_ping.html',1,'System::Net::NetworkInformation']]],
  ['pingcompletedeventargs',['PingCompletedEventArgs',['../class_system_1_1_net_1_1_network_information_1_1_ping_completed_event_args.html',1,'System::Net::NetworkInformation']]],
  ['pingexception',['PingException',['../class_system_1_1_net_1_1_network_information_1_1_ping_exception.html',1,'System::Net::NetworkInformation']]],
  ['pingoptions',['PingOptions',['../class_system_1_1_net_1_1_network_information_1_1_ping_options.html',1,'System::Net::NetworkInformation']]],
  ['pingreply',['PingReply',['../class_system_1_1_net_1_1_network_information_1_1_ping_reply.html',1,'System::Net::NetworkInformation']]],
  ['pipeaccessrule',['PipeAccessRule',['../class_system_1_1_i_o_1_1_pipes_1_1_pipe_access_rule.html',1,'System::IO::Pipes']]],
  ['pipeauditrule',['PipeAuditRule',['../class_system_1_1_i_o_1_1_pipes_1_1_pipe_audit_rule.html',1,'System::IO::Pipes']]],
  ['pipesecurity',['PipeSecurity',['../class_system_1_1_i_o_1_1_pipes_1_1_pipe_security.html',1,'System::IO::Pipes']]],
  ['pipestream',['PipeStream',['../class_system_1_1_i_o_1_1_pipes_1_1_pipe_stream.html',1,'System::IO::Pipes']]],
  ['pkcs1maskgenerationmethod',['PKCS1MaskGenerationMethod',['../class_system_1_1_security_1_1_cryptography_1_1_p_k_c_s1_mask_generation_method.html',1,'System::Security::Cryptography']]],
  ['platformnotsupportedexception',['PlatformNotSupportedException',['../class_system_1_1_platform_not_supported_exception.html',1,'System']]],
  ['pointer',['Pointer',['../class_system_1_1_reflection_1_1_pointer.html',1,'System::Reflection']]],
  ['policyexception',['PolicyException',['../class_system_1_1_security_1_1_policy_1_1_policy_exception.html',1,'System::Security::Policy']]],
  ['policylevel',['PolicyLevel',['../class_system_1_1_security_1_1_policy_1_1_policy_level.html',1,'System::Security::Policy']]],
  ['policystatement',['PolicyStatement',['../class_system_1_1_security_1_1_policy_1_1_policy_statement.html',1,'System::Security::Policy']]],
  ['preallocatedoverlapped',['PreAllocatedOverlapped',['../class_system_1_1_threading_1_1_pre_allocated_overlapped.html',1,'System::Threading']]],
  ['prepreparemethodattribute',['PrePrepareMethodAttribute',['../class_system_1_1_runtime_1_1_constrained_execution_1_1_pre_prepare_method_attribute.html',1,'System::Runtime::ConstrainedExecution']]],
  ['preservesigattribute',['PreserveSigAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_preserve_sig_attribute.html',1,'System::Runtime::InteropServices']]],
  ['primaryinteropassemblyattribute',['PrimaryInteropAssemblyAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_primary_interop_assembly_attribute.html',1,'System::Runtime::InteropServices']]],
  ['principalpermission',['PrincipalPermission',['../class_system_1_1_security_1_1_permissions_1_1_principal_permission.html',1,'System::Security::Permissions']]],
  ['principalpermissionattribute',['PrincipalPermissionAttribute',['../class_system_1_1_security_1_1_permissions_1_1_principal_permission_attribute.html',1,'System::Security::Permissions']]],
  ['privilegenotheldexception',['PrivilegeNotHeldException',['../class_system_1_1_security_1_1_access_control_1_1_privilege_not_held_exception.html',1,'System::Security::AccessControl']]],
  ['process',['Process',['../class_system_1_1_diagnostics_1_1_process.html',1,'System::Diagnostics']]],
  ['processmodule',['ProcessModule',['../class_system_1_1_diagnostics_1_1_process_module.html',1,'System::Diagnostics']]],
  ['processmodulecollection',['ProcessModuleCollection',['../class_system_1_1_diagnostics_1_1_process_module_collection.html',1,'System::Diagnostics']]],
  ['processstartinfo',['ProcessStartInfo',['../class_system_1_1_diagnostics_1_1_process_start_info.html',1,'System::Diagnostics']]],
  ['processthread',['ProcessThread',['../class_system_1_1_diagnostics_1_1_process_thread.html',1,'System::Diagnostics']]],
  ['processthreadcollection',['ProcessThreadCollection',['../class_system_1_1_diagnostics_1_1_process_thread_collection.html',1,'System::Diagnostics']]],
  ['profileoptimization',['ProfileOptimization',['../class_system_1_1_runtime_1_1_profile_optimization.html',1,'System::Runtime']]],
  ['progidattribute',['ProgIdAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_prog_id_attribute.html',1,'System::Runtime::InteropServices']]],
  ['progress',['Progress',['../class_system_1_1_progress.html',1,'System']]],
  ['progresschangedeventargs',['ProgressChangedEventArgs',['../class_system_1_1_component_model_1_1_progress_changed_event_args.html',1,'System::ComponentModel']]],
  ['propertybuilder',['PropertyBuilder',['../class_system_1_1_reflection_1_1_emit_1_1_property_builder.html',1,'System::Reflection::Emit']]],
  ['propertychangedeventargs',['PropertyChangedEventArgs',['../class_system_1_1_component_model_1_1_property_changed_event_args.html',1,'System::ComponentModel']]],
  ['propertychangingeventargs',['PropertyChangingEventArgs',['../class_system_1_1_component_model_1_1_property_changing_event_args.html',1,'System::ComponentModel']]],
  ['propertydescriptor',['PropertyDescriptor',['../class_system_1_1_component_model_1_1_property_descriptor.html',1,'System::ComponentModel']]],
  ['propertydescriptorcollection',['PropertyDescriptorCollection',['../class_system_1_1_component_model_1_1_property_descriptor_collection.html',1,'System::ComponentModel']]],
  ['propertyinfo',['PropertyInfo',['../class_system_1_1_reflection_1_1_property_info.html',1,'System::Reflection']]],
  ['propertytabattribute',['PropertyTabAttribute',['../class_system_1_1_component_model_1_1_property_tab_attribute.html',1,'System::ComponentModel']]],
  ['propertytoken',['PropertyToken',['../struct_system_1_1_reflection_1_1_emit_1_1_property_token.html',1,'System::Reflection::Emit']]],
  ['protocolviolationexception',['ProtocolViolationException',['../class_system_1_1_net_1_1_protocol_violation_exception.html',1,'System::Net']]],
  ['providepropertyattribute',['ProvidePropertyAttribute',['../class_system_1_1_component_model_1_1_provide_property_attribute.html',1,'System::ComponentModel']]],
  ['providermetadata',['ProviderMetadata',['../class_system_1_1_diagnostics_1_1_eventing_1_1_reader_1_1_provider_metadata.html',1,'System::Diagnostics::Eventing::Reader']]],
  ['proxyattribute',['ProxyAttribute',['../class_system_1_1_runtime_1_1_remoting_1_1_proxies_1_1_proxy_attribute.html',1,'System::Runtime::Remoting::Proxies']]],
  ['proxyelement',['ProxyElement',['../class_system_1_1_net_1_1_configuration_1_1_proxy_element.html',1,'System::Net::Configuration']]],
  ['publickey',['PublicKey',['../class_system_1_1_security_1_1_cryptography_1_1_x509_certificates_1_1_public_key.html',1,'System::Security::Cryptography::X509Certificates']]],
  ['publisher',['Publisher',['../class_system_1_1_security_1_1_policy_1_1_publisher.html',1,'System::Security::Policy']]],
  ['publisheridentitypermission',['PublisherIdentityPermission',['../class_system_1_1_security_1_1_permissions_1_1_publisher_identity_permission.html',1,'System::Security::Permissions']]],
  ['publisheridentitypermissionattribute',['PublisherIdentityPermissionAttribute',['../class_system_1_1_security_1_1_permissions_1_1_publisher_identity_permission_attribute.html',1,'System::Security::Permissions']]],
  ['publishermembershipcondition',['PublisherMembershipCondition',['../class_system_1_1_security_1_1_policy_1_1_publisher_membership_condition.html',1,'System::Security::Policy']]],
  ['pureattribute',['PureAttribute',['../class_system_1_1_diagnostics_1_1_contracts_1_1_pure_attribute.html',1,'System::Diagnostics::Contracts']]]
];
