var searchData=
[
  ['iactivationfactory',['IActivationFactory',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_activation_factory.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['iactivator',['IActivator',['../interface_system_1_1_runtime_1_1_remoting_1_1_activation_1_1_i_activator.html',1,'System::Runtime::Remoting::Activation']]],
  ['iadvisesink',['IAdviseSink',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_advise_sink.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['iappdomainsetup',['IAppDomainSetup',['../interface_system_1_1_i_app_domain_setup.html',1,'System']]],
  ['iapplicationresourcestreamresolver',['IApplicationResourceStreamResolver',['../interface_system_1_1_xml_1_1_i_application_resource_stream_resolver.html',1,'System::Xml']]],
  ['iapplicationsettingsprovider',['IApplicationSettingsProvider',['../interface_system_1_1_configuration_1_1_i_application_settings_provider.html',1,'System::Configuration']]],
  ['iapplicationtrustmanager',['IApplicationTrustManager',['../interface_system_1_1_security_1_1_policy_1_1_i_application_trust_manager.html',1,'System::Security::Policy']]],
  ['iargumentprovider',['IArgumentProvider',['../interface_system_1_1_linq_1_1_expressions_1_1_i_argument_provider.html',1,'System::Linq::Expressions']]],
  ['iasyncresult',['IAsyncResult',['../interface_system_1_1_i_async_result.html',1,'System']]],
  ['iasyncstatemachine',['IAsyncStateMachine',['../interface_system_1_1_runtime_1_1_compiler_services_1_1_i_async_state_machine.html',1,'System::Runtime::CompilerServices']]],
  ['iauthenticationmodule',['IAuthenticationModule',['../interface_system_1_1_net_1_1_i_authentication_module.html',1,'System::Net']]],
  ['ibindctx',['IBindCtx',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_bind_ctx.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['ibindinglist',['IBindingList',['../interface_system_1_1_component_model_1_1_i_binding_list.html',1,'System::ComponentModel']]],
  ['ibindinglistview',['IBindingListView',['../interface_system_1_1_component_model_1_1_i_binding_list_view.html',1,'System::ComponentModel']]],
  ['icanceladdnew',['ICancelAddNew',['../interface_system_1_1_component_model_1_1_i_cancel_add_new.html',1,'System::ComponentModel']]],
  ['icertificatepolicy',['ICertificatePolicy',['../interface_system_1_1_net_1_1_i_certificate_policy.html',1,'System::Net']]],
  ['ichangetracking',['IChangeTracking',['../interface_system_1_1_component_model_1_1_i_change_tracking.html',1,'System::ComponentModel']]],
  ['ichannel',['IChannel',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel.html',1,'System::Runtime::Remoting::Channels']]],
  ['ichanneldatastore',['IChannelDataStore',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_data_store.html',1,'System::Runtime::Remoting::Channels']]],
  ['ichannelinfo',['IChannelInfo',['../interface_system_1_1_runtime_1_1_remoting_1_1_i_channel_info.html',1,'System::Runtime::Remoting']]],
  ['ichannelreceiver',['IChannelReceiver',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_receiver.html',1,'System::Runtime::Remoting::Channels']]],
  ['ichannelreceiverhook',['IChannelReceiverHook',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_receiver_hook.html',1,'System::Runtime::Remoting::Channels']]],
  ['ichannelsender',['IChannelSender',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_sender.html',1,'System::Runtime::Remoting::Channels']]],
  ['ichannelsinkbase',['IChannelSinkBase',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_sink_base.html',1,'System::Runtime::Remoting::Channels']]],
  ['iclientchannelsink',['IClientChannelSink',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_channel_sink.html',1,'System::Runtime::Remoting::Channels']]],
  ['iclientchannelsinkprovider',['IClientChannelSinkProvider',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_channel_sink_provider.html',1,'System::Runtime::Remoting::Channels']]],
  ['iclientchannelsinkstack',['IClientChannelSinkStack',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_channel_sink_stack.html',1,'System::Runtime::Remoting::Channels']]],
  ['iclientformattersink',['IClientFormatterSink',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_formatter_sink.html',1,'System::Runtime::Remoting::Channels']]],
  ['iclientformattersinkprovider',['IClientFormatterSinkProvider',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_formatter_sink_provider.html',1,'System::Runtime::Remoting::Channels']]],
  ['iclientresponsechannelsinkstack',['IClientResponseChannelSinkStack',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_response_channel_sink_stack.html',1,'System::Runtime::Remoting::Channels']]],
  ['icloneable',['ICloneable',['../interface_system_1_1_i_cloneable.html',1,'System']]],
  ['icmpv4statistics',['IcmpV4Statistics',['../class_system_1_1_net_1_1_network_information_1_1_icmp_v4_statistics.html',1,'System::Net::NetworkInformation']]],
  ['icmpv6statistics',['IcmpV6Statistics',['../class_system_1_1_net_1_1_network_information_1_1_icmp_v6_statistics.html',1,'System::Net::NetworkInformation']]],
  ['icodecompiler',['ICodeCompiler',['../interface_system_1_1_code_dom_1_1_compiler_1_1_i_code_compiler.html',1,'System::CodeDom::Compiler']]],
  ['icodegenerator',['ICodeGenerator',['../interface_system_1_1_code_dom_1_1_compiler_1_1_i_code_generator.html',1,'System::CodeDom::Compiler']]],
  ['icodeparser',['ICodeParser',['../interface_system_1_1_code_dom_1_1_compiler_1_1_i_code_parser.html',1,'System::CodeDom::Compiler']]],
  ['icollectdata',['ICollectData',['../interface_system_1_1_diagnostics_1_1_i_collect_data.html',1,'System::Diagnostics']]],
  ['icollection',['ICollection',['../interface_system_1_1_collections_1_1_generic_1_1_i_collection.html',1,'System.Collections.Generic.ICollection&lt; T &gt;'],['../interface_system_1_1_collections_1_1_i_collection.html',1,'System.Collections.ICollection']]],
  ['icollection_3c_20expression_20_3e',['ICollection&lt; Expression &gt;',['../interface_system_1_1_collections_1_1_i_collection.html',1,'System::Collections']]],
  ['icollection_3c_20gatewayipaddressinformation_20_3e',['ICollection&lt; GatewayIPAddressInformation &gt;',['../interface_system_1_1_collections_1_1_i_collection.html',1,'System::Collections']]],
  ['icollection_3c_20identityreference_20_3e',['ICollection&lt; IdentityReference &gt;',['../interface_system_1_1_collections_1_1_i_collection.html',1,'System::Collections']]],
  ['icollection_3c_20ipaddress_20_3e',['ICollection&lt; IPAddress &gt;',['../interface_system_1_1_collections_1_1_i_collection.html',1,'System::Collections']]],
  ['icollection_3c_20ipaddressinformation_20_3e',['ICollection&lt; IPAddressInformation &gt;',['../interface_system_1_1_collections_1_1_i_collection.html',1,'System::Collections']]],
  ['icollection_3c_20multicastipaddressinformation_20_3e',['ICollection&lt; MulticastIPAddressInformation &gt;',['../interface_system_1_1_collections_1_1_i_collection.html',1,'System::Collections']]],
  ['icollection_3c_20object_20_3e',['ICollection&lt; object &gt;',['../interface_system_1_1_collections_1_1_i_collection.html',1,'System::Collections']]],
  ['icollection_3c_20string_20_3e',['ICollection&lt; string &gt;',['../interface_system_1_1_collections_1_1_i_collection.html',1,'System::Collections']]],
  ['icollection_3c_20t_20_3e',['ICollection&lt; T &gt;',['../interface_system_1_1_collections_1_1_i_collection.html',1,'System::Collections']]],
  ['icollection_3c_20telement_20_3e',['ICollection&lt; TElement &gt;',['../interface_system_1_1_collections_1_1_i_collection.html',1,'System::Collections']]],
  ['icollection_3c_20tkey_20_3e',['ICollection&lt; TKey &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_collection.html',1,'System.Collections.Generic.ICollection&lt; TKey &gt;'],['../interface_system_1_1_collections_1_1_i_collection.html',1,'System.Collections.ICollection&lt; TKey &gt;']]],
  ['icollection_3c_20tvalue_20_3e',['ICollection&lt; TValue &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_collection.html',1,'System.Collections.Generic.ICollection&lt; TValue &gt;'],['../interface_system_1_1_collections_1_1_i_collection.html',1,'System.Collections.ICollection&lt; TValue &gt;']]],
  ['icollection_3c_20unicastipaddressinformation_20_3e',['ICollection&lt; UnicastIPAddressInformation &gt;',['../interface_system_1_1_collections_1_1_i_collection.html',1,'System::Collections']]],
  ['icomnativedescriptorhandler',['IComNativeDescriptorHandler',['../interface_system_1_1_component_model_1_1_i_com_native_descriptor_handler.html',1,'System::ComponentModel']]],
  ['icomparable',['IComparable',['../interface_system_1_1_i_comparable.html',1,'System.IComparable'],['../interface_system_1_1_i_comparable.html',1,'System.IComparable&lt; in in T &gt;']]],
  ['icomparable_3c_20bool_20_3e',['IComparable&lt; bool &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20byte_20_3e',['IComparable&lt; byte &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20char_20_3e',['IComparable&lt; char &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20datetime_20_3e',['IComparable&lt; DateTime &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20datetimeoffset_20_3e',['IComparable&lt; DateTimeOffset &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20decimal_20_3e',['IComparable&lt; decimal &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20double_20_3e',['IComparable&lt; double &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20float_20_3e',['IComparable&lt; float &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20guid_20_3e',['IComparable&lt; Guid &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20int_20_3e',['IComparable&lt; int &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20long_20_3e',['IComparable&lt; long &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20sbyte_20_3e',['IComparable&lt; sbyte &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20securityidentifier_20_3e',['IComparable&lt; SecurityIdentifier &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20short_20_3e',['IComparable&lt; short &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20string_20_3e',['IComparable&lt; string &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20timespan_20_3e',['IComparable&lt; TimeSpan &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20uint_20_3e',['IComparable&lt; uint &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20ulong_20_3e',['IComparable&lt; ulong &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20ushort_20_3e',['IComparable&lt; ushort &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20valuetuple_20_3e',['IComparable&lt; ValueTuple &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20version_20_3e',['IComparable&lt; Version &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_28t1_2c_20t2_29_3e',['IComparable&lt;(T1, T2)&gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_28t1_2c_20t2_2c_20t3_29_3e',['IComparable&lt;(T1, T2, T3)&gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_28t1_2c_20t2_2c_20t3_2c_20t4_29_3e',['IComparable&lt;(T1, T2, T3, T4)&gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_28t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_29_3e',['IComparable&lt;(T1, T2, T3, T4, T5)&gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_28t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_2c_20t6_29_3e',['IComparable&lt;(T1, T2, T3, T4, T5, T6)&gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_28t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_2c_20t6_2c_20t7_29_3e',['IComparable&lt;(T1, T2, T3, T4, T5, T6, T7)&gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparer',['IComparer',['../interface_system_1_1_collections_1_1_generic_1_1_i_comparer.html',1,'System.Collections.Generic.IComparer&lt; in in T &gt;'],['../interface_system_1_1_collections_1_1_i_comparer.html',1,'System.Collections.IComparer']]],
  ['icomparer_3c_20concatkey_3c_20tleftkey_2c_20trightkey_20_3e_20_3e',['IComparer&lt; ConcatKey&lt; TLeftKey, TRightKey &gt; &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_comparer.html',1,'System::Collections::Generic']]],
  ['icomparer_3c_20object_20_3e',['IComparer&lt; object &gt;',['../interface_system_1_1_collections_1_1_i_comparer.html',1,'System::Collections']]],
  ['icomparer_3c_20producer_3c_20tkey_20_3e_20_3e',['IComparer&lt; Producer&lt; TKey &gt; &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_comparer.html',1,'System::Collections::Generic']]],
  ['icomparer_3c_20singlerange_20_3e',['IComparer&lt; SingleRange &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_comparer.html',1,'System::Collections::Generic']]],
  ['icomparer_3c_20string_20_3e',['IComparer&lt; string &gt;',['../interface_system_1_1_collections_1_1_i_comparer.html',1,'System::Collections']]],
  ['icomparer_3c_20t_20_3e',['IComparer&lt; T &gt;',['../interface_system_1_1_collections_1_1_i_comparer.html',1,'System.Collections.IComparer&lt; T &gt;'],['../interface_system_1_1_collections_1_1_generic_1_1_i_comparer.html',1,'System.Collections.Generic.IComparer&lt; T &gt;']]],
  ['icomparer_3c_20telement_20_3e',['IComparer&lt; TElement &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_comparer.html',1,'System::Collections::Generic']]],
  ['icomparer_3c_20timezoneinfo_20_3e',['IComparer&lt; TimeZoneInfo &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_comparer.html',1,'System::Collections::Generic']]],
  ['icomparer_3c_20tkey_20_3e',['IComparer&lt; TKey &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_comparer.html',1,'System.Collections.Generic.IComparer&lt; TKey &gt;'],['../interface_system_1_1_collections_1_1_i_comparer.html',1,'System.Collections.IComparer&lt; TKey &gt;']]],
  ['icomparer_3c_20tleftkey_20_3e',['IComparer&lt; TLeftKey &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_comparer.html',1,'System::Collections::Generic']]],
  ['icomparer_3c_20torderkey_20_3e',['IComparer&lt; TOrderKey &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_comparer.html',1,'System.Collections.Generic.IComparer&lt; TOrderKey &gt;'],['../interface_system_1_1_collections_1_1_i_comparer.html',1,'System.Collections.IComparer&lt; TOrderKey &gt;']]],
  ['icomparer_3c_20trightkey_20_3e',['IComparer&lt; TRightKey &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_comparer.html',1,'System::Collections::Generic']]],
  ['icomparer_3c_20tsortkey_20_3e',['IComparer&lt; TSortKey &gt;',['../interface_system_1_1_collections_1_1_i_comparer.html',1,'System.Collections.IComparer&lt; TSortKey &gt;'],['../interface_system_1_1_collections_1_1_generic_1_1_i_comparer.html',1,'System.Collections.Generic.IComparer&lt; TSortKey &gt;']]],
  ['icomparer_3c_20u_20_3e',['IComparer&lt; U &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_comparer.html',1,'System::Collections::Generic']]],
  ['icomponent',['IComponent',['../interface_system_1_1_component_model_1_1_i_component.html',1,'System::ComponentModel']]],
  ['icomponentchangeservice',['IComponentChangeService',['../interface_system_1_1_component_model_1_1_design_1_1_i_component_change_service.html',1,'System::ComponentModel::Design']]],
  ['icomponentdiscoveryservice',['IComponentDiscoveryService',['../interface_system_1_1_component_model_1_1_design_1_1_i_component_discovery_service.html',1,'System::ComponentModel::Design']]],
  ['icomponentinitializer',['IComponentInitializer',['../interface_system_1_1_component_model_1_1_design_1_1_i_component_initializer.html',1,'System::ComponentModel::Design']]],
  ['iconfigurationsectionhandler',['IConfigurationSectionHandler',['../interface_system_1_1_configuration_1_1_i_configuration_section_handler.html',1,'System::Configuration']]],
  ['iconfigurationsystem',['IConfigurationSystem',['../interface_system_1_1_configuration_1_1_i_configuration_system.html',1,'System::Configuration']]],
  ['iconnectionpoint',['IConnectionPoint',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_connection_point.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['iconnectionpointcontainer',['IConnectionPointContainer',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_connection_point_container.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['iconstructioncallmessage',['IConstructionCallMessage',['../interface_system_1_1_runtime_1_1_remoting_1_1_activation_1_1_i_construction_call_message.html',1,'System::Runtime::Remoting::Activation']]],
  ['iconstructionreturnmessage',['IConstructionReturnMessage',['../interface_system_1_1_runtime_1_1_remoting_1_1_activation_1_1_i_construction_return_message.html',1,'System::Runtime::Remoting::Activation']]],
  ['icontainer',['IContainer',['../interface_system_1_1_component_model_1_1_i_container.html',1,'System::ComponentModel']]],
  ['icontextattribute',['IContextAttribute',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_context_attribute.html',1,'System::Runtime::Remoting::Contexts']]],
  ['icontextproperty',['IContextProperty',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_context_property.html',1,'System::Runtime::Remoting::Contexts']]],
  ['icontextpropertyactivator',['IContextPropertyActivator',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_context_property_activator.html',1,'System::Runtime::Remoting::Contexts']]],
  ['icontributeclientcontextsink',['IContributeClientContextSink',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_contribute_client_context_sink.html',1,'System::Runtime::Remoting::Contexts']]],
  ['icontributedynamicsink',['IContributeDynamicSink',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_contribute_dynamic_sink.html',1,'System::Runtime::Remoting::Contexts']]],
  ['icontributeenvoysink',['IContributeEnvoySink',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_contribute_envoy_sink.html',1,'System::Runtime::Remoting::Contexts']]],
  ['icontributeobjectsink',['IContributeObjectSink',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_contribute_object_sink.html',1,'System::Runtime::Remoting::Contexts']]],
  ['icontributeservercontextsink',['IContributeServerContextSink',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_contribute_server_context_sink.html',1,'System::Runtime::Remoting::Contexts']]],
  ['iconvertible',['IConvertible',['../interface_system_1_1_i_convertible.html',1,'System']]],
  ['icredentialpolicy',['ICredentialPolicy',['../interface_system_1_1_net_1_1_i_credential_policy.html',1,'System::Net']]],
  ['icredentials',['ICredentials',['../interface_system_1_1_net_1_1_i_credentials.html',1,'System::Net']]],
  ['icredentialsbyhost',['ICredentialsByHost',['../interface_system_1_1_net_1_1_i_credentials_by_host.html',1,'System::Net']]],
  ['icriticalnotifycompletion',['ICriticalNotifyCompletion',['../interface_system_1_1_runtime_1_1_compiler_services_1_1_i_critical_notify_completion.html',1,'System::Runtime::CompilerServices']]],
  ['icryptotransform',['ICryptoTransform',['../interface_system_1_1_security_1_1_cryptography_1_1_i_crypto_transform.html',1,'System::Security::Cryptography']]],
  ['icspasymmetricalgorithm',['ICspAsymmetricAlgorithm',['../interface_system_1_1_security_1_1_cryptography_1_1_i_csp_asymmetric_algorithm.html',1,'System::Security::Cryptography']]],
  ['icustomadapter',['ICustomAdapter',['../interface_system_1_1_runtime_1_1_interop_services_1_1_i_custom_adapter.html',1,'System::Runtime::InteropServices']]],
  ['icustomattributeprovider',['ICustomAttributeProvider',['../interface_system_1_1_reflection_1_1_i_custom_attribute_provider.html',1,'System::Reflection']]],
  ['icustomfactory',['ICustomFactory',['../interface_system_1_1_runtime_1_1_interop_services_1_1_i_custom_factory.html',1,'System::Runtime::InteropServices']]],
  ['icustomformatter',['ICustomFormatter',['../interface_system_1_1_i_custom_formatter.html',1,'System']]],
  ['icustommarshaler',['ICustomMarshaler',['../interface_system_1_1_runtime_1_1_interop_services_1_1_i_custom_marshaler.html',1,'System::Runtime::InteropServices']]],
  ['icustomqueryinterface',['ICustomQueryInterface',['../interface_system_1_1_runtime_1_1_interop_services_1_1_i_custom_query_interface.html',1,'System::Runtime::InteropServices']]],
  ['icustomtypedescriptor',['ICustomTypeDescriptor',['../interface_system_1_1_component_model_1_1_i_custom_type_descriptor.html',1,'System::ComponentModel']]],
  ['icustomtypeprovider',['ICustomTypeProvider',['../interface_system_1_1_reflection_1_1_i_custom_type_provider.html',1,'System::Reflection']]],
  ['idataerrorinfo',['IDataErrorInfo',['../interface_system_1_1_component_model_1_1_i_data_error_info.html',1,'System::ComponentModel']]],
  ['idataobject',['IDataObject',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_data_object.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['identitynotmappedexception',['IdentityNotMappedException',['../class_system_1_1_security_1_1_principal_1_1_identity_not_mapped_exception.html',1,'System::Security::Principal']]],
  ['identityreference',['IdentityReference',['../class_system_1_1_security_1_1_principal_1_1_identity_reference.html',1,'System::Security::Principal']]],
  ['identityreferencecollection',['IdentityReferenceCollection',['../class_system_1_1_security_1_1_principal_1_1_identity_reference_collection.html',1,'System::Security::Principal']]],
  ['ideserializationcallback',['IDeserializationCallback',['../interface_system_1_1_runtime_1_1_serialization_1_1_i_deserialization_callback.html',1,'System::Runtime::Serialization']]],
  ['idesigner',['IDesigner',['../interface_system_1_1_component_model_1_1_design_1_1_i_designer.html',1,'System::ComponentModel::Design']]],
  ['idesignereventservice',['IDesignerEventService',['../interface_system_1_1_component_model_1_1_design_1_1_i_designer_event_service.html',1,'System::ComponentModel::Design']]],
  ['idesignerfilter',['IDesignerFilter',['../interface_system_1_1_component_model_1_1_design_1_1_i_designer_filter.html',1,'System::ComponentModel::Design']]],
  ['idesignerhost',['IDesignerHost',['../interface_system_1_1_component_model_1_1_design_1_1_i_designer_host.html',1,'System::ComponentModel::Design']]],
  ['idesignerhosttransactionstate',['IDesignerHostTransactionState',['../interface_system_1_1_component_model_1_1_design_1_1_i_designer_host_transaction_state.html',1,'System::ComponentModel::Design']]],
  ['idesignerloaderhost',['IDesignerLoaderHost',['../interface_system_1_1_component_model_1_1_design_1_1_serialization_1_1_i_designer_loader_host.html',1,'System::ComponentModel::Design::Serialization']]],
  ['idesignerloaderhost2',['IDesignerLoaderHost2',['../interface_system_1_1_component_model_1_1_design_1_1_serialization_1_1_i_designer_loader_host2.html',1,'System::ComponentModel::Design::Serialization']]],
  ['idesignerloaderservice',['IDesignerLoaderService',['../interface_system_1_1_component_model_1_1_design_1_1_serialization_1_1_i_designer_loader_service.html',1,'System::ComponentModel::Design::Serialization']]],
  ['idesigneroptionservice',['IDesignerOptionService',['../interface_system_1_1_component_model_1_1_design_1_1_i_designer_option_service.html',1,'System::ComponentModel::Design']]],
  ['idesignerserializationmanager',['IDesignerSerializationManager',['../interface_system_1_1_component_model_1_1_design_1_1_serialization_1_1_i_designer_serialization_manager.html',1,'System::ComponentModel::Design::Serialization']]],
  ['idesignerserializationprovider',['IDesignerSerializationProvider',['../interface_system_1_1_component_model_1_1_design_1_1_serialization_1_1_i_designer_serialization_provider.html',1,'System::ComponentModel::Design::Serialization']]],
  ['idesignerserializationservice',['IDesignerSerializationService',['../interface_system_1_1_component_model_1_1_design_1_1_serialization_1_1_i_designer_serialization_service.html',1,'System::ComponentModel::Design::Serialization']]],
  ['idictionary',['IDictionary',['../interface_system_1_1_collections_1_1_generic_1_1_i_dictionary.html',1,'System.Collections.Generic.IDictionary&lt; TKey, TValue &gt;'],['../interface_system_1_1_collections_1_1_i_dictionary.html',1,'System.Collections.IDictionary']]],
  ['idictionary_3c_20k_2c_20v_20_3e',['IDictionary&lt; K, V &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_dictionary.html',1,'System::Collections::Generic']]],
  ['idictionary_3c_20string_2c_20object_20_3e',['IDictionary&lt; string, object &gt;',['../interface_system_1_1_collections_1_1_i_dictionary.html',1,'System.Collections.IDictionary&lt; string, object &gt;'],['../interface_system_1_1_collections_1_1_generic_1_1_i_dictionary.html',1,'System.Collections.Generic.IDictionary&lt; string, object &gt;']]],
  ['idictionary_3c_20string_2c_20string_20_3e',['IDictionary&lt; string, string &gt;',['../interface_system_1_1_collections_1_1_i_dictionary.html',1,'System.Collections.IDictionary&lt; string, string &gt;'],['../interface_system_1_1_collections_1_1_generic_1_1_i_dictionary.html',1,'System.Collections.Generic.IDictionary&lt; string, string &gt;']]],
  ['idictionary_3c_20string_2c_20system_3a_3atimespan_20_3e',['IDictionary&lt; string, System::TimeSpan &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_dictionary.html',1,'System::Collections::Generic']]],
  ['idictionary_3c_20string_2c_20trackingvalidationobjectdictionary_2evalidateandparsevalue_20_3e',['IDictionary&lt; string, TrackingValidationObjectDictionary.ValidateAndParseValue &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_dictionary.html',1,'System::Collections::Generic']]],
  ['idictionary_3c_20string_2c_20validateandparsevalue_20_3e',['IDictionary&lt; string, ValidateAndParseValue &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_dictionary.html',1,'System::Collections::Generic']]],
  ['idictionary_3c_20tkey_2c_20system_3a_3alinq_3a_3aigrouping_3c_20tkey_2c_20telement_20_3e_20_3e',['IDictionary&lt; TKey, System::Linq::IGrouping&lt; TKey, TElement &gt; &gt;',['../interface_system_1_1_collections_1_1_i_dictionary.html',1,'System::Collections']]],
  ['idictionary_3c_20tkey_2c_20tvalue_20_3e',['IDictionary&lt; TKey, TValue &gt;',['../interface_system_1_1_collections_1_1_i_dictionary.html',1,'System::Collections']]],
  ['idictionaryenumerator',['IDictionaryEnumerator',['../interface_system_1_1_collections_1_1_i_dictionary_enumerator.html',1,'System::Collections']]],
  ['idictionaryservice',['IDictionaryService',['../interface_system_1_1_component_model_1_1_design_1_1_i_dictionary_service.html',1,'System::ComponentModel::Design']]],
  ['idispatchconstantattribute',['IDispatchConstantAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_i_dispatch_constant_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['idispatchimplattribute',['IDispatchImplAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_i_dispatch_impl_attribute.html',1,'System::Runtime::InteropServices']]],
  ['idisposable',['IDisposable',['../interface_system_1_1_i_disposable.html',1,'System']]],
  ['idldesc',['IDLDESC',['../struct_system_1_1_runtime_1_1_interop_services_1_1_i_d_l_d_e_s_c.html',1,'System.Runtime.InteropServices.IDLDESC'],['../struct_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_d_l_d_e_s_c.html',1,'System.Runtime.InteropServices.ComTypes.IDLDESC']]],
  ['idnelement',['IdnElement',['../class_system_1_1_configuration_1_1_idn_element.html',1,'System::Configuration']]],
  ['idnmapping',['IdnMapping',['../class_system_1_1_globalization_1_1_idn_mapping.html',1,'System::Globalization']]],
  ['idynamicexpression',['IDynamicExpression',['../interface_system_1_1_linq_1_1_expressions_1_1_i_dynamic_expression.html',1,'System::Linq::Expressions']]],
  ['idynamicmessagesink',['IDynamicMessageSink',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_dynamic_message_sink.html',1,'System::Runtime::Remoting::Contexts']]],
  ['idynamicmetaobjectprovider',['IDynamicMetaObjectProvider',['../interface_system_1_1_dynamic_1_1_i_dynamic_meta_object_provider.html',1,'System::Dynamic']]],
  ['idynamicproperty',['IDynamicProperty',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_dynamic_property.html',1,'System::Runtime::Remoting::Contexts']]],
  ['ieditableobject',['IEditableObject',['../interface_system_1_1_component_model_1_1_i_editable_object.html',1,'System::ComponentModel']]],
  ['ienumconnectionpoints',['IEnumConnectionPoints',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_enum_connection_points.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['ienumconnections',['IEnumConnections',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_enum_connections.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['ienumerable',['IEnumerable',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerable.html',1,'System.Collections.Generic.IEnumerable&lt; out out T &gt;'],['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System.Collections.IEnumerable']]],
  ['ienumerable_3c_20char_20_3e',['IEnumerable&lt; char &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20claim_20_3e',['IEnumerable&lt; Claim &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerable.html',1,'System::Collections::Generic']]],
  ['ienumerable_3c_20cultureinfo_20_3e',['IEnumerable&lt; CultureInfo &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20evidencebase_20_3e',['IEnumerable&lt; EvidenceBase &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20expression_20_3e',['IEnumerable&lt; Expression &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20gatewayipaddressinformation_20_3e',['IEnumerable&lt; GatewayIPAddressInformation &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20idelayevaluatedevidence_20_3e',['IEnumerable&lt; IDelayEvaluatedEvidence &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20identityreference_20_3e',['IEnumerable&lt; IdentityReference &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20ipaddress_20_3e',['IEnumerable&lt; IPAddress &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20ipaddressinformation_20_3e',['IEnumerable&lt; IPAddressInformation &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20keyvaluepair_3c_20long_2c_20tsource_20_3e_20_3e',['IEnumerable&lt; KeyValuePair&lt; long, TSource &gt; &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20multicastipaddressinformation_20_3e',['IEnumerable&lt; MulticastIPAddressInformation &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20object_20_3e',['IEnumerable&lt; object &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20sequencepoint_20_3e',['IEnumerable&lt; SequencePoint &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20string_20_3e',['IEnumerable&lt; string &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerable.html',1,'System.Collections.Generic.IEnumerable&lt; string &gt;'],['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System.Collections.IEnumerable&lt; string &gt;']]],
  ['ienumerable_3c_20system_3a_3asecurity_3a_3aclaims_3a_3aclaimsidentity_20_3e',['IEnumerable&lt; System::Security::Claims::ClaimsIdentity &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerable.html',1,'System::Collections::Generic']]],
  ['ienumerable_3c_20system_3a_3athreading_3a_3atasks_3a_3atask_20_3e',['IEnumerable&lt; System::Threading::Tasks::Task &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerable.html',1,'System::Collections::Generic']]],
  ['ienumerable_3c_20system_3a_3auri_20_3e',['IEnumerable&lt; System::Uri &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerable.html',1,'System::Collections::Generic']]],
  ['ienumerable_3c_20t_20_3e',['IEnumerable&lt; T &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System.Collections.IEnumerable&lt; T &gt;'],['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerable.html',1,'System.Collections.Generic.IEnumerable&lt; T &gt;']]],
  ['ienumerable_3c_20telement_20_3e',['IEnumerable&lt; TElement &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System.Collections.IEnumerable&lt; TElement &gt;'],['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerable.html',1,'System.Collections.Generic.IEnumerable&lt; TElement &gt;']]],
  ['ienumerable_3c_20tinputoutput_20_3e',['IEnumerable&lt; TInputOutput &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20tkey_20_3e',['IEnumerable&lt; TKey &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerable.html',1,'System.Collections.Generic.IEnumerable&lt; TKey &gt;'],['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System.Collections.IEnumerable&lt; TKey &gt;']]],
  ['ienumerable_3c_20tresult_20_3e',['IEnumerable&lt; TResult &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20tsource_20_3e',['IEnumerable&lt; TSource &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20tvalue_20_3e',['IEnumerable&lt; TValue &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System.Collections.IEnumerable&lt; TValue &gt;'],['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerable.html',1,'System.Collections.Generic.IEnumerable&lt; TValue &gt;']]],
  ['ienumerable_3c_20unicastipaddressinformation_20_3e',['IEnumerable&lt; UnicastIPAddressInformation &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20uri_20_3e',['IEnumerable&lt; Uri &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20xmlschema_20_3e',['IEnumerable&lt; XmlSchema &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerator',['IEnumerator',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerator.html',1,'System.Collections.Generic.IEnumerator&lt; out out T &gt;'],['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System.Collections.IEnumerator']]],
  ['ienumerator_3c_20char_20_3e',['IEnumerator&lt; char &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System::Collections']]],
  ['ienumerator_3c_20evidencebase_20_3e',['IEnumerator&lt; EvidenceBase &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System::Collections']]],
  ['ienumerator_3c_20identityreference_20_3e',['IEnumerator&lt; IdentityReference &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System::Collections']]],
  ['ienumerator_3c_20keyvaluepair_3c_20long_2c_20telement_20_3e_20_3e',['IEnumerator&lt; KeyValuePair&lt; long, TElement &gt; &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerator.html',1,'System::Collections::Generic']]],
  ['ienumerator_3c_20keyvaluepair_3c_20long_2c_20tsource_20_3e_20_3e',['IEnumerator&lt; KeyValuePair&lt; long, TSource &gt; &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System::Collections']]],
  ['ienumerator_3c_20keyvaluepair_3c_20tkey_2c_20tvalue_20_3e_20_3e',['IEnumerator&lt; KeyValuePair&lt; TKey, TValue &gt; &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System::Collections']]],
  ['ienumerator_3c_20keyvaluepair_3c_20wrapper_3c_20tinputoutput_20_3e_2c_20pair_3c_20tinputoutput_2c_20concatkey_3c_20tleftkey_2c_20trightkey_20_3e_20_3e_20_3e_20_3e',['IEnumerator&lt; KeyValuePair&lt; Wrapper&lt; TInputOutput &gt;, Pair&lt; TInputOutput, ConcatKey&lt; TLeftKey, TRightKey &gt; &gt; &gt; &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerator.html',1,'System::Collections::Generic']]],
  ['ienumerator_3c_20keyvaluepair_3c_20wrapper_3c_20tinputoutput_20_3e_2c_20pair_3c_20tinputoutput_2c_20tleftkey_20_3e_20_3e_20_3e',['IEnumerator&lt; KeyValuePair&lt; Wrapper&lt; TInputOutput &gt;, Pair&lt; TInputOutput, TLeftKey &gt; &gt; &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerator.html',1,'System::Collections::Generic']]],
  ['ienumerator_3c_20keyvaluepair_3c_20wrapper_3c_20tinputoutput_20_3e_2c_20tkey_20_3e_20_3e',['IEnumerator&lt; KeyValuePair&lt; Wrapper&lt; TInputOutput &gt;, TKey &gt; &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerator.html',1,'System::Collections::Generic']]],
  ['ienumerator_3c_20mimebasepart_20_3e',['IEnumerator&lt; MimeBasePart &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerator.html',1,'System::Collections::Generic']]],
  ['ienumerator_3c_20object_20_3e',['IEnumerator&lt; object &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System::Collections']]],
  ['ienumerator_3c_20sequencepoint_20_3e',['IEnumerator&lt; SequencePoint &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System::Collections']]],
  ['ienumerator_3c_20string_20_3e',['IEnumerator&lt; string &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System::Collections']]],
  ['ienumerator_3c_20t_20_3e',['IEnumerator&lt; T &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerator.html',1,'System::Collections::Generic']]],
  ['ienumerator_3c_20telement_20_3e',['IEnumerator&lt; TElement &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System.Collections.IEnumerator&lt; TElement &gt;'],['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerator.html',1,'System.Collections.Generic.IEnumerator&lt; TElement &gt;']]],
  ['ienumerator_3c_20tinputoutput_20_3e',['IEnumerator&lt; TInputOutput &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System.Collections.IEnumerator&lt; TInputOutput &gt;'],['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerator.html',1,'System.Collections.Generic.IEnumerator&lt; TInputOutput &gt;']]],
  ['ienumerator_3c_20tkey_20_3e',['IEnumerator&lt; TKey &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerator.html',1,'System::Collections::Generic']]],
  ['ienumerator_3c_20toutput_20_3e',['IEnumerator&lt; TOutput &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System.Collections.IEnumerator&lt; TOutput &gt;'],['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerator.html',1,'System.Collections.Generic.IEnumerator&lt; TOutput &gt;']]],
  ['ienumerator_3c_20trightinput_20_3e',['IEnumerator&lt; TRightInput &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerator.html',1,'System::Collections::Generic']]],
  ['ienumerator_3c_20tsource_20_3e',['IEnumerator&lt; TSource &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System::Collections']]],
  ['ienumerator_3c_20tvalue_20_3e',['IEnumerator&lt; TValue &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System.Collections.IEnumerator&lt; TValue &gt;'],['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerator.html',1,'System.Collections.Generic.IEnumerator&lt; TValue &gt;']]],
  ['ienumerator_3c_20uri_20_3e',['IEnumerator&lt; Uri &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System::Collections']]],
  ['ienumerator_3c_20xmlschema_20_3e',['IEnumerator&lt; XmlSchema &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System::Collections']]],
  ['ienumformatetc',['IEnumFORMATETC',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_enum_f_o_r_m_a_t_e_t_c.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['ienummoniker',['IEnumMoniker',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_enum_moniker.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['ienumstatdata',['IEnumSTATDATA',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_enum_s_t_a_t_d_a_t_a.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['ienumstring',['IEnumString',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_enum_string.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['ienumvariant',['IEnumVARIANT',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_enum_v_a_r_i_a_n_t.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['ienvoyinfo',['IEnvoyInfo',['../interface_system_1_1_runtime_1_1_remoting_1_1_i_envoy_info.html',1,'System::Runtime::Remoting']]],
  ['iequalitycomparer',['IEqualityComparer',['../interface_system_1_1_collections_1_1_generic_1_1_i_equality_comparer.html',1,'System.Collections.Generic.IEqualityComparer&lt; in in T &gt;'],['../interface_system_1_1_collections_1_1_i_equality_comparer.html',1,'System.Collections.IEqualityComparer']]],
  ['iequalitycomparer_3c_20eventcachekey_20_3e',['IEqualityComparer&lt; EventCacheKey &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_equality_comparer.html',1,'System::Collections::Generic']]],
  ['iequalitycomparer_3c_20string_20_3e',['IEqualityComparer&lt; string &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_equality_comparer.html',1,'System::Collections::Generic']]],
  ['iequalitycomparer_3c_20t_20_3e',['IEqualityComparer&lt; T &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_equality_comparer.html',1,'System::Collections::Generic']]],
  ['iequalitycomparer_3c_20telement_20_3e',['IEqualityComparer&lt; TElement &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_equality_comparer.html',1,'System::Collections::Generic']]],
  ['iequalitycomparer_3c_20tgroupkey_20_3e',['IEqualityComparer&lt; TGroupKey &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_equality_comparer.html',1,'System::Collections::Generic']]],
  ['iequalitycomparer_3c_20thashkey_20_3e',['IEqualityComparer&lt; THashKey &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_equality_comparer.html',1,'System::Collections::Generic']]],
  ['iequalitycomparer_3c_20tinput_20_3e',['IEqualityComparer&lt; TInput &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_equality_comparer.html',1,'System::Collections::Generic']]],
  ['iequalitycomparer_3c_20tinputoutput_20_3e',['IEqualityComparer&lt; TInputOutput &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_equality_comparer.html',1,'System::Collections::Generic']]],
  ['iequalitycomparer_3c_20tkey_20_3e',['IEqualityComparer&lt; TKey &gt;',['../interface_system_1_1_collections_1_1_i_equality_comparer.html',1,'System.Collections.IEqualityComparer&lt; TKey &gt;'],['../interface_system_1_1_collections_1_1_generic_1_1_i_equality_comparer.html',1,'System.Collections.Generic.IEqualityComparer&lt; TKey &gt;']]],
  ['iequalitycomparer_3c_20type_20_3e',['IEqualityComparer&lt; Type &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_equality_comparer.html',1,'System::Collections::Generic']]],
  ['iequalitycomparer_3c_20wrapper_3c_20tinputoutput_20_3e_20_3e',['IEqualityComparer&lt; Wrapper&lt; TInputOutput &gt; &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_equality_comparer.html',1,'System::Collections::Generic']]],
  ['iequatable',['IEquatable',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20adjustmentrule_20_3e',['IEquatable&lt; AdjustmentRule &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20blobcontentid_20_3e',['IEquatable&lt; BlobContentId &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20blobhandle_20_3e',['IEquatable&lt; BlobHandle &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20bool_20_3e',['IEquatable&lt; bool &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20byte_20_3e',['IEquatable&lt; byte &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20cancellationtokenregistration_20_3e',['IEquatable&lt; CancellationTokenRegistration &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20char_20_3e',['IEquatable&lt; char &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20cngalgorithm_20_3e',['IEquatable&lt; CngAlgorithm &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20cngalgorithmgroup_20_3e',['IEquatable&lt; CngAlgorithmGroup &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20cngkeyblobformat_20_3e',['IEquatable&lt; CngKeyBlobFormat &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20cngproperty_20_3e',['IEquatable&lt; CngProperty &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20cngprovider_20_3e',['IEquatable&lt; CngProvider &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20datetime_20_3e',['IEquatable&lt; DateTime &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20datetimeoffset_20_3e',['IEquatable&lt; DateTimeOffset &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20decimal_20_3e',['IEquatable&lt; decimal &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20documenthandle_20_3e',['IEquatable&lt; DocumentHandle &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20documentnameblobhandle_20_3e',['IEquatable&lt; DocumentNameBlobHandle &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20double_20_3e',['IEquatable&lt; double &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20exceptionhandler_20_3e',['IEquatable&lt; ExceptionHandler &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20float_20_3e',['IEquatable&lt; float &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20frameworkname_20_3e',['IEquatable&lt; FrameworkName &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20guid_20_3e',['IEquatable&lt; Guid &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20handle_20_3e',['IEquatable&lt; Handle &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20hashalgorithmname_20_3e',['IEquatable&lt; HashAlgorithmName &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20int_20_3e',['IEquatable&lt; int &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20long_20_3e',['IEquatable&lt; long &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20methoddebuginformationhandle_20_3e',['IEquatable&lt; MethodDebugInformationHandle &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20methoddefinitionhandle_20_3e',['IEquatable&lt; MethodDefinitionHandle &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20osplatform_20_3e',['IEquatable&lt; OSPlatform &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20rsaencryptionpadding_20_3e',['IEquatable&lt; RSAEncryptionPadding &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20rsasignaturepadding_20_3e',['IEquatable&lt; RSASignaturePadding &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20sbyte_20_3e',['IEquatable&lt; sbyte &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20sequencepoint_20_3e',['IEquatable&lt; SequencePoint &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20short_20_3e',['IEquatable&lt; short &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20sortversion_20_3e',['IEquatable&lt; SortVersion &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20string_20_3e',['IEquatable&lt; string &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20timespan_20_3e',['IEquatable&lt; TimeSpan &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20timezoneinfo_20_3e',['IEquatable&lt; TimeZoneInfo &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20transitiontime_20_3e',['IEquatable&lt; TransitionTime &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20typedconstant_20_3e',['IEquatable&lt; TypedConstant &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20udpreceiveresult_20_3e',['IEquatable&lt; UdpReceiveResult &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20uint_20_3e',['IEquatable&lt; uint &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20ulong_20_3e',['IEquatable&lt; ulong &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20ushort_20_3e',['IEquatable&lt; ushort &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20valuetuple_20_3e',['IEquatable&lt; ValueTuple &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20version_20_3e',['IEquatable&lt; Version &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_28t1_2c_20t2_29_3e',['IEquatable&lt;(T1, T2)&gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_28t1_2c_20t2_2c_20t3_29_3e',['IEquatable&lt;(T1, T2, T3)&gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_28t1_2c_20t2_2c_20t3_2c_20t4_29_3e',['IEquatable&lt;(T1, T2, T3, T4)&gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_28t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_29_3e',['IEquatable&lt;(T1, T2, T3, T4, T5)&gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_28t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_2c_20t6_29_3e',['IEquatable&lt;(T1, T2, T3, T4, T5, T6)&gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_28t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_2c_20t6_2c_20t7_29_3e',['IEquatable&lt;(T1, T2, T3, T4, T5, T6, T7)&gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['ieventbindingservice',['IEventBindingService',['../interface_system_1_1_component_model_1_1_design_1_1_i_event_binding_service.html',1,'System::ComponentModel::Design']]],
  ['ievidencefactory',['IEvidenceFactory',['../interface_system_1_1_security_1_1_i_evidence_factory.html',1,'System::Security']]],
  ['iexpando',['IExpando',['../interface_system_1_1_runtime_1_1_interop_services_1_1_expando_1_1_i_expando.html',1,'System::Runtime::InteropServices::Expando']]],
  ['iextenderlistservice',['IExtenderListService',['../interface_system_1_1_component_model_1_1_design_1_1_i_extender_list_service.html',1,'System::ComponentModel::Design']]],
  ['iextenderprovider',['IExtenderProvider',['../interface_system_1_1_component_model_1_1_i_extender_provider.html',1,'System::ComponentModel']]],
  ['iextenderproviderservice',['IExtenderProviderService',['../interface_system_1_1_component_model_1_1_design_1_1_i_extender_provider_service.html',1,'System::ComponentModel::Design']]],
  ['ifieldinfo',['IFieldInfo',['../interface_system_1_1_runtime_1_1_serialization_1_1_formatters_1_1_i_field_info.html',1,'System::Runtime::Serialization::Formatters']]],
  ['iformatprovider',['IFormatProvider',['../interface_system_1_1_i_format_provider.html',1,'System']]],
  ['iformattable',['IFormattable',['../interface_system_1_1_i_formattable.html',1,'System']]],
  ['iformatter',['IFormatter',['../interface_system_1_1_runtime_1_1_serialization_1_1_i_formatter.html',1,'System::Runtime::Serialization']]],
  ['iformatterconverter',['IFormatterConverter',['../interface_system_1_1_runtime_1_1_serialization_1_1_i_formatter_converter.html',1,'System::Runtime::Serialization']]],
  ['ignoresectionhandler',['IgnoreSectionHandler',['../class_system_1_1_configuration_1_1_ignore_section_handler.html',1,'System::Configuration']]],
  ['igrouping',['IGrouping',['../interface_system_1_1_linq_1_1_i_grouping.html',1,'System::Linq']]],
  ['igrouping_3c_20tgroupkey_2c_20telement_20_3e',['IGrouping&lt; TGroupKey, TElement &gt;',['../interface_system_1_1_linq_1_1_i_grouping.html',1,'System::Linq']]],
  ['igrouping_3c_20tkey_2c_20telement_20_3e',['IGrouping&lt; TKey, TElement &gt;',['../interface_system_1_1_linq_1_1_i_grouping.html',1,'System::Linq']]],
  ['ihashcodeprovider',['IHashCodeProvider',['../interface_system_1_1_collections_1_1_i_hash_code_provider.html',1,'System::Collections']]],
  ['ihasxmlnode',['IHasXmlNode',['../interface_system_1_1_xml_1_1_i_has_xml_node.html',1,'System::Xml']]],
  ['ihelpservice',['IHelpService',['../interface_system_1_1_component_model_1_1_design_1_1_i_help_service.html',1,'System::ComponentModel::Design']]],
  ['iidentity',['IIdentity',['../interface_system_1_1_security_1_1_principal_1_1_i_identity.html',1,'System::Security::Principal']]],
  ['iidentitypermissionfactory',['IIdentityPermissionFactory',['../interface_system_1_1_security_1_1_policy_1_1_i_identity_permission_factory.html',1,'System::Security::Policy']]],
  ['iinheritanceservice',['IInheritanceService',['../interface_system_1_1_component_model_1_1_design_1_1_i_inheritance_service.html',1,'System::ComponentModel::Design']]],
  ['iintellisensebuilder',['IIntellisenseBuilder',['../interface_system_1_1_component_model_1_1_i_intellisense_builder.html',1,'System::ComponentModel']]],
  ['iinvokeongetbinder',['IInvokeOnGetBinder',['../interface_system_1_1_dynamic_1_1_i_invoke_on_get_binder.html',1,'System::Dynamic']]],
  ['ilease',['ILease',['../interface_system_1_1_runtime_1_1_remoting_1_1_lifetime_1_1_i_lease.html',1,'System::Runtime::Remoting::Lifetime']]],
  ['ilgenerator',['ILGenerator',['../class_system_1_1_reflection_1_1_emit_1_1_i_l_generator.html',1,'System::Reflection::Emit']]],
  ['ilist',['IList',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System.Collections.Generic.IList&lt; T &gt;'],['../interface_system_1_1_collections_1_1_i_list.html',1,'System.Collections.IList']]],
  ['ilist_3c_20char_20_3e',['IList&lt; char &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20expression_20_3e',['IList&lt; Expression &gt;',['../interface_system_1_1_collections_1_1_i_list.html',1,'System::Collections']]],
  ['ilist_3c_20idtddefaultattributeinfo_20_3e',['IList&lt; IDtdDefaultAttributeInfo &gt;',['../interface_system_1_1_collections_1_1_i_list.html',1,'System::Collections']]],
  ['ilist_3c_20object_20_3e',['IList&lt; object &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System.Collections.Generic.IList&lt; object &gt;'],['../interface_system_1_1_collections_1_1_i_list.html',1,'System.Collections.IList&lt; object &gt;']]],
  ['ilist_3c_20string_20_3e',['IList&lt; string &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20system_3a_3aarraysegment_3c_20byte_20_3e_20_3e',['IList&lt; System::ArraySegment&lt; byte &gt; &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20system_3a_3adiagnostics_3a_3aeventing_3a_3areader_3a_3aeventkeyword_20_3e',['IList&lt; System::Diagnostics::Eventing::Reader::EventKeyword &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20system_3a_3adiagnostics_3a_3aeventing_3a_3areader_3a_3aeventlevel_20_3e',['IList&lt; System::Diagnostics::Eventing::Reader::EventLevel &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20system_3a_3adiagnostics_3a_3aeventing_3a_3areader_3a_3aeventloglink_20_3e',['IList&lt; System::Diagnostics::Eventing::Reader::EventLogLink &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20system_3a_3adiagnostics_3a_3aeventing_3a_3areader_3a_3aeventopcode_20_3e',['IList&lt; System::Diagnostics::Eventing::Reader::EventOpcode &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20system_3a_3adiagnostics_3a_3aeventing_3a_3areader_3a_3aeventtask_20_3e',['IList&lt; System::Diagnostics::Eventing::Reader::EventTask &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20system_3a_3alinq_3a_3aexpressions_3a_3aexpression_20_3e',['IList&lt; System::Linq::Expressions::Expression &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20system_3a_3alinq_3a_3aexpressions_3a_3aparameterexpression_20_3e',['IList&lt; System::Linq::Expressions::ParameterExpression &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20system_3a_3areflection_3a_3acustomattributenamedargument_20_3e',['IList&lt; System::Reflection::CustomAttributeNamedArgument &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20system_3a_3areflection_3a_3acustomattributetypedargument_20_3e',['IList&lt; System::Reflection::CustomAttributeTypedArgument &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20system_3a_3areflection_3a_3aexceptionhandlingclause_20_3e',['IList&lt; System::Reflection::ExceptionHandlingClause &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20system_3a_3areflection_3a_3alocalvariableinfo_20_3e',['IList&lt; System::Reflection::LocalVariableInfo &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20system_3a_3asecurity_3a_3apolicy_3a_3astrongname_20_3e',['IList&lt; System::Security::Policy::StrongName &gt;',['../interface_system_1_1_collections_1_1_i_list.html',1,'System::Collections']]],
  ['ilist_3c_20system_3a_3athreading_3a_3atasks_3a_3atask_20_3e',['IList&lt; System::Threading::Tasks::Task &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20t_20_3e',['IList&lt; T &gt;',['../interface_system_1_1_collections_1_1_i_list.html',1,'System::Collections']]],
  ['ilist_3c_20telement_20_3e',['IList&lt; TElement &gt;',['../interface_system_1_1_collections_1_1_i_list.html',1,'System::Collections']]],
  ['ilist_3c_20tkey_20_3e',['IList&lt; TKey &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20tsource_20_3e',['IList&lt; TSource &gt;',['../interface_system_1_1_collections_1_1_i_list.html',1,'System::Collections']]],
  ['ilist_3c_20tvalue_20_3e',['IList&lt; TValue &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilistsource',['IListSource',['../interface_system_1_1_component_model_1_1_i_list_source.html',1,'System::ComponentModel']]],
  ['ilogicalthreadaffinative',['ILogicalThreadAffinative',['../interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_logical_thread_affinative.html',1,'System::Runtime::Remoting::Messaging']]],
  ['ilookup',['ILookup',['../interface_system_1_1_linq_1_1_i_lookup.html',1,'System::Linq']]],
  ['ilookup_3c_20string_2c_20methodinfo_20_3e',['ILookup&lt; string, MethodInfo &gt;',['../interface_system_1_1_linq_1_1_i_lookup.html',1,'System::Linq']]],
  ['image',['Image',['../class_system_1_1_net_1_1_mime_1_1_media_type_names_1_1_image.html',1,'System::Net::Mime::MediaTypeNames']]],
  ['imembershipcondition',['IMembershipCondition',['../interface_system_1_1_security_1_1_policy_1_1_i_membership_condition.html',1,'System::Security::Policy']]],
  ['imenucommandservice',['IMenuCommandService',['../interface_system_1_1_component_model_1_1_design_1_1_i_menu_command_service.html',1,'System::ComponentModel::Design']]],
  ['imessage',['IMessage',['../interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_message.html',1,'System::Runtime::Remoting::Messaging']]],
  ['imessagectrl',['IMessageCtrl',['../interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_message_ctrl.html',1,'System::Runtime::Remoting::Messaging']]],
  ['imessagesink',['IMessageSink',['../interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_message_sink.html',1,'System::Runtime::Remoting::Messaging']]],
  ['imethodcallmessage',['IMethodCallMessage',['../interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_method_call_message.html',1,'System::Runtime::Remoting::Messaging']]],
  ['imethodmessage',['IMethodMessage',['../interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_method_message.html',1,'System::Runtime::Remoting::Messaging']]],
  ['imethodreturnmessage',['IMethodReturnMessage',['../interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_method_return_message.html',1,'System::Runtime::Remoting::Messaging']]],
  ['immutableobjectattribute',['ImmutableObjectAttribute',['../class_system_1_1_component_model_1_1_immutable_object_attribute.html',1,'System::ComponentModel']]],
  ['imoniker',['IMoniker',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_moniker.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['importcontext',['ImportContext',['../class_system_1_1_xml_1_1_serialization_1_1_import_context.html',1,'System::Xml::Serialization']]],
  ['importedfromtypelibattribute',['ImportedFromTypeLibAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_imported_from_type_lib_attribute.html',1,'System::Runtime::InteropServices']]],
  ['inamecreationservice',['INameCreationService',['../interface_system_1_1_component_model_1_1_design_1_1_serialization_1_1_i_name_creation_service.html',1,'System::ComponentModel::Design::Serialization']]],
  ['inattribute',['InAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_in_attribute.html',1,'System::Runtime::InteropServices']]],
  ['incrementalhash',['IncrementalHash',['../class_system_1_1_security_1_1_cryptography_1_1_incremental_hash.html',1,'System::Security::Cryptography']]],
  ['indentedtextwriter',['IndentedTextWriter',['../class_system_1_1_code_dom_1_1_compiler_1_1_indented_text_writer.html',1,'System::CodeDom::Compiler']]],
  ['indexernameattribute',['IndexerNameAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_indexer_name_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['indexexpression',['IndexExpression',['../class_system_1_1_linq_1_1_expressions_1_1_index_expression.html',1,'System::Linq::Expressions']]],
  ['indexoutofrangeexception',['IndexOutOfRangeException',['../class_system_1_1_index_out_of_range_exception.html',1,'System']]],
  ['inestedcontainer',['INestedContainer',['../interface_system_1_1_component_model_1_1_i_nested_container.html',1,'System::ComponentModel']]],
  ['inestedsite',['INestedSite',['../interface_system_1_1_component_model_1_1_i_nested_site.html',1,'System::ComponentModel']]],
  ['inheritanceattribute',['InheritanceAttribute',['../class_system_1_1_component_model_1_1_inheritance_attribute.html',1,'System::ComponentModel']]],
  ['initializationeventattribute',['InitializationEventAttribute',['../class_system_1_1_component_model_1_1_initialization_event_attribute.html',1,'System::ComponentModel']]],
  ['inormalizeforisolatedstorage',['INormalizeForIsolatedStorage',['../interface_system_1_1_i_o_1_1_isolated_storage_1_1_i_normalize_for_isolated_storage.html',1,'System::IO::IsolatedStorage']]],
  ['inotifycollectionchanged',['INotifyCollectionChanged',['../interface_system_1_1_collections_1_1_specialized_1_1_i_notify_collection_changed.html',1,'System::Collections::Specialized']]],
  ['inotifycompletion',['INotifyCompletion',['../interface_system_1_1_runtime_1_1_compiler_services_1_1_i_notify_completion.html',1,'System::Runtime::CompilerServices']]],
  ['inotifydataerrorinfo',['INotifyDataErrorInfo',['../interface_system_1_1_component_model_1_1_i_notify_data_error_info.html',1,'System::ComponentModel']]],
  ['inotifypropertychanged',['INotifyPropertyChanged',['../interface_system_1_1_component_model_1_1_i_notify_property_changed.html',1,'System::ComponentModel']]],
  ['inotifypropertychanging',['INotifyPropertyChanging',['../interface_system_1_1_component_model_1_1_i_notify_property_changing.html',1,'System::ComponentModel']]],
  ['installertypeattribute',['InstallerTypeAttribute',['../class_system_1_1_component_model_1_1_installer_type_attribute.html',1,'System::ComponentModel']]],
  ['instancecreationeditor',['InstanceCreationEditor',['../class_system_1_1_component_model_1_1_instance_creation_editor.html',1,'System::ComponentModel']]],
  ['instancedata',['InstanceData',['../class_system_1_1_diagnostics_1_1_instance_data.html',1,'System::Diagnostics']]],
  ['instancedatacollection',['InstanceDataCollection',['../class_system_1_1_diagnostics_1_1_instance_data_collection.html',1,'System::Diagnostics']]],
  ['instancedatacollectioncollection',['InstanceDataCollectionCollection',['../class_system_1_1_diagnostics_1_1_instance_data_collection_collection.html',1,'System::Diagnostics']]],
  ['instancedescriptor',['InstanceDescriptor',['../class_system_1_1_component_model_1_1_design_1_1_serialization_1_1_instance_descriptor.html',1,'System::ComponentModel::Design::Serialization']]],
  ['instancenotfoundexception',['InstanceNotFoundException',['../class_system_1_1_management_1_1_instrumentation_1_1_instance_not_found_exception.html',1,'System::Management::Instrumentation']]],
  ['instrumentationbaseexception',['InstrumentationBaseException',['../class_system_1_1_management_1_1_instrumentation_1_1_instrumentation_base_exception.html',1,'System::Management::Instrumentation']]],
  ['instrumentationexception',['InstrumentationException',['../class_system_1_1_management_1_1_instrumentation_1_1_instrumentation_exception.html',1,'System::Management::Instrumentation']]],
  ['insufficientexecutionstackexception',['InsufficientExecutionStackException',['../class_system_1_1_insufficient_execution_stack_exception.html',1,'System']]],
  ['insufficientmemoryexception',['InsufficientMemoryException',['../class_system_1_1_insufficient_memory_exception.html',1,'System']]],
  ['int16',['Int16',['../struct_system_1_1_int16.html',1,'System']]],
  ['int16converter',['Int16Converter',['../class_system_1_1_component_model_1_1_int16_converter.html',1,'System::ComponentModel']]],
  ['int32',['Int32',['../struct_system_1_1_int32.html',1,'System']]],
  ['int32converter',['Int32Converter',['../class_system_1_1_component_model_1_1_int32_converter.html',1,'System::ComponentModel']]],
  ['int64',['Int64',['../struct_system_1_1_int64.html',1,'System']]],
  ['int64converter',['Int64Converter',['../class_system_1_1_component_model_1_1_int64_converter.html',1,'System::ComponentModel']]],
  ['interfaceimplementedinversionattribute',['InterfaceImplementedInVersionAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_interface_implemented_in_version_attribute.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['interfacemapping',['InterfaceMapping',['../struct_system_1_1_reflection_1_1_interface_mapping.html',1,'System::Reflection']]],
  ['interfacetypeattribute',['InterfaceTypeAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_interface_type_attribute.html',1,'System::Runtime::InteropServices']]],
  ['interlocked',['Interlocked',['../class_system_1_1_threading_1_1_interlocked.html',1,'System::Threading']]],
  ['internalactivationcontexthelper',['InternalActivationContextHelper',['../class_system_1_1_deployment_1_1_internal_1_1_internal_activation_context_helper.html',1,'System::Deployment::Internal']]],
  ['internalapplicationidentityhelper',['InternalApplicationIdentityHelper',['../class_system_1_1_deployment_1_1_internal_1_1_internal_application_identity_helper.html',1,'System::Deployment::Internal']]],
  ['internalbufferoverflowexception',['InternalBufferOverflowException',['../class_system_1_1_i_o_1_1_internal_buffer_overflow_exception.html',1,'System::IO']]],
  ['internalmessagewrapper',['InternalMessageWrapper',['../class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_internal_message_wrapper.html',1,'System::Runtime::Remoting::Messaging']]],
  ['internalremotingservices',['InternalRemotingServices',['../class_system_1_1_runtime_1_1_remoting_1_1_internal_remoting_services.html',1,'System::Runtime::Remoting']]],
  ['internalrm',['InternalRM',['../class_system_1_1_runtime_1_1_serialization_1_1_formatters_1_1_internal_r_m.html',1,'System::Runtime::Serialization::Formatters']]],
  ['internalst',['InternalST',['../class_system_1_1_runtime_1_1_serialization_1_1_formatters_1_1_internal_s_t.html',1,'System::Runtime::Serialization::Formatters']]],
  ['internalsvisibletoattribute',['InternalsVisibleToAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_internals_visible_to_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['intptr',['IntPtr',['../struct_system_1_1_int_ptr.html',1,'System']]],
  ['introspectionextensions',['IntrospectionExtensions',['../class_system_1_1_reflection_1_1_introspection_extensions.html',1,'System::Reflection']]],
  ['invalidasynchronousstateexception',['InvalidAsynchronousStateException',['../class_system_1_1_component_model_1_1_invalid_asynchronous_state_exception.html',1,'System::ComponentModel']]],
  ['invalidcastexception',['InvalidCastException',['../class_system_1_1_invalid_cast_exception.html',1,'System']]],
  ['invalidcomobjectexception',['InvalidComObjectException',['../class_system_1_1_runtime_1_1_interop_services_1_1_invalid_com_object_exception.html',1,'System::Runtime::InteropServices']]],
  ['invalidcredentialexception',['InvalidCredentialException',['../class_system_1_1_security_1_1_authentication_1_1_invalid_credential_exception.html',1,'System::Security::Authentication']]],
  ['invaliddataexception',['InvalidDataException',['../class_system_1_1_i_o_1_1_invalid_data_exception.html',1,'System::IO']]],
  ['invalidenumargumentexception',['InvalidEnumArgumentException',['../class_system_1_1_component_model_1_1_invalid_enum_argument_exception.html',1,'System::ComponentModel']]],
  ['invalidfiltercriteriaexception',['InvalidFilterCriteriaException',['../class_system_1_1_reflection_1_1_invalid_filter_criteria_exception.html',1,'System::Reflection']]],
  ['invalidolevarianttypeexception',['InvalidOleVariantTypeException',['../class_system_1_1_runtime_1_1_interop_services_1_1_invalid_ole_variant_type_exception.html',1,'System::Runtime::InteropServices']]],
  ['invalidoperationexception',['InvalidOperationException',['../class_system_1_1_invalid_operation_exception.html',1,'System']]],
  ['invalidprogramexception',['InvalidProgramException',['../class_system_1_1_invalid_program_exception.html',1,'System']]],
  ['invalidtimezoneexception',['InvalidTimeZoneException',['../class_system_1_1_invalid_time_zone_exception.html',1,'System']]],
  ['invocationexpression',['InvocationExpression',['../class_system_1_1_linq_1_1_expressions_1_1_invocation_expression.html',1,'System::Linq::Expressions']]],
  ['invokebinder',['InvokeBinder',['../class_system_1_1_dynamic_1_1_invoke_binder.html',1,'System::Dynamic']]],
  ['invokememberbinder',['InvokeMemberBinder',['../class_system_1_1_dynamic_1_1_invoke_member_binder.html',1,'System::Dynamic']]],
  ['iobjecthandle',['IObjectHandle',['../interface_system_1_1_runtime_1_1_remoting_1_1_i_object_handle.html',1,'System::Runtime::Remoting']]],
  ['iobjectreference',['IObjectReference',['../interface_system_1_1_runtime_1_1_serialization_1_1_i_object_reference.html',1,'System::Runtime::Serialization']]],
  ['iobservable',['IObservable',['../interface_system_1_1_i_observable.html',1,'System']]],
  ['iobserver',['IObserver',['../interface_system_1_1_i_observer.html',1,'System']]],
  ['iodescriptionattribute',['IODescriptionAttribute',['../class_system_1_1_i_o_1_1_i_o_description_attribute.html',1,'System::IO']]],
  ['ioexception',['IOException',['../class_system_1_1_i_o_1_1_i_o_exception.html',1,'System::IO']]],
  ['iordereddictionary',['IOrderedDictionary',['../interface_system_1_1_collections_1_1_specialized_1_1_i_ordered_dictionary.html',1,'System::Collections::Specialized']]],
  ['iorderedenumerable',['IOrderedEnumerable',['../interface_system_1_1_linq_1_1_i_ordered_enumerable.html',1,'System::Linq']]],
  ['iorderedenumerable_3c_20tinputoutput_20_3e',['IOrderedEnumerable&lt; TInputOutput &gt;',['../interface_system_1_1_linq_1_1_i_ordered_enumerable.html',1,'System::Linq']]],
  ['iorderedenumerable_3c_20tsource_20_3e',['IOrderedEnumerable&lt; TSource &gt;',['../interface_system_1_1_linq_1_1_i_ordered_enumerable.html',1,'System::Linq']]],
  ['iorderedqueryable',['IOrderedQueryable',['../interface_system_1_1_linq_1_1_i_ordered_queryable.html',1,'System.Linq.IOrderedQueryable'],['../interface_system_1_1_linq_1_1_i_ordered_queryable.html',1,'System.Linq.IOrderedQueryable&lt; out out T &gt;']]],
  ['iorderedqueryable_3c_20t_20_3e',['IOrderedQueryable&lt; T &gt;',['../interface_system_1_1_linq_1_1_i_ordered_queryable.html',1,'System::Linq']]],
  ['ipaddress',['IPAddress',['../class_system_1_1_net_1_1_i_p_address.html',1,'System::Net']]],
  ['ipaddresscollection',['IPAddressCollection',['../class_system_1_1_net_1_1_network_information_1_1_i_p_address_collection.html',1,'System::Net::NetworkInformation']]],
  ['ipaddressinformation',['IPAddressInformation',['../class_system_1_1_net_1_1_network_information_1_1_i_p_address_information.html',1,'System::Net::NetworkInformation']]],
  ['ipaddressinformationcollection',['IPAddressInformationCollection',['../class_system_1_1_net_1_1_network_information_1_1_i_p_address_information_collection.html',1,'System::Net::NetworkInformation']]],
  ['ipendpoint',['IPEndPoint',['../class_system_1_1_net_1_1_i_p_end_point.html',1,'System::Net']]],
  ['ipermission',['IPermission',['../interface_system_1_1_security_1_1_i_permission.html',1,'System::Security']]],
  ['ipersistcomponentsettings',['IPersistComponentSettings',['../interface_system_1_1_configuration_1_1_i_persist_component_settings.html',1,'System::Configuration']]],
  ['ipersistfile',['IPersistFile',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_persist_file.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['ipglobalproperties',['IPGlobalProperties',['../class_system_1_1_net_1_1_network_information_1_1_i_p_global_properties.html',1,'System::Net::NetworkInformation']]],
  ['ipglobalstatistics',['IPGlobalStatistics',['../class_system_1_1_net_1_1_network_information_1_1_i_p_global_statistics.html',1,'System::Net::NetworkInformation']]],
  ['iphostentry',['IPHostEntry',['../class_system_1_1_net_1_1_i_p_host_entry.html',1,'System::Net']]],
  ['ipinterfaceproperties',['IPInterfaceProperties',['../class_system_1_1_net_1_1_network_information_1_1_i_p_interface_properties.html',1,'System::Net::NetworkInformation']]],
  ['ipinterfacestatistics',['IPInterfaceStatistics',['../class_system_1_1_net_1_1_network_information_1_1_i_p_interface_statistics.html',1,'System::Net::NetworkInformation']]],
  ['ippacketinformation',['IPPacketInformation',['../struct_system_1_1_net_1_1_sockets_1_1_i_p_packet_information.html',1,'System::Net::Sockets']]],
  ['iprincipal',['IPrincipal',['../interface_system_1_1_security_1_1_principal_1_1_i_principal.html',1,'System::Security::Principal']]],
  ['iproducerconsumercollection',['IProducerConsumerCollection',['../interface_system_1_1_collections_1_1_concurrent_1_1_i_producer_consumer_collection.html',1,'System::Collections::Concurrent']]],
  ['iprogress',['IProgress',['../interface_system_1_1_i_progress.html',1,'System']]],
  ['iprogress_3c_20t_20_3e',['IProgress&lt; T &gt;',['../interface_system_1_1_i_progress.html',1,'System']]],
  ['ipv4interfaceproperties',['IPv4InterfaceProperties',['../class_system_1_1_net_1_1_network_information_1_1_i_pv4_interface_properties.html',1,'System::Net::NetworkInformation']]],
  ['ipv4interfacestatistics',['IPv4InterfaceStatistics',['../class_system_1_1_net_1_1_network_information_1_1_i_pv4_interface_statistics.html',1,'System::Net::NetworkInformation']]],
  ['ipv6element',['Ipv6Element',['../class_system_1_1_net_1_1_configuration_1_1_ipv6_element.html',1,'System::Net::Configuration']]],
  ['ipv6interfaceproperties',['IPv6InterfaceProperties',['../class_system_1_1_net_1_1_network_information_1_1_i_pv6_interface_properties.html',1,'System::Net::NetworkInformation']]],
  ['ipv6multicastoption',['IPv6MulticastOption',['../class_system_1_1_net_1_1_sockets_1_1_i_pv6_multicast_option.html',1,'System::Net::Sockets']]],
  ['iqueryable',['IQueryable',['../interface_system_1_1_linq_1_1_i_queryable.html',1,'System.Linq.IQueryable'],['../interface_system_1_1_linq_1_1_i_queryable.html',1,'System.Linq.IQueryable&lt; out out T &gt;']]],
  ['iqueryable_3c_20t_20_3e',['IQueryable&lt; T &gt;',['../interface_system_1_1_linq_1_1_i_queryable.html',1,'System::Linq']]],
  ['iqueryprovider',['IQueryProvider',['../interface_system_1_1_linq_1_1_i_query_provider.html',1,'System::Linq']]],
  ['iraiseitemchangedevents',['IRaiseItemChangedEvents',['../interface_system_1_1_component_model_1_1_i_raise_item_changed_events.html',1,'System::ComponentModel']]],
  ['ireadonlycollection',['IReadOnlyCollection',['../interface_system_1_1_collections_1_1_generic_1_1_i_read_only_collection.html',1,'System::Collections::Generic']]],
  ['ireadonlycollection_3c_20t_20_3e',['IReadOnlyCollection&lt; T &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_read_only_collection.html',1,'System::Collections::Generic']]],
  ['ireadonlycollection_3c_20tkey_20_3e',['IReadOnlyCollection&lt; TKey &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_read_only_collection.html',1,'System::Collections::Generic']]],
  ['ireadonlycollection_3c_20tvalue_20_3e',['IReadOnlyCollection&lt; TValue &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_read_only_collection.html',1,'System::Collections::Generic']]],
  ['ireadonlydictionary',['IReadOnlyDictionary',['../interface_system_1_1_collections_1_1_generic_1_1_i_read_only_dictionary.html',1,'System::Collections::Generic']]],
  ['ireadonlylist',['IReadOnlyList',['../interface_system_1_1_collections_1_1_generic_1_1_i_read_only_list.html',1,'System::Collections::Generic']]],
  ['ireadonlylist_3c_20t_20_3e',['IReadOnlyList&lt; T &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_read_only_list.html',1,'System::Collections::Generic']]],
  ['ireferenceservice',['IReferenceService',['../interface_system_1_1_component_model_1_1_design_1_1_i_reference_service.html',1,'System::ComponentModel::Design']]],
  ['ireflect',['IReflect',['../interface_system_1_1_reflection_1_1_i_reflect.html',1,'System::Reflection']]],
  ['ireflectabletype',['IReflectableType',['../interface_system_1_1_reflection_1_1_i_reflectable_type.html',1,'System::Reflection']]],
  ['iregistrationservices',['IRegistrationServices',['../interface_system_1_1_runtime_1_1_interop_services_1_1_i_registration_services.html',1,'System::Runtime::InteropServices']]],
  ['iremotingformatter',['IRemotingFormatter',['../interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_remoting_formatter.html',1,'System::Runtime::Remoting::Messaging']]],
  ['iremotingtypeinfo',['IRemotingTypeInfo',['../interface_system_1_1_runtime_1_1_remoting_1_1_i_remoting_type_info.html',1,'System::Runtime::Remoting']]],
  ['iresourcereader',['IResourceReader',['../interface_system_1_1_resources_1_1_i_resource_reader.html',1,'System::Resources']]],
  ['iresourceservice',['IResourceService',['../interface_system_1_1_component_model_1_1_design_1_1_i_resource_service.html',1,'System::ComponentModel::Design']]],
  ['iresourcewriter',['IResourceWriter',['../interface_system_1_1_resources_1_1_i_resource_writer.html',1,'System::Resources']]],
  ['irevertiblechangetracking',['IRevertibleChangeTracking',['../interface_system_1_1_component_model_1_1_i_revertible_change_tracking.html',1,'System::ComponentModel']]],
  ['iriparsingelement',['IriParsingElement',['../class_system_1_1_configuration_1_1_iri_parsing_element.html',1,'System::Configuration']]],
  ['irootdesigner',['IRootDesigner',['../interface_system_1_1_component_model_1_1_design_1_1_i_root_designer.html',1,'System::ComponentModel::Design']]],
  ['irunningobjecttable',['IRunningObjectTable',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_running_object_table.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['iruntimevariables',['IRuntimeVariables',['../interface_system_1_1_runtime_1_1_compiler_services_1_1_i_runtime_variables.html',1,'System::Runtime::CompilerServices']]],
  ['isafeserializationdata',['ISafeSerializationData',['../interface_system_1_1_runtime_1_1_serialization_1_1_i_safe_serialization_data.html',1,'System::Runtime::Serialization']]],
  ['isboxed',['IsBoxed',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_boxed.html',1,'System::Runtime::CompilerServices']]],
  ['isbyreflikeattribute',['IsByRefLikeAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_by_ref_like_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['isbyvalue',['IsByValue',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_by_value.html',1,'System::Runtime::CompilerServices']]],
  ['isconst',['IsConst',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_const.html',1,'System::Runtime::CompilerServices']]],
  ['iscopyconstructed',['IsCopyConstructed',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_copy_constructed.html',1,'System::Runtime::CompilerServices']]],
  ['isecurablechannel',['ISecurableChannel',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_securable_channel.html',1,'System::Runtime::Remoting::Channels']]],
  ['isecurityencodable',['ISecurityEncodable',['../interface_system_1_1_security_1_1_i_security_encodable.html',1,'System::Security']]],
  ['isecuritypolicyencodable',['ISecurityPolicyEncodable',['../interface_system_1_1_security_1_1_i_security_policy_encodable.html',1,'System::Security']]],
  ['iselectionservice',['ISelectionService',['../interface_system_1_1_component_model_1_1_design_1_1_i_selection_service.html',1,'System::ComponentModel::Design']]],
  ['iserializable',['ISerializable',['../interface_system_1_1_runtime_1_1_serialization_1_1_i_serializable.html',1,'System::Runtime::Serialization']]],
  ['iserializationsurrogate',['ISerializationSurrogate',['../interface_system_1_1_runtime_1_1_serialization_1_1_i_serialization_surrogate.html',1,'System::Runtime::Serialization']]],
  ['iserverchannelsink',['IServerChannelSink',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_server_channel_sink.html',1,'System::Runtime::Remoting::Channels']]],
  ['iserverchannelsinkprovider',['IServerChannelSinkProvider',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_server_channel_sink_provider.html',1,'System::Runtime::Remoting::Channels']]],
  ['iserverchannelsinkstack',['IServerChannelSinkStack',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_server_channel_sink_stack.html',1,'System::Runtime::Remoting::Channels']]],
  ['iserverformattersinkprovider',['IServerFormatterSinkProvider',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_server_formatter_sink_provider.html',1,'System::Runtime::Remoting::Channels']]],
  ['iserverresponsechannelsinkstack',['IServerResponseChannelSinkStack',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_server_response_channel_sink_stack.html',1,'System::Runtime::Remoting::Channels']]],
  ['iservicecontainer',['IServiceContainer',['../interface_system_1_1_component_model_1_1_design_1_1_i_service_container.html',1,'System::ComponentModel::Design']]],
  ['iserviceprovider',['IServiceProvider',['../interface_system_1_1_i_service_provider.html',1,'System']]],
  ['iset',['ISet',['../interface_system_1_1_collections_1_1_generic_1_1_i_set.html',1,'System::Collections::Generic']]],
  ['isettingsproviderservice',['ISettingsProviderService',['../interface_system_1_1_configuration_1_1_i_settings_provider_service.html',1,'System::Configuration']]],
  ['isexplicitlydereferenced',['IsExplicitlyDereferenced',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_explicitly_dereferenced.html',1,'System::Runtime::CompilerServices']]],
  ['isimplicitlydereferenced',['IsImplicitlyDereferenced',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_implicitly_dereferenced.html',1,'System::Runtime::CompilerServices']]],
  ['isite',['ISite',['../interface_system_1_1_component_model_1_1_i_site.html',1,'System::ComponentModel']]],
  ['isjitintrinsic',['IsJitIntrinsic',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_jit_intrinsic.html',1,'System::Runtime::CompilerServices']]],
  ['islong',['IsLong',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_long.html',1,'System::Runtime::CompilerServices']]],
  ['isoapmessage',['ISoapMessage',['../interface_system_1_1_runtime_1_1_serialization_1_1_formatters_1_1_i_soap_message.html',1,'System::Runtime::Serialization::Formatters']]],
  ['isoapxsd',['ISoapXsd',['../interface_system_1_1_runtime_1_1_remoting_1_1_metadata_1_1_w3c_xsd2001_1_1_i_soap_xsd.html',1,'System::Runtime::Remoting::Metadata::W3cXsd2001']]],
  ['isolatedstorage',['IsolatedStorage',['../class_system_1_1_i_o_1_1_isolated_storage_1_1_isolated_storage.html',1,'System::IO::IsolatedStorage']]],
  ['isolatedstorageexception',['IsolatedStorageException',['../class_system_1_1_i_o_1_1_isolated_storage_1_1_isolated_storage_exception.html',1,'System::IO::IsolatedStorage']]],
  ['isolatedstoragefile',['IsolatedStorageFile',['../class_system_1_1_i_o_1_1_isolated_storage_1_1_isolated_storage_file.html',1,'System::IO::IsolatedStorage']]],
  ['isolatedstoragefilepermission',['IsolatedStorageFilePermission',['../class_system_1_1_security_1_1_permissions_1_1_isolated_storage_file_permission.html',1,'System::Security::Permissions']]],
  ['isolatedstoragefilepermissionattribute',['IsolatedStorageFilePermissionAttribute',['../class_system_1_1_security_1_1_permissions_1_1_isolated_storage_file_permission_attribute.html',1,'System::Security::Permissions']]],
  ['isolatedstoragefilestream',['IsolatedStorageFileStream',['../class_system_1_1_i_o_1_1_isolated_storage_1_1_isolated_storage_file_stream.html',1,'System::IO::IsolatedStorage']]],
  ['isolatedstoragepermission',['IsolatedStoragePermission',['../class_system_1_1_security_1_1_permissions_1_1_isolated_storage_permission.html',1,'System::Security::Permissions']]],
  ['isolatedstoragepermissionattribute',['IsolatedStoragePermissionAttribute',['../class_system_1_1_security_1_1_permissions_1_1_isolated_storage_permission_attribute.html',1,'System::Security::Permissions']]],
  ['isolatedstoragesecuritystate',['IsolatedStorageSecurityState',['../class_system_1_1_i_o_1_1_isolated_storage_1_1_isolated_storage_security_state.html',1,'System::IO::IsolatedStorage']]],
  ['ispinned',['IsPinned',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_pinned.html',1,'System::Runtime::CompilerServices']]],
  ['isponsor',['ISponsor',['../interface_system_1_1_runtime_1_1_remoting_1_1_lifetime_1_1_i_sponsor.html',1,'System::Runtime::Remoting::Lifetime']]],
  ['isreadonlyattribute',['IsReadOnlyAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_read_only_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['issignunspecifiedbyte',['IsSignUnspecifiedByte',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_sign_unspecified_byte.html',1,'System::Runtime::CompilerServices']]],
  ['istackwalk',['IStackWalk',['../interface_system_1_1_security_1_1_i_stack_walk.html',1,'System::Security']]],
  ['istream',['IStream',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_stream.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['istrongbox',['IStrongBox',['../interface_system_1_1_runtime_1_1_compiler_services_1_1_i_strong_box.html',1,'System::Runtime::CompilerServices']]],
  ['istructuralcomparable',['IStructuralComparable',['../interface_system_1_1_collections_1_1_i_structural_comparable.html',1,'System::Collections']]],
  ['istructuralequatable',['IStructuralEquatable',['../interface_system_1_1_collections_1_1_i_structural_equatable.html',1,'System::Collections']]],
  ['isudtreturn',['IsUdtReturn',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_udt_return.html',1,'System::Runtime::CompilerServices']]],
  ['isupportinitialize',['ISupportInitialize',['../interface_system_1_1_component_model_1_1_i_support_initialize.html',1,'System::ComponentModel']]],
  ['isupportinitializenotification',['ISupportInitializeNotification',['../interface_system_1_1_component_model_1_1_i_support_initialize_notification.html',1,'System::ComponentModel']]],
  ['isurrogateselector',['ISurrogateSelector',['../interface_system_1_1_runtime_1_1_serialization_1_1_i_surrogate_selector.html',1,'System::Runtime::Serialization']]],
  ['isvolatile',['IsVolatile',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_volatile.html',1,'System::Runtime::CompilerServices']]],
  ['isymbolbinder',['ISymbolBinder',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_binder.html',1,'System::Diagnostics::SymbolStore']]],
  ['isymbolbinder1',['ISymbolBinder1',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_binder1.html',1,'System::Diagnostics::SymbolStore']]],
  ['isymboldocument',['ISymbolDocument',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_document.html',1,'System::Diagnostics::SymbolStore']]],
  ['isymboldocumentwriter',['ISymbolDocumentWriter',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_document_writer.html',1,'System::Diagnostics::SymbolStore']]],
  ['isymbolmethod',['ISymbolMethod',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_method.html',1,'System::Diagnostics::SymbolStore']]],
  ['isymbolnamespace',['ISymbolNamespace',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_namespace.html',1,'System::Diagnostics::SymbolStore']]],
  ['isymbolreader',['ISymbolReader',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_reader.html',1,'System::Diagnostics::SymbolStore']]],
  ['isymbolscope',['ISymbolScope',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_scope.html',1,'System::Diagnostics::SymbolStore']]],
  ['isymbolvariable',['ISymbolVariable',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_variable.html',1,'System::Diagnostics::SymbolStore']]],
  ['isymbolwriter',['ISymbolWriter',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_writer.html',1,'System::Diagnostics::SymbolStore']]],
  ['isynchronizeinvoke',['ISynchronizeInvoke',['../interface_system_1_1_component_model_1_1_i_synchronize_invoke.html',1,'System::ComponentModel']]],
  ['iteratorstatemachineattribute',['IteratorStateMachineAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_iterator_state_machine_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['itrackinghandler',['ITrackingHandler',['../interface_system_1_1_runtime_1_1_remoting_1_1_services_1_1_i_tracking_handler.html',1,'System::Runtime::Remoting::Services']]],
  ['itransportheaders',['ITransportHeaders',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_transport_headers.html',1,'System::Runtime::Remoting::Channels']]],
  ['itreedesigner',['ITreeDesigner',['../interface_system_1_1_component_model_1_1_design_1_1_i_tree_designer.html',1,'System::ComponentModel::Design']]],
  ['ituple',['ITuple',['../interface_system_1_1_runtime_1_1_compiler_services_1_1_i_tuple.html',1,'System::Runtime::CompilerServices']]],
  ['itypecomp',['ITypeComp',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_type_comp.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['itypedescriptorcontext',['ITypeDescriptorContext',['../interface_system_1_1_component_model_1_1_i_type_descriptor_context.html',1,'System::ComponentModel']]],
  ['itypedescriptorfilterservice',['ITypeDescriptorFilterService',['../interface_system_1_1_component_model_1_1_design_1_1_i_type_descriptor_filter_service.html',1,'System::ComponentModel::Design']]],
  ['itypediscoveryservice',['ITypeDiscoveryService',['../interface_system_1_1_component_model_1_1_design_1_1_i_type_discovery_service.html',1,'System::ComponentModel::Design']]],
  ['itypedlist',['ITypedList',['../interface_system_1_1_component_model_1_1_i_typed_list.html',1,'System::ComponentModel']]],
  ['itypeinfo',['ITypeInfo',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_type_info.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['itypeinfo2',['ITypeInfo2',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_type_info2.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['itypelib',['ITypeLib',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_type_lib.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['itypelib2',['ITypeLib2',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_type_lib2.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['itypelibconverter',['ITypeLibConverter',['../interface_system_1_1_runtime_1_1_interop_services_1_1_i_type_lib_converter.html',1,'System::Runtime::InteropServices']]],
  ['itypelibexporternameprovider',['ITypeLibExporterNameProvider',['../interface_system_1_1_runtime_1_1_interop_services_1_1_i_type_lib_exporter_name_provider.html',1,'System::Runtime::InteropServices']]],
  ['itypelibexporternotifysink',['ITypeLibExporterNotifySink',['../interface_system_1_1_runtime_1_1_interop_services_1_1_i_type_lib_exporter_notify_sink.html',1,'System::Runtime::InteropServices']]],
  ['itypelibimporternotifysink',['ITypeLibImporterNotifySink',['../interface_system_1_1_runtime_1_1_interop_services_1_1_i_type_lib_importer_notify_sink.html',1,'System::Runtime::InteropServices']]],
  ['ityperesolutionservice',['ITypeResolutionService',['../interface_system_1_1_component_model_1_1_design_1_1_i_type_resolution_service.html',1,'System::ComponentModel::Design']]],
  ['iunknownconstantattribute',['IUnknownConstantAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_i_unknown_constant_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['iunrestrictedpermission',['IUnrestrictedPermission',['../interface_system_1_1_security_1_1_permissions_1_1_i_unrestricted_permission.html',1,'System::Security::Permissions']]],
  ['iwebproxy',['IWebProxy',['../interface_system_1_1_net_1_1_i_web_proxy.html',1,'System::Net']]],
  ['iwebproxyscript',['IWebProxyScript',['../interface_system_1_1_net_1_1_i_web_proxy_script.html',1,'System::Net']]],
  ['iwebrequestcreate',['IWebRequestCreate',['../interface_system_1_1_net_1_1_i_web_request_create.html',1,'System::Net']]],
  ['ixmllineinfo',['IXmlLineInfo',['../interface_system_1_1_xml_1_1_i_xml_line_info.html',1,'System::Xml']]],
  ['ixmlnamespaceresolver',['IXmlNamespaceResolver',['../interface_system_1_1_xml_1_1_i_xml_namespace_resolver.html',1,'System::Xml']]],
  ['ixmlschemainfo',['IXmlSchemaInfo',['../interface_system_1_1_xml_1_1_schema_1_1_i_xml_schema_info.html',1,'System::Xml::Schema']]],
  ['ixmlserializable',['IXmlSerializable',['../interface_system_1_1_xml_1_1_serialization_1_1_i_xml_serializable.html',1,'System::Xml::Serialization']]],
  ['ixmltextparser',['IXmlTextParser',['../interface_system_1_1_xml_1_1_serialization_1_1_i_xml_text_parser.html',1,'System::Xml::Serialization']]],
  ['ixpathnavigable',['IXPathNavigable',['../interface_system_1_1_xml_1_1_x_path_1_1_i_x_path_navigable.html',1,'System::Xml::XPath']]],
  ['ixsltcontextfunction',['IXsltContextFunction',['../interface_system_1_1_xml_1_1_xsl_1_1_i_xslt_context_function.html',1,'System::Xml::Xsl']]],
  ['ixsltcontextvariable',['IXsltContextVariable',['../interface_system_1_1_xml_1_1_xsl_1_1_i_xslt_context_variable.html',1,'System::Xml::Xsl']]]
];
