var searchData=
[
  ['iactcontext',['IActContext',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_act_context.html',1,'System::Deployment::Internal::Isolation']]],
  ['iactivationfactory',['IActivationFactory',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_activation_factory.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['iactivator',['IActivator',['../interface_system_1_1_runtime_1_1_remoting_1_1_activation_1_1_i_activator.html',1,'System::Runtime::Remoting::Activation']]],
  ['iappdomainsetup',['IAppDomainSetup',['../interface_system_1_1_i_app_domain_setup.html',1,'System']]],
  ['iappidauthority',['IAppIdAuthority',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_app_id_authority.html',1,'System::Deployment::Internal::Isolation']]],
  ['iapplicationcontext',['IApplicationContext',['../interface_microsoft_1_1_win32_1_1_i_application_context.html',1,'Microsoft::Win32']]],
  ['iapplicationtrustmanager',['IApplicationTrustManager',['../interface_system_1_1_security_1_1_policy_1_1_i_application_trust_manager.html',1,'System::Security::Policy']]],
  ['iarraysorthelper',['IArraySortHelper',['../interface_system_1_1_collections_1_1_generic_1_1_i_array_sort_helper.html',1,'System.Collections.Generic.IArraySortHelper&lt; TKey &gt;'],['../interface_system_1_1_collections_1_1_generic_1_1_i_array_sort_helper.html',1,'System.Collections.Generic.IArraySortHelper&lt; TKey, TValue &gt;']]],
  ['iarraysorthelper_3c_20t_20_3e',['IArraySortHelper&lt; T &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_array_sort_helper.html',1,'System::Collections::Generic']]],
  ['iarraysorthelper_3c_20tkey_2c_20tvalue_20_3e',['IArraySortHelper&lt; TKey, TValue &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_array_sort_helper.html',1,'System::Collections::Generic']]],
  ['iassemblyenum',['IAssemblyEnum',['../interface_microsoft_1_1_win32_1_1_i_assembly_enum.html',1,'Microsoft::Win32']]],
  ['iassemblyname',['IAssemblyName',['../interface_microsoft_1_1_win32_1_1_i_assembly_name.html',1,'Microsoft::Win32']]],
  ['iassemblyreferencedependentassemblyentry',['IAssemblyReferenceDependentAssemblyEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_assembly_reference_dependent_assembly_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['iassemblyreferenceentry',['IAssemblyReferenceEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_assembly_reference_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['iassemblyrequestentry',['IAssemblyRequestEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_assembly_request_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['iasynccausalitytracerstatics',['IAsyncCausalityTracerStatics',['../interface_windows_1_1_foundation_1_1_diagnostics_1_1_i_async_causality_tracer_statics.html',1,'Windows::Foundation::Diagnostics']]],
  ['iasynclocal',['IAsyncLocal',['../interface_system_1_1_threading_1_1_i_async_local.html',1,'System::Threading']]],
  ['iasyncresult',['IAsyncResult',['../interface_system_1_1_i_async_result.html',1,'System']]],
  ['iasyncstatemachine',['IAsyncStateMachine',['../interface_system_1_1_runtime_1_1_compiler_services_1_1_i_async_state_machine.html',1,'System::Runtime::CompilerServices']]],
  ['ibindableiterable',['IBindableIterable',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_bindable_iterable.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['ibindableiterator',['IBindableIterator',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_bindable_iterator.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['ibindablevector',['IBindableVector',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_bindable_vector.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['ibindablevectorview',['IBindableVectorView',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_bindable_vector_view.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['ibindctx',['IBindCtx',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_bind_ctx.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['ibuiltinpermission',['IBuiltInPermission',['../interface_system_1_1_security_1_1_permissions_1_1_i_built_in_permission.html',1,'System::Security::Permissions']]],
  ['icategorymembershipdataentry',['ICategoryMembershipDataEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_category_membership_data_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['icategorymembershipentry',['ICategoryMembershipEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_category_membership_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['icdf',['ICDF',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_c_d_f.html',1,'System::Deployment::Internal::Isolation']]],
  ['ichannel',['IChannel',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel.html',1,'System::Runtime::Remoting::Channels']]],
  ['ichanneldatastore',['IChannelDataStore',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_data_store.html',1,'System::Runtime::Remoting::Channels']]],
  ['ichannelinfo',['IChannelInfo',['../interface_system_1_1_runtime_1_1_remoting_1_1_i_channel_info.html',1,'System::Runtime::Remoting']]],
  ['ichannelreceiver',['IChannelReceiver',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_receiver.html',1,'System::Runtime::Remoting::Channels']]],
  ['ichannelreceiverhook',['IChannelReceiverHook',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_receiver_hook.html',1,'System::Runtime::Remoting::Channels']]],
  ['ichannelsender',['IChannelSender',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_sender.html',1,'System::Runtime::Remoting::Channels']]],
  ['ichannelsinkbase',['IChannelSinkBase',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_sink_base.html',1,'System::Runtime::Remoting::Channels']]],
  ['iclientchannelsink',['IClientChannelSink',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_channel_sink.html',1,'System::Runtime::Remoting::Channels']]],
  ['iclientchannelsinkprovider',['IClientChannelSinkProvider',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_channel_sink_provider.html',1,'System::Runtime::Remoting::Channels']]],
  ['iclientchannelsinkstack',['IClientChannelSinkStack',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_channel_sink_stack.html',1,'System::Runtime::Remoting::Channels']]],
  ['iclientformattersink',['IClientFormatterSink',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_formatter_sink.html',1,'System::Runtime::Remoting::Channels']]],
  ['iclientformattersinkprovider',['IClientFormatterSinkProvider',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_formatter_sink_provider.html',1,'System::Runtime::Remoting::Channels']]],
  ['iclientresponsechannelsinkstack',['IClientResponseChannelSinkStack',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_response_channel_sink_stack.html',1,'System::Runtime::Remoting::Channels']]],
  ['icloneable',['ICloneable',['../interface_system_1_1_i_cloneable.html',1,'System']]],
  ['iclosable',['IClosable',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_closable.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['iclosabletoidisposableadapter',['IClosableToIDisposableAdapter',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_closable_to_i_disposable_adapter.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['iclrstrongname',['IClrStrongName',['../interface_microsoft_1_1_runtime_1_1_hosting_1_1_i_clr_strong_name.html',1,'Microsoft::Runtime::Hosting']]],
  ['iclrstrongnameusingintptr',['IClrStrongNameUsingIntPtr',['../interface_microsoft_1_1_runtime_1_1_hosting_1_1_i_clr_strong_name_using_int_ptr.html',1,'Microsoft::Runtime::Hosting']]],
  ['iclrsurrogateentry',['ICLRSurrogateEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_c_l_r_surrogate_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['icms',['ICMS',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_c_m_s.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['icollection',['ICollection',['../interface_system_1_1_collections_1_1_i_collection.html',1,'System.Collections.ICollection'],['../interface_system_1_1_collections_1_1_generic_1_1_i_collection.html',1,'System.Collections.Generic.ICollection&lt; T &gt;']]],
  ['icollection_3c_20identityreference_20_3e',['ICollection&lt; IdentityReference &gt;',['../interface_system_1_1_collections_1_1_i_collection.html',1,'System::Collections']]],
  ['icollection_3c_20object_20_3e',['ICollection&lt; object &gt;',['../interface_system_1_1_collections_1_1_i_collection.html',1,'System::Collections']]],
  ['icollection_3c_20string_20_3e',['ICollection&lt; string &gt;',['../interface_system_1_1_collections_1_1_i_collection.html',1,'System::Collections']]],
  ['icollection_3c_20t_20_3e',['ICollection&lt; T &gt;',['../interface_system_1_1_collections_1_1_i_collection.html',1,'System::Collections']]],
  ['icollection_3c_20tkey_20_3e',['ICollection&lt; TKey &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_collection.html',1,'System.Collections.Generic.ICollection&lt; TKey &gt;'],['../interface_system_1_1_collections_1_1_i_collection.html',1,'System.Collections.ICollection&lt; TKey &gt;']]],
  ['icollection_3c_20tvalue_20_3e',['ICollection&lt; TValue &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_collection.html',1,'System.Collections.Generic.ICollection&lt; TValue &gt;'],['../interface_system_1_1_collections_1_1_i_collection.html',1,'System.Collections.ICollection&lt; TValue &gt;']]],
  ['icomparable',['IComparable',['../interface_system_1_1_i_comparable.html',1,'System.IComparable'],['../interface_system_1_1_i_comparable.html',1,'System.IComparable&lt; in in T &gt;']]],
  ['icomparable_3c_20bool_20_3e',['IComparable&lt; bool &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20byte_20_3e',['IComparable&lt; byte &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20char_20_3e',['IComparable&lt; char &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20datetime_20_3e',['IComparable&lt; DateTime &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20datetimeoffset_20_3e',['IComparable&lt; DateTimeOffset &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20decimal_20_3e',['IComparable&lt; decimal &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20double_20_3e',['IComparable&lt; double &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20float_20_3e',['IComparable&lt; float &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20guid_20_3e',['IComparable&lt; Guid &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20int_20_3e',['IComparable&lt; int &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20long_20_3e',['IComparable&lt; long &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20sbyte_20_3e',['IComparable&lt; sbyte &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20securityidentifier_20_3e',['IComparable&lt; SecurityIdentifier &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20short_20_3e',['IComparable&lt; short &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20string_20_3e',['IComparable&lt; string &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20timespan_20_3e',['IComparable&lt; TimeSpan &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20uint_20_3e',['IComparable&lt; uint &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20ulong_20_3e',['IComparable&lt; ulong &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20ushort_20_3e',['IComparable&lt; ushort &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20valuetuple_20_3e',['IComparable&lt; ValueTuple &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_20version_20_3e',['IComparable&lt; Version &gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_28t1_2c_20t2_29_3e',['IComparable&lt;(T1, T2)&gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_28t1_2c_20t2_2c_20t3_29_3e',['IComparable&lt;(T1, T2, T3)&gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_28t1_2c_20t2_2c_20t3_2c_20t4_29_3e',['IComparable&lt;(T1, T2, T3, T4)&gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_28t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_29_3e',['IComparable&lt;(T1, T2, T3, T4, T5)&gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_28t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_2c_20t6_29_3e',['IComparable&lt;(T1, T2, T3, T4, T5, T6)&gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparable_3c_28t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_2c_20t6_2c_20t7_29_3e',['IComparable&lt;(T1, T2, T3, T4, T5, T6, T7)&gt;',['../interface_system_1_1_i_comparable.html',1,'System']]],
  ['icomparer',['IComparer',['../interface_system_1_1_collections_1_1_i_comparer.html',1,'System.Collections.IComparer'],['../interface_system_1_1_collections_1_1_generic_1_1_i_comparer.html',1,'System.Collections.Generic.IComparer&lt; in in T &gt;']]],
  ['icomparer_3c_20string_20_3e',['IComparer&lt; string &gt;',['../interface_system_1_1_collections_1_1_i_comparer.html',1,'System::Collections']]],
  ['icomparer_3c_20t_20_3e',['IComparer&lt; T &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_comparer.html',1,'System.Collections.Generic.IComparer&lt; T &gt;'],['../interface_system_1_1_collections_1_1_i_comparer.html',1,'System.Collections.IComparer&lt; T &gt;']]],
  ['icomparer_3c_20timezoneinfo_20_3e',['IComparer&lt; TimeZoneInfo &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_comparer.html',1,'System::Collections::Generic']]],
  ['icomparer_3c_20tkey_20_3e',['IComparer&lt; TKey &gt;',['../interface_system_1_1_collections_1_1_i_comparer.html',1,'System::Collections']]],
  ['icompatibleframeworksmetadataentry',['ICompatibleFrameworksMetadataEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_compatible_frameworks_metadata_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['icomserverentry',['ICOMServerEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_c_o_m_server_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['iconnectionpoint',['IConnectionPoint',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_connection_point.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['iconnectionpointcontainer',['IConnectionPointContainer',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_connection_point_container.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['iconstantmembershipcondition',['IConstantMembershipCondition',['../interface_system_1_1_security_1_1_policy_1_1_i_constant_membership_condition.html',1,'System::Security::Policy']]],
  ['iconstructioncallmessage',['IConstructionCallMessage',['../interface_system_1_1_runtime_1_1_remoting_1_1_activation_1_1_i_construction_call_message.html',1,'System::Runtime::Remoting::Activation']]],
  ['iconstructionreturnmessage',['IConstructionReturnMessage',['../interface_system_1_1_runtime_1_1_remoting_1_1_activation_1_1_i_construction_return_message.html',1,'System::Runtime::Remoting::Activation']]],
  ['icontextattribute',['IContextAttribute',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_context_attribute.html',1,'System::Runtime::Remoting::Contexts']]],
  ['icontextproperty',['IContextProperty',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_context_property.html',1,'System::Runtime::Remoting::Contexts']]],
  ['icontextpropertyactivator',['IContextPropertyActivator',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_context_property_activator.html',1,'System::Runtime::Remoting::Contexts']]],
  ['icontributeclientcontextsink',['IContributeClientContextSink',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_contribute_client_context_sink.html',1,'System::Runtime::Remoting::Contexts']]],
  ['icontributedynamicsink',['IContributeDynamicSink',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_contribute_dynamic_sink.html',1,'System::Runtime::Remoting::Contexts']]],
  ['icontributeenvoysink',['IContributeEnvoySink',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_contribute_envoy_sink.html',1,'System::Runtime::Remoting::Contexts']]],
  ['icontributeobjectsink',['IContributeObjectSink',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_contribute_object_sink.html',1,'System::Runtime::Remoting::Contexts']]],
  ['icontributeservercontextsink',['IContributeServerContextSink',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_contribute_server_context_sink.html',1,'System::Runtime::Remoting::Contexts']]],
  ['iconvertible',['IConvertible',['../interface_system_1_1_i_convertible.html',1,'System']]],
  ['icriticalnotifycompletion',['ICriticalNotifyCompletion',['../interface_system_1_1_runtime_1_1_compiler_services_1_1_i_critical_notify_completion.html',1,'System::Runtime::CompilerServices']]],
  ['icryptotransform',['ICryptoTransform',['../interface_system_1_1_security_1_1_cryptography_1_1_i_crypto_transform.html',1,'System::Security::Cryptography']]],
  ['icspasymmetricalgorithm',['ICspAsymmetricAlgorithm',['../interface_system_1_1_security_1_1_cryptography_1_1_i_csp_asymmetric_algorithm.html',1,'System::Security::Cryptography']]],
  ['icustomadapter',['ICustomAdapter',['../interface_system_1_1_runtime_1_1_interop_services_1_1_i_custom_adapter.html',1,'System::Runtime::InteropServices']]],
  ['icustomattributeprovider',['ICustomAttributeProvider',['../interface_system_1_1_reflection_1_1_i_custom_attribute_provider.html',1,'System::Reflection']]],
  ['icustomdebuggernotification',['ICustomDebuggerNotification',['../interface_system_1_1_diagnostics_1_1_i_custom_debugger_notification.html',1,'System::Diagnostics']]],
  ['icustomfactory',['ICustomFactory',['../interface_system_1_1_runtime_1_1_interop_services_1_1_i_custom_factory.html',1,'System::Runtime::InteropServices']]],
  ['icustomformatter',['ICustomFormatter',['../interface_system_1_1_i_custom_formatter.html',1,'System']]],
  ['icustommarshaler',['ICustomMarshaler',['../interface_system_1_1_runtime_1_1_interop_services_1_1_i_custom_marshaler.html',1,'System::Runtime::InteropServices']]],
  ['icustomproperty',['ICustomProperty',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_custom_property.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['icustompropertyprovider',['ICustomPropertyProvider',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_custom_property_provider.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['icustompropertyproviderimpl',['ICustomPropertyProviderImpl',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_custom_property_provider_impl.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['icustompropertyproviderproxy',['ICustomPropertyProviderProxy',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_custom_property_provider_proxy.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['icustomqueryinterface',['ICustomQueryInterface',['../interface_system_1_1_runtime_1_1_interop_services_1_1_i_custom_query_interface.html',1,'System::Runtime::InteropServices']]],
  ['ideferreddisposable',['IDeferredDisposable',['../interface_system_1_1_threading_1_1_i_deferred_disposable.html',1,'System::Threading']]],
  ['idefinitionappid',['IDefinitionAppId',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_definition_app_id.html',1,'System::Deployment::Internal::Isolation']]],
  ['idefinitionidentity',['IDefinitionIdentity',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_definition_identity.html',1,'System::Deployment::Internal::Isolation']]],
  ['idelayevaluatedevidence',['IDelayEvaluatedEvidence',['../interface_system_1_1_security_1_1_policy_1_1_i_delay_evaluated_evidence.html',1,'System::Security::Policy']]],
  ['identity',['Identity',['../class_system_1_1_runtime_1_1_remoting_1_1_identity.html',1,'System::Runtime::Remoting']]],
  ['identity_5fattribute',['IDENTITY_ATTRIBUTE',['../struct_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_d_e_n_t_i_t_y___a_t_t_r_i_b_u_t_e.html',1,'System::Deployment::Internal::Isolation']]],
  ['identityholder',['IdentityHolder',['../class_system_1_1_runtime_1_1_remoting_1_1_identity_holder.html',1,'System::Runtime::Remoting']]],
  ['identitynotmappedexception',['IdentityNotMappedException',['../class_system_1_1_security_1_1_principal_1_1_identity_not_mapped_exception.html',1,'System::Security::Principal']]],
  ['identityreference',['IdentityReference',['../class_system_1_1_security_1_1_principal_1_1_identity_reference.html',1,'System::Security::Principal']]],
  ['identityreferencecollection',['IdentityReferenceCollection',['../class_system_1_1_security_1_1_principal_1_1_identity_reference_collection.html',1,'System::Security::Principal']]],
  ['identityreferenceenumerator',['IdentityReferenceEnumerator',['../class_system_1_1_security_1_1_principal_1_1_identity_reference_enumerator.html',1,'System::Security::Principal']]],
  ['idependentosmetadataentry',['IDependentOSMetadataEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_dependent_o_s_metadata_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['ideploymentmetadataentry',['IDeploymentMetadataEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_deployment_metadata_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['idescriptionmetadataentry',['IDescriptionMetadataEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_description_metadata_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['ideserializationcallback',['IDeserializationCallback',['../interface_system_1_1_runtime_1_1_serialization_1_1_i_deserialization_callback.html',1,'System::Runtime::Serialization']]],
  ['idictionary',['IDictionary',['../interface_system_1_1_collections_1_1_i_dictionary.html',1,'System.Collections.IDictionary'],['../interface_system_1_1_collections_1_1_generic_1_1_i_dictionary.html',1,'System.Collections.Generic.IDictionary&lt; TKey, TValue &gt;']]],
  ['idictionary_3c_20k_2c_20v_20_3e',['IDictionary&lt; K, V &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_dictionary.html',1,'System::Collections::Generic']]],
  ['idictionary_3c_20string_2c_20object_20_3e',['IDictionary&lt; string, object &gt;',['../interface_system_1_1_collections_1_1_i_dictionary.html',1,'System::Collections']]],
  ['idictionary_3c_20tkey_2c_20tvalue_20_3e',['IDictionary&lt; TKey, TValue &gt;',['../interface_system_1_1_collections_1_1_i_dictionary.html',1,'System::Collections']]],
  ['idictionaryenumerator',['IDictionaryEnumerator',['../interface_system_1_1_collections_1_1_i_dictionary_enumerator.html',1,'System::Collections']]],
  ['idispatchconstantattribute',['IDispatchConstantAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_i_dispatch_constant_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['idispatchimplattribute',['IDispatchImplAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_i_dispatch_impl_attribute.html',1,'System::Runtime::InteropServices']]],
  ['idisposable',['IDisposable',['../interface_system_1_1_i_disposable.html',1,'System']]],
  ['idisposabletoiclosableadapter',['IDisposableToIClosableAdapter',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_disposable_to_i_closable_adapter.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['idldesc',['IDLDESC',['../struct_system_1_1_runtime_1_1_interop_services_1_1_i_d_l_d_e_s_c.html',1,'System.Runtime.InteropServices.IDLDESC'],['../struct_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_d_l_d_e_s_c.html',1,'System.Runtime.InteropServices.ComTypes.IDLDESC']]],
  ['idnmapping',['IdnMapping',['../class_system_1_1_globalization_1_1_idn_mapping.html',1,'System::Globalization']]],
  ['idops',['IdOps',['../struct_system_1_1_runtime_1_1_remoting_1_1_id_ops.html',1,'System::Runtime::Remoting']]],
  ['idrole',['IDRole',['../class_system_1_1_security_1_1_permissions_1_1_i_d_role.html',1,'System::Security::Permissions']]],
  ['idynamicmessagesink',['IDynamicMessageSink',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_dynamic_message_sink.html',1,'System::Runtime::Remoting::Contexts']]],
  ['idynamicproperty',['IDynamicProperty',['../interface_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_i_dynamic_property.html',1,'System::Runtime::Remoting::Contexts']]],
  ['ientrypointentry',['IEntryPointEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_entry_point_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['ienumconnectionpoints',['IEnumConnectionPoints',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_enum_connection_points.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['ienumconnections',['IEnumConnections',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_enum_connections.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['ienumdefinitionidentity',['IEnumDefinitionIdentity',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_enum_definition_identity.html',1,'System::Deployment::Internal::Isolation']]],
  ['ienumerable',['IEnumerable',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_enumerable.html',1,'System.Runtime.InteropServices.ComTypes.IEnumerable'],['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System.Collections.IEnumerable'],['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerable.html',1,'System.Collections.Generic.IEnumerable&lt; out out T &gt;']]],
  ['ienumerable_3c_20char_20_3e',['IEnumerable&lt; char &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20claim_20_3e',['IEnumerable&lt; Claim &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerable.html',1,'System::Collections::Generic']]],
  ['ienumerable_3c_20cultureinfo_20_3e',['IEnumerable&lt; CultureInfo &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20evidencebase_20_3e',['IEnumerable&lt; EvidenceBase &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20identityreference_20_3e',['IEnumerable&lt; IdentityReference &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20keyvaluepair_3c_20long_2c_20tsource_20_3e_20_3e',['IEnumerable&lt; KeyValuePair&lt; long, TSource &gt; &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20string_20_3e',['IEnumerable&lt; string &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20system_3a_3asecurity_3a_3aclaims_3a_3aclaimsidentity_20_3e',['IEnumerable&lt; System::Security::Claims::ClaimsIdentity &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerable.html',1,'System::Collections::Generic']]],
  ['ienumerable_3c_20system_3a_3asecurity_3a_3apolicy_3a_3aidelayevaluatedevidence_20_3e',['IEnumerable&lt; System::Security::Policy::IDelayEvaluatedEvidence &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20system_3a_3athreading_3a_3atasks_3a_3atask_20_3e',['IEnumerable&lt; System::Threading::Tasks::Task &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerable.html',1,'System::Collections::Generic']]],
  ['ienumerable_3c_20t_20_3e',['IEnumerable&lt; T &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System.Collections.IEnumerable&lt; T &gt;'],['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerable.html',1,'System.Collections.Generic.IEnumerable&lt; T &gt;']]],
  ['ienumerable_3c_20tkey_20_3e',['IEnumerable&lt; TKey &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerable.html',1,'System.Collections.Generic.IEnumerable&lt; TKey &gt;'],['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System.Collections.IEnumerable&lt; TKey &gt;']]],
  ['ienumerable_3c_20tsource_20_3e',['IEnumerable&lt; TSource &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System::Collections']]],
  ['ienumerable_3c_20tvalue_20_3e',['IEnumerable&lt; TValue &gt;',['../interface_system_1_1_collections_1_1_i_enumerable.html',1,'System.Collections.IEnumerable&lt; TValue &gt;'],['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerable.html',1,'System.Collections.Generic.IEnumerable&lt; TValue &gt;']]],
  ['ienumerator',['IEnumerator',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_enumerator.html',1,'System.Runtime.InteropServices.ComTypes.IEnumerator'],['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System.Collections.IEnumerator'],['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerator.html',1,'System.Collections.Generic.IEnumerator&lt; out out T &gt;']]],
  ['ienumerator_3c_20char_20_3e',['IEnumerator&lt; char &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System::Collections']]],
  ['ienumerator_3c_20evidencebase_20_3e',['IEnumerator&lt; EvidenceBase &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System::Collections']]],
  ['ienumerator_3c_20identityreference_20_3e',['IEnumerator&lt; IdentityReference &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System::Collections']]],
  ['ienumerator_3c_20keyvaluepair_3c_20long_2c_20tsource_20_3e_20_3e',['IEnumerator&lt; KeyValuePair&lt; long, TSource &gt; &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System::Collections']]],
  ['ienumerator_3c_20keyvaluepair_3c_20tkey_2c_20tvalue_20_3e_20_3e',['IEnumerator&lt; KeyValuePair&lt; TKey, TValue &gt; &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System::Collections']]],
  ['ienumerator_3c_20object_20_3e',['IEnumerator&lt; object &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System::Collections']]],
  ['ienumerator_3c_20t_20_3e',['IEnumerator&lt; T &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System.Collections.IEnumerator&lt; T &gt;'],['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerator.html',1,'System.Collections.Generic.IEnumerator&lt; T &gt;']]],
  ['ienumerator_3c_20tkey_20_3e',['IEnumerator&lt; TKey &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerator.html',1,'System::Collections::Generic']]],
  ['ienumerator_3c_20tsource_20_3e',['IEnumerator&lt; TSource &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System::Collections']]],
  ['ienumerator_3c_20tvalue_20_3e',['IEnumerator&lt; TValue &gt;',['../interface_system_1_1_collections_1_1_i_enumerator.html',1,'System.Collections.IEnumerator&lt; TValue &gt;'],['../interface_system_1_1_collections_1_1_generic_1_1_i_enumerator.html',1,'System.Collections.Generic.IEnumerator&lt; TValue &gt;']]],
  ['ienumidentity_5fattribute',['IEnumIDENTITY_ATTRIBUTE',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_enum_i_d_e_n_t_i_t_y___a_t_t_r_i_b_u_t_e.html',1,'System::Deployment::Internal::Isolation']]],
  ['ienummoniker',['IEnumMoniker',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_enum_moniker.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['ienumreferenceidentity',['IEnumReferenceIdentity',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_enum_reference_identity.html',1,'System::Deployment::Internal::Isolation']]],
  ['ienumstore_5fassembly',['IEnumSTORE_ASSEMBLY',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_enum_s_t_o_r_e___a_s_s_e_m_b_l_y.html',1,'System::Deployment::Internal::Isolation']]],
  ['ienumstore_5fassembly_5ffile',['IEnumSTORE_ASSEMBLY_FILE',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_enum_s_t_o_r_e___a_s_s_e_m_b_l_y___f_i_l_e.html',1,'System::Deployment::Internal::Isolation']]],
  ['ienumstore_5fassembly_5finstallation_5freference',['IEnumSTORE_ASSEMBLY_INSTALLATION_REFERENCE',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_enum_s_t_o_r_e___a_s_s_e_m_b_l_4c765da971345ae051ff2207211c90f0.html',1,'System::Deployment::Internal::Isolation']]],
  ['ienumstore_5fcategory',['IEnumSTORE_CATEGORY',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_enum_s_t_o_r_e___c_a_t_e_g_o_r_y.html',1,'System::Deployment::Internal::Isolation']]],
  ['ienumstore_5fcategory_5finstance',['IEnumSTORE_CATEGORY_INSTANCE',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_enum_s_t_o_r_e___c_a_t_e_g_o_r_y___i_n_s_t_a_n_c_e.html',1,'System::Deployment::Internal::Isolation']]],
  ['ienumstore_5fcategory_5fsubcategory',['IEnumSTORE_CATEGORY_SUBCATEGORY',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_enum_s_t_o_r_e___c_a_t_e_g_o_r_y___s_u_b_c_a_t_e_g_o_r_y.html',1,'System::Deployment::Internal::Isolation']]],
  ['ienumstore_5fdeployment_5fmetadata',['IEnumSTORE_DEPLOYMENT_METADATA',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_enum_s_t_o_r_e___d_e_p_l_o_y_m_e_n_t___m_e_t_a_d_a_t_a.html',1,'System::Deployment::Internal::Isolation']]],
  ['ienumstore_5fdeployment_5fmetadata_5fproperty',['IEnumSTORE_DEPLOYMENT_METADATA_PROPERTY',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_enum_s_t_o_r_e___d_e_p_l_o_y_m_48751da2bd0d2914acee70e9e2f4e57c.html',1,'System::Deployment::Internal::Isolation']]],
  ['ienumstring',['IEnumString',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_enum_string.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['ienumunknown',['IEnumUnknown',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_enum_unknown.html',1,'System::Deployment::Internal::Isolation']]],
  ['ienumvariant',['IEnumVARIANT',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_enum_v_a_r_i_a_n_t.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['ienvoyinfo',['IEnvoyInfo',['../interface_system_1_1_runtime_1_1_remoting_1_1_i_envoy_info.html',1,'System::Runtime::Remoting']]],
  ['iequalitycomparer',['IEqualityComparer',['../interface_system_1_1_collections_1_1_i_equality_comparer.html',1,'System.Collections.IEqualityComparer'],['../interface_system_1_1_collections_1_1_generic_1_1_i_equality_comparer.html',1,'System.Collections.Generic.IEqualityComparer&lt; in in T &gt;']]],
  ['iequalitycomparer_3c_20eventcachekey_20_3e',['IEqualityComparer&lt; EventCacheKey &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_equality_comparer.html',1,'System::Collections::Generic']]],
  ['iequalitycomparer_3c_20string_20_3e',['IEqualityComparer&lt; string &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_equality_comparer.html',1,'System::Collections::Generic']]],
  ['iequalitycomparer_3c_20t_20_3e',['IEqualityComparer&lt; T &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_equality_comparer.html',1,'System::Collections::Generic']]],
  ['iequalitycomparer_3c_20tkey_20_3e',['IEqualityComparer&lt; TKey &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_equality_comparer.html',1,'System.Collections.Generic.IEqualityComparer&lt; TKey &gt;'],['../interface_system_1_1_collections_1_1_i_equality_comparer.html',1,'System.Collections.IEqualityComparer&lt; TKey &gt;']]],
  ['iequatable',['IEquatable',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20adjustmentrule_20_3e',['IEquatable&lt; AdjustmentRule &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20bool_20_3e',['IEquatable&lt; bool &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20byte_20_3e',['IEquatable&lt; byte &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20cancellationtokenregistration_20_3e',['IEquatable&lt; CancellationTokenRegistration &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20char_20_3e',['IEquatable&lt; char &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20datetime_20_3e',['IEquatable&lt; DateTime &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20datetimeoffset_20_3e',['IEquatable&lt; DateTimeOffset &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20decimal_20_3e',['IEquatable&lt; decimal &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20double_20_3e',['IEquatable&lt; double &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20exceptionhandler_20_3e',['IEquatable&lt; ExceptionHandler &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20float_20_3e',['IEquatable&lt; float &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20guid_20_3e',['IEquatable&lt; Guid &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20hashalgorithmname_20_3e',['IEquatable&lt; HashAlgorithmName &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20int_20_3e',['IEquatable&lt; int &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20long_20_3e',['IEquatable&lt; long &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20osplatform_20_3e',['IEquatable&lt; OSPlatform &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20rsaencryptionpadding_20_3e',['IEquatable&lt; RSAEncryptionPadding &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20rsasignaturepadding_20_3e',['IEquatable&lt; RSASignaturePadding &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20sbyte_20_3e',['IEquatable&lt; sbyte &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20short_20_3e',['IEquatable&lt; short &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20sortversion_20_3e',['IEquatable&lt; SortVersion &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20string_20_3e',['IEquatable&lt; string &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20timespan_20_3e',['IEquatable&lt; TimeSpan &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20timezoneinfo_20_3e',['IEquatable&lt; TimeZoneInfo &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20transitiontime_20_3e',['IEquatable&lt; TransitionTime &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20uint_20_3e',['IEquatable&lt; uint &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20ulong_20_3e',['IEquatable&lt; ulong &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20ushort_20_3e',['IEquatable&lt; ushort &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20valuetuple_20_3e',['IEquatable&lt; ValueTuple &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_20version_20_3e',['IEquatable&lt; Version &gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_28t1_2c_20t2_29_3e',['IEquatable&lt;(T1, T2)&gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_28t1_2c_20t2_2c_20t3_29_3e',['IEquatable&lt;(T1, T2, T3)&gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_28t1_2c_20t2_2c_20t3_2c_20t4_29_3e',['IEquatable&lt;(T1, T2, T3, T4)&gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_28t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_29_3e',['IEquatable&lt;(T1, T2, T3, T4, T5)&gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_28t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_2c_20t6_29_3e',['IEquatable&lt;(T1, T2, T3, T4, T5, T6)&gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['iequatable_3c_28t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_2c_20t6_2c_20t7_29_3e',['IEquatable&lt;(T1, T2, T3, T4, T5, T6, T7)&gt;',['../interface_system_1_1_i_equatable.html',1,'System']]],
  ['ievidencefactory',['IEvidenceFactory',['../interface_system_1_1_security_1_1_i_evidence_factory.html',1,'System::Security']]],
  ['iexpando',['IExpando',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_expando.html',1,'System.Runtime.InteropServices.ComTypes.IExpando'],['../interface_system_1_1_runtime_1_1_interop_services_1_1_expando_1_1_i_expando.html',1,'System.Runtime.InteropServices.Expando.IExpando']]],
  ['ifieldinfo',['IFieldInfo',['../interface_system_1_1_runtime_1_1_serialization_1_1_formatters_1_1_i_field_info.html',1,'System::Runtime::Serialization::Formatters']]],
  ['ifileassociationentry',['IFileAssociationEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_file_association_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['ifileentry',['IFileEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_file_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['iformatprovider',['IFormatProvider',['../interface_system_1_1_i_format_provider.html',1,'System']]],
  ['iformattable',['IFormattable',['../interface_system_1_1_i_formattable.html',1,'System']]],
  ['iformatter',['IFormatter',['../interface_system_1_1_runtime_1_1_serialization_1_1_i_formatter.html',1,'System::Runtime::Serialization']]],
  ['iformatterconverter',['IFormatterConverter',['../interface_system_1_1_runtime_1_1_serialization_1_1_i_formatter_converter.html',1,'System::Runtime::Serialization']]],
  ['igetproxytarget',['IGetProxyTarget',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_get_proxy_target.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['ihashcodeprovider',['IHashCodeProvider',['../interface_system_1_1_collections_1_1_i_hash_code_provider.html',1,'System::Collections']]],
  ['ihashelemententry',['IHashElementEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_hash_element_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['iidentity',['IIdentity',['../interface_system_1_1_security_1_1_principal_1_1_i_identity.html',1,'System::Security::Principal']]],
  ['iidentityauthority',['IIdentityAuthority',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_identity_authority.html',1,'System::Deployment::Internal::Isolation']]],
  ['iidentitypermissionfactory',['IIdentityPermissionFactory',['../interface_system_1_1_security_1_1_policy_1_1_i_identity_permission_factory.html',1,'System::Security::Policy']]],
  ['iinternalmessage',['IInternalMessage',['../interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_internal_message.html',1,'System::Runtime::Remoting::Messaging']]],
  ['iiterable',['IIterable',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_iterable.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['iiterator',['IIterator',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_iterator.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['iiterator_3c_20object_20_3e',['IIterator&lt; object &gt;',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_iterator.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['ikeyvaluepair',['IKeyValuePair',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_key_value_pair.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['ilease',['ILease',['../interface_system_1_1_runtime_1_1_remoting_1_1_lifetime_1_1_i_lease.html',1,'System::Runtime::Remoting::Lifetime']]],
  ['ilegacyevidenceadapter',['ILegacyEvidenceAdapter',['../interface_system_1_1_security_1_1_policy_1_1_i_legacy_evidence_adapter.html',1,'System::Security::Policy']]],
  ['ilgenerator',['ILGenerator',['../class_system_1_1_reflection_1_1_emit_1_1_i_l_generator.html',1,'System::Reflection::Emit']]],
  ['ilist',['IList',['../interface_system_1_1_collections_1_1_i_list.html',1,'System.Collections.IList'],['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System.Collections.Generic.IList&lt; T &gt;']]],
  ['ilist_3c_20object_20_3e',['IList&lt; object &gt;',['../interface_system_1_1_collections_1_1_i_list.html',1,'System.Collections.IList&lt; object &gt;'],['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System.Collections.Generic.IList&lt; object &gt;']]],
  ['ilist_3c_20string_20_3e',['IList&lt; string &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20system_3a_3areflection_3a_3acustomattributenamedargument_20_3e',['IList&lt; System::Reflection::CustomAttributeNamedArgument &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20system_3a_3areflection_3a_3acustomattributetypedargument_20_3e',['IList&lt; System::Reflection::CustomAttributeTypedArgument &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20system_3a_3areflection_3a_3aexceptionhandlingclause_20_3e',['IList&lt; System::Reflection::ExceptionHandlingClause &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20system_3a_3areflection_3a_3alocalvariableinfo_20_3e',['IList&lt; System::Reflection::LocalVariableInfo &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20system_3a_3asecurity_3a_3apolicy_3a_3astrongname_20_3e',['IList&lt; System::Security::Policy::StrongName &gt;',['../interface_system_1_1_collections_1_1_i_list.html',1,'System::Collections']]],
  ['ilist_3c_20system_3a_3athreading_3a_3atasks_3a_3atask_20_3e',['IList&lt; System::Threading::Tasks::Task &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_list.html',1,'System::Collections::Generic']]],
  ['ilist_3c_20t_20_3e',['IList&lt; T &gt;',['../interface_system_1_1_collections_1_1_i_list.html',1,'System::Collections']]],
  ['ilist_3c_20tsource_20_3e',['IList&lt; TSource &gt;',['../interface_system_1_1_collections_1_1_i_list.html',1,'System::Collections']]],
  ['illogicalcallcontext',['IllogicalCallContext',['../class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_illogical_call_context.html',1,'System::Runtime::Remoting::Messaging']]],
  ['ilogicalthreadaffinative',['ILogicalThreadAffinative',['../interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_logical_thread_affinative.html',1,'System::Runtime::Remoting::Messaging']]],
  ['imanagedactivationfactory',['IManagedActivationFactory',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_managed_activation_factory.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['imanifestinformation',['IManifestInformation',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_manifest_information.html',1,'System::Deployment::Internal::Isolation']]],
  ['imanifestparseerrorcallback',['IManifestParseErrorCallback',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_manifest_parse_error_callback.html',1,'System::Deployment::Internal::Isolation']]],
  ['imap',['IMap',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_map.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['imapview',['IMapView',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_map_view.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['imapview_3c_20tkey_2c_20tvalue_20_3e',['IMapView&lt; TKey, TValue &gt;',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_map_view.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['imapviewtoireadonlydictionaryadapter',['IMapViewToIReadOnlyDictionaryAdapter',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_map_view_to_i_read_only_dictionary_adapter.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['imembershipcondition',['IMembershipCondition',['../interface_system_1_1_security_1_1_policy_1_1_i_membership_condition.html',1,'System::Security::Policy']]],
  ['imessage',['IMessage',['../interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_message.html',1,'System::Runtime::Remoting::Messaging']]],
  ['imessagectrl',['IMessageCtrl',['../interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_message_ctrl.html',1,'System::Runtime::Remoting::Messaging']]],
  ['imessagesink',['IMessageSink',['../interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_message_sink.html',1,'System::Runtime::Remoting::Messaging']]],
  ['imetadatasectionentry',['IMetadataSectionEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_metadata_section_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['imethodcallmessage',['IMethodCallMessage',['../interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_method_call_message.html',1,'System::Runtime::Remoting::Messaging']]],
  ['imethodmessage',['IMethodMessage',['../interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_method_message.html',1,'System::Runtime::Remoting::Messaging']]],
  ['imethodreturnmessage',['IMethodReturnMessage',['../interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_method_return_message.html',1,'System::Runtime::Remoting::Messaging']]],
  ['imoniker',['IMoniker',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_moniker.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['importedfromtypelibattribute',['ImportedFromTypeLibAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_imported_from_type_lib_attribute.html',1,'System::Runtime::InteropServices']]],
  ['importercallback',['ImporterCallback',['../class_system_1_1_runtime_1_1_interop_services_1_1_importer_callback.html',1,'System::Runtime::InteropServices']]],
  ['imuiresourceidlookupmapentry',['IMuiResourceIdLookupMapEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_mui_resource_id_lookup_map_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['imuiresourcemapentry',['IMuiResourceMapEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_mui_resource_map_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['imuiresourcetypeidintentry',['IMuiResourceTypeIdIntEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_mui_resource_type_id_int_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['imuiresourcetypeidstringentry',['IMuiResourceTypeIdStringEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_mui_resource_type_id_string_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['inattribute',['InAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_in_attribute.html',1,'System::Runtime::InteropServices']]],
  ['indexernameattribute',['IndexerNameAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_indexer_name_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['indexoutofrangeexception',['IndexOutOfRangeException',['../class_system_1_1_index_out_of_range_exception.html',1,'System']]],
  ['indexrange',['IndexRange',['../struct_system_1_1_threading_1_1_tasks_1_1_index_range.html',1,'System::Threading::Tasks']]],
  ['inormalizeforisolatedstorage',['INormalizeForIsolatedStorage',['../interface_system_1_1_i_o_1_1_isolated_storage_1_1_i_normalize_for_isolated_storage.html',1,'System::IO::IsolatedStorage']]],
  ['inotifycompletion',['INotifyCompletion',['../interface_system_1_1_runtime_1_1_compiler_services_1_1_i_notify_completion.html',1,'System::Runtime::CompilerServices']]],
  ['insufficientexecutionstackexception',['InsufficientExecutionStackException',['../class_system_1_1_insufficient_execution_stack_exception.html',1,'System']]],
  ['insufficientmemoryexception',['InsufficientMemoryException',['../class_system_1_1_insufficient_memory_exception.html',1,'System']]],
  ['int16',['Int16',['../struct_system_1_1_int16.html',1,'System']]],
  ['int16arraytypeinfo',['Int16ArrayTypeInfo',['../class_system_1_1_diagnostics_1_1_tracing_1_1_int16_array_type_info.html',1,'System::Diagnostics::Tracing']]],
  ['int16typeinfo',['Int16TypeInfo',['../class_system_1_1_diagnostics_1_1_tracing_1_1_int16_type_info.html',1,'System::Diagnostics::Tracing']]],
  ['int32',['Int32',['../struct_system_1_1_int32.html',1,'System']]],
  ['int32arraytypeinfo',['Int32ArrayTypeInfo',['../class_system_1_1_diagnostics_1_1_tracing_1_1_int32_array_type_info.html',1,'System::Diagnostics::Tracing']]],
  ['int32typeinfo',['Int32TypeInfo',['../class_system_1_1_diagnostics_1_1_tracing_1_1_int32_type_info.html',1,'System::Diagnostics::Tracing']]],
  ['int64',['Int64',['../struct_system_1_1_int64.html',1,'System']]],
  ['int64arraytypeinfo',['Int64ArrayTypeInfo',['../class_system_1_1_diagnostics_1_1_tracing_1_1_int64_array_type_info.html',1,'System::Diagnostics::Tracing']]],
  ['int64typeinfo',['Int64TypeInfo',['../class_system_1_1_diagnostics_1_1_tracing_1_1_int64_type_info.html',1,'System::Diagnostics::Tracing']]],
  ['interfaceimplementedinversionattribute',['InterfaceImplementedInVersionAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_interface_implemented_in_version_attribute.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['interfacemapping',['InterfaceMapping',['../struct_system_1_1_reflection_1_1_interface_mapping.html',1,'System::Reflection']]],
  ['interfacemarshaler',['InterfaceMarshaler',['../class_system_1_1_stub_helpers_1_1_interface_marshaler.html',1,'System::StubHelpers']]],
  ['interfacetypeattribute',['InterfaceTypeAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_interface_type_attribute.html',1,'System::Runtime::InteropServices']]],
  ['interlocked',['Interlocked',['../class_system_1_1_threading_1_1_interlocked.html',1,'System::Threading']]],
  ['internal',['Internal',['../class_system_1_1_internal.html',1,'System']]],
  ['internalactivationcontexthelper',['InternalActivationContextHelper',['../class_system_1_1_deployment_1_1_internal_1_1_internal_activation_context_helper.html',1,'System::Deployment::Internal']]],
  ['internalapplicationidentityhelper',['InternalApplicationIdentityHelper',['../class_system_1_1_deployment_1_1_internal_1_1_internal_application_identity_helper.html',1,'System::Deployment::Internal']]],
  ['internalassemblybuilder',['InternalAssemblyBuilder',['../class_system_1_1_reflection_1_1_emit_1_1_internal_assembly_builder.html',1,'System::Reflection::Emit']]],
  ['internalcodepagedataitem',['InternalCodePageDataItem',['../struct_system_1_1_globalization_1_1_internal_code_page_data_item.html',1,'System::Globalization']]],
  ['internaldecoderbestfitfallback',['InternalDecoderBestFitFallback',['../class_system_1_1_text_1_1_internal_decoder_best_fit_fallback.html',1,'System::Text']]],
  ['internaldecoderbestfitfallbackbuffer',['InternalDecoderBestFitFallbackBuffer',['../class_system_1_1_text_1_1_internal_decoder_best_fit_fallback_buffer.html',1,'System::Text']]],
  ['internalencoderbestfitfallback',['InternalEncoderBestFitFallback',['../class_system_1_1_text_1_1_internal_encoder_best_fit_fallback.html',1,'System::Text']]],
  ['internalencoderbestfitfallbackbuffer',['InternalEncoderBestFitFallbackBuffer',['../class_system_1_1_text_1_1_internal_encoder_best_fit_fallback_buffer.html',1,'System::Text']]],
  ['internalencodingdataitem',['InternalEncodingDataItem',['../struct_system_1_1_globalization_1_1_internal_encoding_data_item.html',1,'System::Globalization']]],
  ['internalfe',['InternalFE',['../class_system_1_1_runtime_1_1_serialization_1_1_formatters_1_1_binary_1_1_internal_f_e.html',1,'System::Runtime::Serialization::Formatters::Binary']]],
  ['internalmessagewrapper',['InternalMessageWrapper',['../class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_internal_message_wrapper.html',1,'System::Runtime::Remoting::Messaging']]],
  ['internalmodulebuilder',['InternalModuleBuilder',['../class_system_1_1_reflection_1_1_emit_1_1_internal_module_builder.html',1,'System::Reflection::Emit']]],
  ['internalremotingservices',['InternalRemotingServices',['../class_system_1_1_runtime_1_1_remoting_1_1_internal_remoting_services.html',1,'System::Runtime::Remoting']]],
  ['internalrm',['InternalRM',['../class_system_1_1_runtime_1_1_serialization_1_1_formatters_1_1_internal_r_m.html',1,'System::Runtime::Serialization::Formatters']]],
  ['internalsink',['InternalSink',['../class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_internal_sink.html',1,'System::Runtime::Remoting::Messaging']]],
  ['internalst',['InternalST',['../class_system_1_1_runtime_1_1_serialization_1_1_formatters_1_1_internal_s_t.html',1,'System::Runtime::Serialization::Formatters']]],
  ['internalsvisibletoattribute',['InternalsVisibleToAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_internals_visible_to_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['intptr',['IntPtr',['../struct_system_1_1_int_ptr.html',1,'System']]],
  ['intptrarraytypeinfo',['IntPtrArrayTypeInfo',['../class_system_1_1_diagnostics_1_1_tracing_1_1_int_ptr_array_type_info.html',1,'System::Diagnostics::Tracing']]],
  ['intptrtypeinfo',['IntPtrTypeInfo',['../class_system_1_1_diagnostics_1_1_tracing_1_1_int_ptr_type_info.html',1,'System::Diagnostics::Tracing']]],
  ['introducedmethodenumerator',['IntroducedMethodEnumerator',['../struct_system_1_1_runtime_type_handle_1_1_introduced_method_enumerator.html',1,'System::RuntimeTypeHandle']]],
  ['introspectionextensions',['IntrospectionExtensions',['../class_system_1_1_reflection_1_1_introspection_extensions.html',1,'System::Reflection']]],
  ['introspectivesortutilities',['IntrospectiveSortUtilities',['../class_system_1_1_collections_1_1_generic_1_1_introspective_sort_utilities.html',1,'System::Collections::Generic']]],
  ['intsizedarray',['IntSizedArray',['../class_system_1_1_runtime_1_1_serialization_1_1_formatters_1_1_binary_1_1_int_sized_array.html',1,'System::Runtime::Serialization::Formatters::Binary']]],
  ['invalidcastexception',['InvalidCastException',['../class_system_1_1_invalid_cast_exception.html',1,'System']]],
  ['invalidcomobjectexception',['InvalidComObjectException',['../class_system_1_1_runtime_1_1_interop_services_1_1_invalid_com_object_exception.html',1,'System::Runtime::InteropServices']]],
  ['invalidfiltercriteriaexception',['InvalidFilterCriteriaException',['../class_system_1_1_reflection_1_1_invalid_filter_criteria_exception.html',1,'System::Reflection']]],
  ['invalidolevarianttypeexception',['InvalidOleVariantTypeException',['../class_system_1_1_runtime_1_1_interop_services_1_1_invalid_ole_variant_type_exception.html',1,'System::Runtime::InteropServices']]],
  ['invalidoperationexception',['InvalidOperationException',['../class_system_1_1_invalid_operation_exception.html',1,'System']]],
  ['invalidprogramexception',['InvalidProgramException',['../class_system_1_1_invalid_program_exception.html',1,'System']]],
  ['invalidtimezoneexception',['InvalidTimeZoneException',['../class_system_1_1_invalid_time_zone_exception.html',1,'System']]],
  ['invoketypeinfo',['InvokeTypeInfo',['../class_system_1_1_diagnostics_1_1_tracing_1_1_invoke_type_info.html',1,'System::Diagnostics::Tracing']]],
  ['iobjecthandle',['IObjectHandle',['../interface_system_1_1_runtime_1_1_remoting_1_1_i_object_handle.html',1,'System::Runtime::Remoting']]],
  ['iobjectreference',['IObjectReference',['../interface_system_1_1_runtime_1_1_serialization_1_1_i_object_reference.html',1,'System::Runtime::Serialization']]],
  ['iobservable',['IObservable',['../interface_system_1_1_i_observable.html',1,'System']]],
  ['iobserver',['IObserver',['../interface_system_1_1_i_observer.html',1,'System']]],
  ['ioexception',['IOException',['../class_system_1_1_i_o_1_1_i_o_exception.html',1,'System::IO']]],
  ['ioutil',['IOUtil',['../class_system_1_1_runtime_1_1_serialization_1_1_formatters_1_1_binary_1_1_i_o_util.html',1,'System::Runtime::Serialization::Formatters::Binary']]],
  ['ipathlock',['IPathLock',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_store_1_1_i_path_lock.html',1,'System::Deployment::Internal::Isolation::Store']]],
  ['ipermission',['IPermission',['../interface_system_1_1_security_1_1_i_permission.html',1,'System::Security']]],
  ['ipermissionsetentry',['IPermissionSetEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_permission_set_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['ipersistfile',['IPersistFile',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_persist_file.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['iprincipal',['IPrincipal',['../interface_system_1_1_security_1_1_principal_1_1_i_principal.html',1,'System::Security::Principal']]],
  ['iproducerconsumercollection',['IProducerConsumerCollection',['../interface_system_1_1_collections_1_1_concurrent_1_1_i_producer_consumer_collection.html',1,'System::Collections::Concurrent']]],
  ['iproducerconsumerqueue',['IProducerConsumerQueue',['../interface_system_1_1_threading_1_1_tasks_1_1_i_producer_consumer_queue.html',1,'System::Threading::Tasks']]],
  ['iproducerconsumerqueue_3c_20system_3a_3athreading_3a_3atasks_3a_3atask_20_3e',['IProducerConsumerQueue&lt; System::Threading::Tasks::Task &gt;',['../interface_system_1_1_threading_1_1_tasks_1_1_i_producer_consumer_queue.html',1,'System::Threading::Tasks']]],
  ['iprogidredirectionentry',['IProgIdRedirectionEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_prog_id_redirection_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['iprogress',['IProgress',['../interface_system_1_1_i_progress.html',1,'System']]],
  ['iprogress_3c_20t_20_3e',['IProgress&lt; T &gt;',['../interface_system_1_1_i_progress.html',1,'System']]],
  ['ipropertyvalue',['IPropertyValue',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_property_value.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['ireadonlycollection',['IReadOnlyCollection',['../interface_system_1_1_collections_1_1_generic_1_1_i_read_only_collection.html',1,'System::Collections::Generic']]],
  ['ireadonlycollection_3c_20t_20_3e',['IReadOnlyCollection&lt; T &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_read_only_collection.html',1,'System::Collections::Generic']]],
  ['ireadonlycollection_3c_20tkey_20_3e',['IReadOnlyCollection&lt; TKey &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_read_only_collection.html',1,'System::Collections::Generic']]],
  ['ireadonlycollection_3c_20tvalue_20_3e',['IReadOnlyCollection&lt; TValue &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_read_only_collection.html',1,'System::Collections::Generic']]],
  ['ireadonlydictionary',['IReadOnlyDictionary',['../interface_system_1_1_collections_1_1_generic_1_1_i_read_only_dictionary.html',1,'System::Collections::Generic']]],
  ['ireadonlydictionarytoimapviewadapter',['IReadOnlyDictionaryToIMapViewAdapter',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_read_only_dictionary_to_i_map_view_adapter.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['ireadonlylist',['IReadOnlyList',['../interface_system_1_1_collections_1_1_generic_1_1_i_read_only_list.html',1,'System::Collections::Generic']]],
  ['ireadonlylist_3c_20t_20_3e',['IReadOnlyList&lt; T &gt;',['../interface_system_1_1_collections_1_1_generic_1_1_i_read_only_list.html',1,'System::Collections::Generic']]],
  ['ireadonlylisttoivectorviewadapter',['IReadOnlyListToIVectorViewAdapter',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_read_only_list_to_i_vector_view_adapter.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['ireference',['IReference',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_reference.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['ireferenceappid',['IReferenceAppId',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_reference_app_id.html',1,'System::Deployment::Internal::Isolation']]],
  ['ireferencearray',['IReferenceArray',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_reference_array.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['ireferencefactory',['IReferenceFactory',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_reference_factory.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['ireferenceidentity',['IReferenceIdentity',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_reference_identity.html',1,'System::Deployment::Internal::Isolation']]],
  ['ireflect',['IReflect',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_reflect.html',1,'System.Runtime.InteropServices.ComTypes.IReflect'],['../interface_system_1_1_reflection_1_1_i_reflect.html',1,'System.Reflection.IReflect']]],
  ['ireflectabletype',['IReflectableType',['../interface_system_1_1_reflection_1_1_i_reflectable_type.html',1,'System::Reflection']]],
  ['iregistrationservices',['IRegistrationServices',['../interface_system_1_1_runtime_1_1_interop_services_1_1_i_registration_services.html',1,'System::Runtime::InteropServices']]],
  ['iremotingformatter',['IRemotingFormatter',['../interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_remoting_formatter.html',1,'System::Runtime::Remoting::Messaging']]],
  ['iremotingtypeinfo',['IRemotingTypeInfo',['../interface_system_1_1_runtime_1_1_remoting_1_1_i_remoting_type_info.html',1,'System::Runtime::Remoting']]],
  ['ireportmatchmembershipcondition',['IReportMatchMembershipCondition',['../interface_system_1_1_security_1_1_policy_1_1_i_report_match_membership_condition.html',1,'System::Security::Policy']]],
  ['iresourcegroveler',['IResourceGroveler',['../interface_system_1_1_resources_1_1_i_resource_groveler.html',1,'System::Resources']]],
  ['iresourcereader',['IResourceReader',['../interface_system_1_1_resources_1_1_i_resource_reader.html',1,'System::Resources']]],
  ['iresourcetablemappingentry',['IResourceTableMappingEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_resource_table_mapping_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['iresourcewriter',['IResourceWriter',['../interface_system_1_1_resources_1_1_i_resource_writer.html',1,'System::Resources']]],
  ['irestrictederrorinfo',['IRestrictedErrorInfo',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_restricted_error_info.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['irunningobjecttable',['IRunningObjectTable',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_running_object_table.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['iruntimeevidencefactory',['IRuntimeEvidenceFactory',['../interface_system_1_1_security_1_1_policy_1_1_i_runtime_evidence_factory.html',1,'System::Security::Policy']]],
  ['iruntimefieldinfo',['IRuntimeFieldInfo',['../interface_system_1_1_i_runtime_field_info.html',1,'System']]],
  ['iruntimemethodinfo',['IRuntimeMethodInfo',['../interface_system_1_1_i_runtime_method_info.html',1,'System']]],
  ['isafeserializationdata',['ISafeSerializationData',['../interface_system_1_1_runtime_1_1_serialization_1_1_i_safe_serialization_data.html',1,'System::Runtime::Serialization']]],
  ['isboxed',['IsBoxed',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_boxed.html',1,'System::Runtime::CompilerServices']]],
  ['isbyreflikeattribute',['IsByRefLikeAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_by_ref_like_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['isbyvalue',['IsByValue',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_by_value.html',1,'System::Runtime::CompilerServices']]],
  ['isciiencoding',['ISCIIEncoding',['../class_system_1_1_text_1_1_i_s_c_i_i_encoding.html',1,'System::Text']]],
  ['isconst',['IsConst',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_const.html',1,'System::Runtime::CompilerServices']]],
  ['iscopyconstructed',['IsCopyConstructed',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_copy_constructed.html',1,'System::Runtime::CompilerServices']]],
  ['isection',['ISection',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_section.html',1,'System::Deployment::Internal::Isolation']]],
  ['isectionentry',['ISectionEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_section_entry.html',1,'System::Deployment::Internal::Isolation']]],
  ['isectionwithreferenceidentitykey',['ISectionWithReferenceIdentityKey',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_section_with_reference_identity_key.html',1,'System::Deployment::Internal::Isolation']]],
  ['isectionwithstringkey',['ISectionWithStringKey',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_section_with_string_key.html',1,'System::Deployment::Internal::Isolation']]],
  ['isecurablechannel',['ISecurableChannel',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_securable_channel.html',1,'System::Runtime::Remoting::Channels']]],
  ['isecurityelementfactory',['ISecurityElementFactory',['../interface_system_1_1_security_1_1_i_security_element_factory.html',1,'System::Security']]],
  ['isecurityencodable',['ISecurityEncodable',['../interface_system_1_1_security_1_1_i_security_encodable.html',1,'System::Security']]],
  ['isecuritypolicyencodable',['ISecurityPolicyEncodable',['../interface_system_1_1_security_1_1_i_security_policy_encodable.html',1,'System::Security']]],
  ['iserializable',['ISerializable',['../interface_system_1_1_runtime_1_1_serialization_1_1_i_serializable.html',1,'System::Runtime::Serialization']]],
  ['iserializationrootobject',['ISerializationRootObject',['../interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_serialization_root_object.html',1,'System::Runtime::Remoting::Messaging']]],
  ['iserializationsurrogate',['ISerializationSurrogate',['../interface_system_1_1_runtime_1_1_serialization_1_1_i_serialization_surrogate.html',1,'System::Runtime::Serialization']]],
  ['iserverchannelsink',['IServerChannelSink',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_server_channel_sink.html',1,'System::Runtime::Remoting::Channels']]],
  ['iserverchannelsinkprovider',['IServerChannelSinkProvider',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_server_channel_sink_provider.html',1,'System::Runtime::Remoting::Channels']]],
  ['iserverchannelsinkstack',['IServerChannelSinkStack',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_server_channel_sink_stack.html',1,'System::Runtime::Remoting::Channels']]],
  ['iserverformattersinkprovider',['IServerFormatterSinkProvider',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_server_formatter_sink_provider.html',1,'System::Runtime::Remoting::Channels']]],
  ['iserverresponsechannelsinkstack',['IServerResponseChannelSinkStack',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_server_response_channel_sink_stack.html',1,'System::Runtime::Remoting::Channels']]],
  ['iserviceprovider',['IServiceProvider',['../interface_system_1_1_i_service_provider.html',1,'System']]],
  ['isexplicitlydereferenced',['IsExplicitlyDereferenced',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_explicitly_dereferenced.html',1,'System::Runtime::CompilerServices']]],
  ['isimplicitlydereferenced',['IsImplicitlyDereferenced',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_implicitly_dereferenced.html',1,'System::Runtime::CompilerServices']]],
  ['isjitintrinsic',['IsJitIntrinsic',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_jit_intrinsic.html',1,'System::Runtime::CompilerServices']]],
  ['islong',['IsLong',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_long.html',1,'System::Runtime::CompilerServices']]],
  ['iso2022encoding',['ISO2022Encoding',['../class_system_1_1_text_1_1_i_s_o2022_encoding.html',1,'System::Text']]],
  ['isoapmessage',['ISoapMessage',['../interface_system_1_1_runtime_1_1_serialization_1_1_formatters_1_1_i_soap_message.html',1,'System::Runtime::Serialization::Formatters']]],
  ['isoapxsd',['ISoapXsd',['../interface_system_1_1_runtime_1_1_remoting_1_1_metadata_1_1_w3c_xsd2001_1_1_i_soap_xsd.html',1,'System::Runtime::Remoting::Metadata::W3cXsd2001']]],
  ['isolatedstorage',['IsolatedStorage',['../class_system_1_1_i_o_1_1_isolated_storage_1_1_isolated_storage.html',1,'System::IO::IsolatedStorage']]],
  ['isolatedstorageexception',['IsolatedStorageException',['../class_system_1_1_i_o_1_1_isolated_storage_1_1_isolated_storage_exception.html',1,'System::IO::IsolatedStorage']]],
  ['isolatedstoragefile',['IsolatedStorageFile',['../class_system_1_1_i_o_1_1_isolated_storage_1_1_isolated_storage_file.html',1,'System::IO::IsolatedStorage']]],
  ['isolatedstoragefileenumerator',['IsolatedStorageFileEnumerator',['../class_system_1_1_i_o_1_1_isolated_storage_1_1_isolated_storage_file_enumerator.html',1,'System::IO::IsolatedStorage']]],
  ['isolatedstoragefilepermission',['IsolatedStorageFilePermission',['../class_system_1_1_security_1_1_permissions_1_1_isolated_storage_file_permission.html',1,'System::Security::Permissions']]],
  ['isolatedstoragefilepermissionattribute',['IsolatedStorageFilePermissionAttribute',['../class_system_1_1_security_1_1_permissions_1_1_isolated_storage_file_permission_attribute.html',1,'System::Security::Permissions']]],
  ['isolatedstoragefilestream',['IsolatedStorageFileStream',['../class_system_1_1_i_o_1_1_isolated_storage_1_1_isolated_storage_file_stream.html',1,'System::IO::IsolatedStorage']]],
  ['isolatedstoragepermission',['IsolatedStoragePermission',['../class_system_1_1_security_1_1_permissions_1_1_isolated_storage_permission.html',1,'System::Security::Permissions']]],
  ['isolatedstoragepermissionattribute',['IsolatedStoragePermissionAttribute',['../class_system_1_1_security_1_1_permissions_1_1_isolated_storage_permission_attribute.html',1,'System::Security::Permissions']]],
  ['isolatedstoragesecuritystate',['IsolatedStorageSecurityState',['../class_system_1_1_i_o_1_1_isolated_storage_1_1_isolated_storage_security_state.html',1,'System::IO::IsolatedStorage']]],
  ['isolationinterop',['IsolationInterop',['../class_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_isolation_interop.html',1,'System::Deployment::Internal::Isolation']]],
  ['ispinned',['IsPinned',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_pinned.html',1,'System::Runtime::CompilerServices']]],
  ['isponsor',['ISponsor',['../interface_system_1_1_runtime_1_1_remoting_1_1_lifetime_1_1_i_sponsor.html',1,'System::Runtime::Remoting::Lifetime']]],
  ['isreadonlyattribute',['IsReadOnlyAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_read_only_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['issignunspecifiedbyte',['IsSignUnspecifiedByte',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_sign_unspecified_byte.html',1,'System::Runtime::CompilerServices']]],
  ['istackwalk',['IStackWalk',['../interface_system_1_1_security_1_1_i_stack_walk.html',1,'System::Security']]],
  ['istatemanager',['IStateManager',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_state_manager.html',1,'System::Deployment::Internal::Isolation']]],
  ['istore',['IStore',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_store.html',1,'System::Deployment::Internal::Isolation']]],
  ['istore_5fbindingresult',['IStore_BindingResult',['../struct_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_store___binding_result.html',1,'System::Deployment::Internal::Isolation']]],
  ['istore_5fbindingresult_5fboundversion',['IStore_BindingResult_BoundVersion',['../struct_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_i_store___binding_result___bound_version.html',1,'System::Deployment::Internal::Isolation']]],
  ['istream',['IStream',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_stream.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['istreamable',['IStreamable',['../interface_system_1_1_runtime_1_1_serialization_1_1_formatters_1_1_binary_1_1_i_streamable.html',1,'System::Runtime::Serialization::Formatters::Binary']]],
  ['istringable',['IStringable',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_stringable.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['istringablehelper',['IStringableHelper',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_stringable_helper.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['istructuralcomparable',['IStructuralComparable',['../interface_system_1_1_collections_1_1_i_structural_comparable.html',1,'System::Collections']]],
  ['istructuralequatable',['IStructuralEquatable',['../interface_system_1_1_collections_1_1_i_structural_equatable.html',1,'System::Collections']]],
  ['isubcategorymembershipentry',['ISubcategoryMembershipEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_subcategory_membership_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['isudtreturn',['IsUdtReturn',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_udt_return.html',1,'System::Runtime::CompilerServices']]],
  ['isurrogateselector',['ISurrogateSelector',['../interface_system_1_1_runtime_1_1_serialization_1_1_i_surrogate_selector.html',1,'System::Runtime::Serialization']]],
  ['isvolatile',['IsVolatile',['../class_system_1_1_runtime_1_1_compiler_services_1_1_is_volatile.html',1,'System::Runtime::CompilerServices']]],
  ['isymbolbinder',['ISymbolBinder',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_binder.html',1,'System::Diagnostics::SymbolStore']]],
  ['isymbolbinder1',['ISymbolBinder1',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_binder1.html',1,'System::Diagnostics::SymbolStore']]],
  ['isymboldocument',['ISymbolDocument',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_document.html',1,'System::Diagnostics::SymbolStore']]],
  ['isymboldocumentwriter',['ISymbolDocumentWriter',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_document_writer.html',1,'System::Diagnostics::SymbolStore']]],
  ['isymbolmethod',['ISymbolMethod',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_method.html',1,'System::Diagnostics::SymbolStore']]],
  ['isymbolnamespace',['ISymbolNamespace',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_namespace.html',1,'System::Diagnostics::SymbolStore']]],
  ['isymbolreader',['ISymbolReader',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_reader.html',1,'System::Diagnostics::SymbolStore']]],
  ['isymbolscope',['ISymbolScope',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_scope.html',1,'System::Diagnostics::SymbolStore']]],
  ['isymbolvariable',['ISymbolVariable',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_variable.html',1,'System::Diagnostics::SymbolStore']]],
  ['isymbolwriter',['ISymbolWriter',['../interface_system_1_1_diagnostics_1_1_symbol_store_1_1_i_symbol_writer.html',1,'System::Diagnostics::SymbolStore']]],
  ['itaskcompletionaction',['ITaskCompletionAction',['../interface_system_1_1_threading_1_1_tasks_1_1_i_task_completion_action.html',1,'System::Threading::Tasks']]],
  ['iterabletoenumerableadapter',['IterableToEnumerableAdapter',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_iterable_to_enumerable_adapter.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['iterator',['Iterator',['../class_system_1_1_i_o_1_1_iterator.html',1,'System::IO']]],
  ['iterator_3c_20string_20_3e',['Iterator&lt; string &gt;',['../class_system_1_1_i_o_1_1_iterator.html',1,'System::IO']]],
  ['iteratorstatemachineattribute',['IteratorStateMachineAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_iterator_state_machine_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['iteratortoenumeratoradapter',['IteratorToEnumeratorAdapter',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_iterator_to_enumerator_adapter.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['ithreadpoolworkitem',['IThreadPoolWorkItem',['../interface_system_1_1_threading_1_1_i_thread_pool_work_item.html',1,'System::Threading']]],
  ['itracingstatuschangedeventargs',['ITracingStatusChangedEventArgs',['../interface_windows_1_1_foundation_1_1_diagnostics_1_1_i_tracing_status_changed_event_args.html',1,'Windows::Foundation::Diagnostics']]],
  ['itrackinghandler',['ITrackingHandler',['../interface_system_1_1_runtime_1_1_remoting_1_1_services_1_1_i_tracking_handler.html',1,'System::Runtime::Remoting::Services']]],
  ['itransportheaders',['ITransportHeaders',['../interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_transport_headers.html',1,'System::Runtime::Remoting::Channels']]],
  ['ituple',['ITuple',['../interface_system_1_1_runtime_1_1_compiler_services_1_1_i_tuple.html',1,'System::Runtime::CompilerServices']]],
  ['itupleinternal',['ITupleInternal',['../interface_system_1_1_i_tuple_internal.html',1,'System']]],
  ['itypecomp',['ITypeComp',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_type_comp.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['itypeinfo',['ITypeInfo',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_type_info.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['itypeinfo2',['ITypeInfo2',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_type_info2.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['itypelib',['ITypeLib',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_type_lib.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['itypelib2',['ITypeLib2',['../interface_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_i_type_lib2.html',1,'System::Runtime::InteropServices::ComTypes']]],
  ['itypelibconverter',['ITypeLibConverter',['../interface_system_1_1_runtime_1_1_interop_services_1_1_i_type_lib_converter.html',1,'System::Runtime::InteropServices']]],
  ['itypelibexporternameprovider',['ITypeLibExporterNameProvider',['../interface_system_1_1_runtime_1_1_interop_services_1_1_i_type_lib_exporter_name_provider.html',1,'System::Runtime::InteropServices']]],
  ['itypelibexporternotifysink',['ITypeLibExporterNotifySink',['../interface_system_1_1_runtime_1_1_interop_services_1_1_i_type_lib_exporter_notify_sink.html',1,'System::Runtime::InteropServices']]],
  ['itypelibimporternotifysink',['ITypeLibImporterNotifySink',['../interface_system_1_1_runtime_1_1_interop_services_1_1_i_type_lib_importer_notify_sink.html',1,'System::Runtime::InteropServices']]],
  ['iunionsemanticcodegroup',['IUnionSemanticCodeGroup',['../interface_system_1_1_security_1_1_policy_1_1_i_union_semantic_code_group.html',1,'System::Security::Policy']]],
  ['iunknownconstantattribute',['IUnknownConstantAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_i_unknown_constant_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['iunknownsafehandle',['IUnknownSafeHandle',['../class_system_1_1_threading_1_1_i_unknown_safe_handle.html',1,'System::Threading']]],
  ['iunrestrictedpermission',['IUnrestrictedPermission',['../interface_system_1_1_security_1_1_permissions_1_1_i_unrestricted_permission.html',1,'System::Security::Permissions']]],
  ['ivaluetupleinternal',['IValueTupleInternal',['../interface_system_1_1_i_value_tuple_internal.html',1,'System']]],
  ['ivector',['IVector',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_vector.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['ivector_5fraw',['IVector_Raw',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_vector___raw.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['ivectorview',['IVectorView',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_vector_view.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['ivectorviewtoireadonlylistadapter',['IVectorViewToIReadOnlyListAdapter',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_vector_view_to_i_read_only_list_adapter.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['iwellknownstringequalitycomparer',['IWellKnownStringEqualityComparer',['../interface_system_1_1_i_well_known_string_equality_comparer.html',1,'System']]],
  ['iwindowclassentry',['IWindowClassEntry',['../interface_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_i_window_class_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['iwinrtclassactivator',['IWinRTClassActivator',['../interface_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_i_win_r_t_class_activator.html',1,'System::Runtime::InteropServices::WindowsRuntime']]]
];
