var searchData=
[
  ['calendar',['Calendar',['../class_system_1_1_globalization_1_1_calendar.html',1,'System::Globalization']]],
  ['calendardata',['CalendarData',['../class_system_1_1_globalization_1_1_calendar_data.html',1,'System::Globalization']]],
  ['calendricalcalculationshelper',['CalendricalCalculationsHelper',['../class_system_1_1_globalization_1_1_calendrical_calculations_helper.html',1,'System::Globalization']]],
  ['callbackhelper',['CallBackHelper',['../class_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_call_back_helper.html',1,'System::Runtime::Remoting::Contexts']]],
  ['callcontext',['CallContext',['../class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_call_context.html',1,'System::Runtime::Remoting::Messaging']]],
  ['callcontextremotingdata',['CallContextRemotingData',['../class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_call_context_remoting_data.html',1,'System::Runtime::Remoting::Messaging']]],
  ['callcontextsecuritydata',['CallContextSecurityData',['../class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_call_context_security_data.html',1,'System::Runtime::Remoting::Messaging']]],
  ['callconvcdecl',['CallConvCdecl',['../class_system_1_1_runtime_1_1_compiler_services_1_1_call_conv_cdecl.html',1,'System::Runtime::CompilerServices']]],
  ['callconvfastcall',['CallConvFastcall',['../class_system_1_1_runtime_1_1_compiler_services_1_1_call_conv_fastcall.html',1,'System::Runtime::CompilerServices']]],
  ['callconvstdcall',['CallConvStdcall',['../class_system_1_1_runtime_1_1_compiler_services_1_1_call_conv_stdcall.html',1,'System::Runtime::CompilerServices']]],
  ['callconvthiscall',['CallConvThiscall',['../class_system_1_1_runtime_1_1_compiler_services_1_1_call_conv_thiscall.html',1,'System::Runtime::CompilerServices']]],
  ['callerfilepathattribute',['CallerFilePathAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_caller_file_path_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['callerlinenumberattribute',['CallerLineNumberAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_caller_line_number_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['callermembernameattribute',['CallerMemberNameAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_caller_member_name_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['cancellationcallbackcoreworkarguments',['CancellationCallbackCoreWorkArguments',['../struct_system_1_1_threading_1_1_cancellation_callback_core_work_arguments.html',1,'System::Threading']]],
  ['cancellationcallbackinfo',['CancellationCallbackInfo',['../class_system_1_1_threading_1_1_cancellation_callback_info.html',1,'System::Threading']]],
  ['cancellationtoken',['CancellationToken',['../struct_system_1_1_threading_1_1_cancellation_token.html',1,'System::Threading']]],
  ['cancellationtokenregistration',['CancellationTokenRegistration',['../struct_system_1_1_threading_1_1_cancellation_token_registration.html',1,'System::Threading']]],
  ['cancellationtokensource',['CancellationTokenSource',['../class_system_1_1_threading_1_1_cancellation_token_source.html',1,'System::Threading']]],
  ['cannotunloadappdomainexception',['CannotUnloadAppDomainException',['../class_system_1_1_cannot_unload_app_domain_exception.html',1,'System']]],
  ['canof',['CANOF',['../class_microsoft_1_1_win32_1_1_c_a_n_o_f.html',1,'Microsoft::Win32']]],
  ['capinative',['CapiNative',['../class_system_1_1_security_1_1_cryptography_1_1_capi_native.html',1,'System::Security::Cryptography']]],
  ['caseinsensitivecomparer',['CaseInsensitiveComparer',['../class_system_1_1_collections_1_1_case_insensitive_comparer.html',1,'System::Collections']]],
  ['caseinsensitivehashcodeprovider',['CaseInsensitiveHashCodeProvider',['../class_system_1_1_collections_1_1_case_insensitive_hash_code_provider.html',1,'System::Collections']]],
  ['category',['CATEGORY',['../struct_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_c_a_t_e_g_o_r_y.html',1,'System::Deployment::Internal::Isolation']]],
  ['category_5finstance',['CATEGORY_INSTANCE',['../struct_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_c_a_t_e_g_o_r_y___i_n_s_t_a_n_c_e.html',1,'System::Deployment::Internal::Isolation']]],
  ['category_5fsubcategory',['CATEGORY_SUBCATEGORY',['../struct_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_c_a_t_e_g_o_r_y___s_u_b_c_a_t_e_g_o_r_y.html',1,'System::Deployment::Internal::Isolation']]],
  ['categorymembershipdataentry',['CategoryMembershipDataEntry',['../class_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_category_membership_data_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['categorymembershipentry',['CategoryMembershipEntry',['../class_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_category_membership_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['ccmdictionary',['CCMDictionary',['../class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_c_c_m_dictionary.html',1,'System::Runtime::Remoting::Messaging']]],
  ['cdscollectionetwbclprovider',['CDSCollectionETWBCLProvider',['../class_system_1_1_collections_1_1_concurrent_1_1_c_d_s_collection_e_t_w_b_c_l_provider.html',1,'System::Collections::Concurrent']]],
  ['cdssyncetwbclprovider',['CdsSyncEtwBCLProvider',['../class_system_1_1_threading_1_1_cds_sync_etw_b_c_l_provider.html',1,'System::Threading']]],
  ['cerhashtable',['CerHashtable',['../struct_system_1_1_reflection_1_1_cer_hashtable.html',1,'System::Reflection']]],
  ['cerhashtable_3c_20runtimemethodinfo_2c_20runtimemethodinfo_20_3e',['CerHashtable&lt; RuntimeMethodInfo, RuntimeMethodInfo &gt;',['../struct_system_1_1_reflection_1_1_cer_hashtable.html',1,'System::Reflection']]],
  ['cerhashtable_3c_20string_2c_20t_5b_5d_3e',['CerHashtable&lt; string, T[]&gt;',['../struct_system_1_1_reflection_1_1_cer_hashtable.html',1,'System::Reflection']]],
  ['cerhashtable_3c_20system_3a_3areflection_3a_3aruntimemethodinfo_2c_20system_3a_3areflection_3a_3aruntimemethodinfo_20_3e',['CerHashtable&lt; System::Reflection::RuntimeMethodInfo, System::Reflection::RuntimeMethodInfo &gt;',['../struct_system_1_1_reflection_1_1_cer_hashtable.html',1,'System::Reflection']]],
  ['channeldatastore',['ChannelDataStore',['../class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_channel_data_store.html',1,'System::Runtime::Remoting::Channels']]],
  ['channelinfo',['ChannelInfo',['../class_system_1_1_runtime_1_1_remoting_1_1_channel_info.html',1,'System::Runtime::Remoting']]],
  ['channelservices',['ChannelServices',['../class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_channel_services.html',1,'System::Runtime::Remoting::Channels']]],
  ['channelservicesdata',['ChannelServicesData',['../class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_channel_services_data.html',1,'System::Runtime::Remoting::Channels']]],
  ['char',['Char',['../struct_system_1_1_char.html',1,'System']]],
  ['chararraytypeinfo',['CharArrayTypeInfo',['../class_system_1_1_diagnostics_1_1_tracing_1_1_char_array_type_info.html',1,'System::Diagnostics::Tracing']]],
  ['charenumerator',['CharEnumerator',['../class_system_1_1_char_enumerator.html',1,'System']]],
  ['chartypeinfo',['CharTypeInfo',['../class_system_1_1_diagnostics_1_1_tracing_1_1_char_type_info.html',1,'System::Diagnostics::Tracing']]],
  ['charunicodeinfo',['CharUnicodeInfo',['../class_system_1_1_globalization_1_1_char_unicode_info.html',1,'System::Globalization']]],
  ['chineselunisolarcalendar',['ChineseLunisolarCalendar',['../class_system_1_1_globalization_1_1_chinese_lunisolar_calendar.html',1,'System::Globalization']]],
  ['claim',['Claim',['../class_system_1_1_security_1_1_claims_1_1_claim.html',1,'System::Security::Claims']]],
  ['claimsidentity',['ClaimsIdentity',['../class_system_1_1_security_1_1_claims_1_1_claims_identity.html',1,'System::Security::Claims']]],
  ['claimsprincipal',['ClaimsPrincipal',['../class_system_1_1_security_1_1_claims_1_1_claims_principal.html',1,'System::Security::Claims']]],
  ['claimtypes',['ClaimTypes',['../class_system_1_1_security_1_1_claims_1_1_claim_types.html',1,'System::Security::Claims']]],
  ['claimvaluetypes',['ClaimValueTypes',['../class_system_1_1_security_1_1_claims_1_1_claim_value_types.html',1,'System::Security::Claims']]],
  ['classinterfaceattribute',['ClassInterfaceAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_class_interface_attribute.html',1,'System::Runtime::InteropServices']]],
  ['classpropertywriter',['ClassPropertyWriter',['../class_system_1_1_diagnostics_1_1_tracing_1_1_class_property_writer.html',1,'System::Diagnostics::Tracing']]],
  ['cleanupworklist',['CleanupWorkList',['../class_system_1_1_stub_helpers_1_1_cleanup_work_list.html',1,'System::StubHelpers']]],
  ['cleanupworklistelement',['CleanupWorkListElement',['../class_system_1_1_stub_helpers_1_1_cleanup_work_list_element.html',1,'System::StubHelpers']]],
  ['clientasyncreplyterminatorsink',['ClientAsyncReplyTerminatorSink',['../class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_client_async_reply_terminator_sink.html',1,'System::Runtime::Remoting::Messaging']]],
  ['clientchannelsinkstack',['ClientChannelSinkStack',['../class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_client_channel_sink_stack.html',1,'System::Runtime::Remoting::Channels']]],
  ['clientcontextterminatorsink',['ClientContextTerminatorSink',['../class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_client_context_terminator_sink.html',1,'System::Runtime::Remoting::Messaging']]],
  ['clientsponsor',['ClientSponsor',['../class_system_1_1_runtime_1_1_remoting_1_1_lifetime_1_1_client_sponsor.html',1,'System::Runtime::Remoting::Lifetime']]],
  ['clrconfig',['CLRConfig',['../class_system_1_1_c_l_r_config.html',1,'System']]],
  ['clrikeyvaluepairimpl',['CLRIKeyValuePairImpl',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_c_l_r_i_key_value_pair_impl.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['clripropertyvalueimpl',['CLRIPropertyValueImpl',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_c_l_r_i_property_value_impl.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['clrireferencearrayimpl',['CLRIReferenceArrayImpl',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_c_l_r_i_reference_array_impl.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['clrireferenceimpl',['CLRIReferenceImpl',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_c_l_r_i_reference_impl.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['clrsurrogateentry',['CLRSurrogateEntry',['../class_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_c_l_r_surrogate_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['clscompliantattribute',['CLSCompliantAttribute',['../class_system_1_1_c_l_s_compliant_attribute.html',1,'System']]],
  ['cmsutils',['CmsUtils',['../class_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_cms_utils.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['coclassattribute',['CoClassAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_co_class_attribute.html',1,'System::Runtime::InteropServices']]],
  ['codeaccesspermission',['CodeAccessPermission',['../class_system_1_1_security_1_1_code_access_permission.html',1,'System::Security']]],
  ['codeaccesssecurityattribute',['CodeAccessSecurityAttribute',['../class_system_1_1_security_1_1_permissions_1_1_code_access_security_attribute.html',1,'System::Security::Permissions']]],
  ['codeaccesssecurityengine',['CodeAccessSecurityEngine',['../class_system_1_1_security_1_1_code_access_security_engine.html',1,'System::Security']]],
  ['codeconnectaccess',['CodeConnectAccess',['../class_system_1_1_security_1_1_policy_1_1_code_connect_access.html',1,'System::Security::Policy']]],
  ['codegroup',['CodeGroup',['../class_system_1_1_security_1_1_policy_1_1_code_group.html',1,'System::Security::Policy']]],
  ['codegrouppositionmarker',['CodeGroupPositionMarker',['../class_system_1_1_security_1_1_policy_1_1_code_group_position_marker.html',1,'System::Security::Policy']]],
  ['codegroupstack',['CodeGroupStack',['../class_system_1_1_security_1_1_policy_1_1_code_group_stack.html',1,'System::Security::Policy']]],
  ['codegroupstackframe',['CodeGroupStackFrame',['../class_system_1_1_security_1_1_policy_1_1_code_group_stack_frame.html',1,'System::Security::Policy']]],
  ['codepagedataitem',['CodePageDataItem',['../class_system_1_1_globalization_1_1_code_page_data_item.html',1,'System::Globalization']]],
  ['codepageencoding',['CodePageEncoding',['../class_system_1_1_text_1_1_code_page_encoding.html',1,'System::Text']]],
  ['collection',['Collection',['../class_system_1_1_collections_1_1_object_model_1_1_collection.html',1,'System::Collections::ObjectModel']]],
  ['collection_3c_20assembly_20_3e',['Collection&lt; Assembly &gt;',['../class_system_1_1_collections_1_1_object_model_1_1_collection.html',1,'System::Collections::ObjectModel']]],
  ['collection_3c_20ienumerable_3c_20system_3a_3asecurity_3a_3aclaims_3a_3aclaim_20_3e_20_3e',['Collection&lt; IEnumerable&lt; System::Security::Claims::Claim &gt; &gt;',['../class_system_1_1_collections_1_1_object_model_1_1_collection.html',1,'System::Collections::ObjectModel']]],
  ['collection_3c_20string_20_3e',['Collection&lt; string &gt;',['../class_system_1_1_collections_1_1_object_model_1_1_collection.html',1,'System::Collections::ObjectModel']]],
  ['collection_3c_20titem_20_3e',['Collection&lt; TItem &gt;',['../class_system_1_1_collections_1_1_object_model_1_1_collection.html',1,'System::Collections::ObjectModel']]],
  ['collectionbase',['CollectionBase',['../class_system_1_1_collections_1_1_collection_base.html',1,'System::Collections']]],
  ['comaliasnameattribute',['ComAliasNameAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_com_alias_name_attribute.html',1,'System::Runtime::InteropServices']]],
  ['comcompatibleversionattribute',['ComCompatibleVersionAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_com_compatible_version_attribute.html',1,'System::Runtime::InteropServices']]],
  ['comconversionlossattribute',['ComConversionLossAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_com_conversion_loss_attribute.html',1,'System::Runtime::InteropServices']]],
  ['comdefaultinterfaceattribute',['ComDefaultInterfaceAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_com_default_interface_attribute.html',1,'System::Runtime::InteropServices']]],
  ['comeventinterfaceattribute',['ComEventInterfaceAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_com_event_interface_attribute.html',1,'System::Runtime::InteropServices']]],
  ['comeventshelper',['ComEventsHelper',['../class_system_1_1_runtime_1_1_interop_services_1_1_com_events_helper.html',1,'System::Runtime::InteropServices']]],
  ['comeventsinfo',['ComEventsInfo',['../class_system_1_1_runtime_1_1_interop_services_1_1_com_events_info.html',1,'System::Runtime::InteropServices']]],
  ['comeventsmethod',['ComEventsMethod',['../class_system_1_1_runtime_1_1_interop_services_1_1_com_events_method.html',1,'System::Runtime::InteropServices']]],
  ['comeventssink',['ComEventsSink',['../class_system_1_1_runtime_1_1_interop_services_1_1_com_events_sink.html',1,'System::Runtime::InteropServices']]],
  ['comexception',['COMException',['../class_system_1_1_runtime_1_1_interop_services_1_1_c_o_m_exception.html',1,'System::Runtime::InteropServices']]],
  ['comimportattribute',['ComImportAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_com_import_attribute.html',1,'System::Runtime::InteropServices']]],
  ['commonace',['CommonAce',['../class_system_1_1_security_1_1_access_control_1_1_common_ace.html',1,'System::Security::AccessControl']]],
  ['commonacl',['CommonAcl',['../class_system_1_1_security_1_1_access_control_1_1_common_acl.html',1,'System::Security::AccessControl']]],
  ['commonobjectsecurity',['CommonObjectSecurity',['../class_system_1_1_security_1_1_access_control_1_1_common_object_security.html',1,'System::Security::AccessControl']]],
  ['commonsecuritydescriptor',['CommonSecurityDescriptor',['../class_system_1_1_security_1_1_access_control_1_1_common_security_descriptor.html',1,'System::Security::AccessControl']]],
  ['compareinfo',['CompareInfo',['../class_system_1_1_globalization_1_1_compare_info.html',1,'System::Globalization']]],
  ['comparer',['Comparer',['../class_system_1_1_collections_1_1_comparer.html',1,'System.Collections.Comparer'],['../class_system_1_1_collections_1_1_generic_1_1_comparer.html',1,'System.Collections.Generic.Comparer&lt; T &gt;']]],
  ['comparer_3c_20t_3f_3e',['Comparer&lt; T?&gt;',['../class_system_1_1_collections_1_1_generic_1_1_comparer.html',1,'System::Collections::Generic']]],
  ['comparisoncomparer',['ComparisonComparer',['../class_system_1_1_collections_1_1_generic_1_1_comparison_comparer.html',1,'System::Collections::Generic']]],
  ['compatibilityswitch',['CompatibilitySwitch',['../class_system_1_1_runtime_1_1_versioning_1_1_compatibility_switch.html',1,'System::Runtime::Versioning']]],
  ['compatibilityswitches',['CompatibilitySwitches',['../class_system_1_1_compatibility_switches.html',1,'System']]],
  ['compatiblecomparer',['CompatibleComparer',['../class_system_1_1_collections_1_1_compatible_comparer.html',1,'System::Collections']]],
  ['compatibleframeworksmetadataentry',['CompatibleFrameworksMetadataEntry',['../class_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_compatible_frameworks_metadata_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['compilationrelaxationsattribute',['CompilationRelaxationsAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_compilation_relaxations_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['compilergeneratedattribute',['CompilerGeneratedAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_compiler_generated_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['compilerglobalscopeattribute',['CompilerGlobalScopeAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_compiler_global_scope_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['compilermarshaloverride',['CompilerMarshalOverride',['../class_system_1_1_runtime_1_1_compiler_services_1_1_compiler_marshal_override.html',1,'System::Runtime::CompilerServices']]],
  ['completionactioninvoker',['CompletionActionInvoker',['../class_system_1_1_threading_1_1_tasks_1_1_completion_action_invoker.html',1,'System::Threading::Tasks']]],
  ['componentguaranteesattribute',['ComponentGuaranteesAttribute',['../class_system_1_1_runtime_1_1_versioning_1_1_component_guarantees_attribute.html',1,'System::Runtime::Versioning']]],
  ['compoundace',['CompoundAce',['../class_system_1_1_security_1_1_access_control_1_1_compound_ace.html',1,'System::Security::AccessControl']]],
  ['compressedstack',['CompressedStack',['../class_system_1_1_threading_1_1_compressed_stack.html',1,'System::Threading']]],
  ['compressedstackswitcher',['CompressedStackSwitcher',['../struct_system_1_1_threading_1_1_compressed_stack_switcher.html',1,'System::Threading']]],
  ['comredirectionproxy',['ComRedirectionProxy',['../class_system_1_1_runtime_1_1_remoting_1_1_com_redirection_proxy.html',1,'System::Runtime::Remoting']]],
  ['comregisterfunctionattribute',['ComRegisterFunctionAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_com_register_function_attribute.html',1,'System::Runtime::InteropServices']]],
  ['comserverentry',['COMServerEntry',['../class_system_1_1_deployment_1_1_internal_1_1_isolation_1_1_manifest_1_1_c_o_m_server_entry.html',1,'System::Deployment::Internal::Isolation::Manifest']]],
  ['comsourceinterfacesattribute',['ComSourceInterfacesAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_com_source_interfaces_attribute.html',1,'System::Runtime::InteropServices']]],
  ['comunregisterfunctionattribute',['ComUnregisterFunctionAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_com_unregister_function_attribute.html',1,'System::Runtime::InteropServices']]],
  ['comvisibleattribute',['ComVisibleAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_com_visible_attribute.html',1,'System::Runtime::InteropServices']]],
  ['concurrentdictionary',['ConcurrentDictionary',['../class_system_1_1_collections_1_1_concurrent_1_1_concurrent_dictionary.html',1,'System::Collections::Concurrent']]],
  ['concurrentdictionary_3c_20int_2c_20processingmode_20_3e',['ConcurrentDictionary&lt; int, ProcessingMode &gt;',['../class_system_1_1_collections_1_1_concurrent_1_1_concurrent_dictionary.html',1,'System::Collections::Concurrent']]],
  ['concurrentdictionary_3c_20string_2c_20object_20_3e',['ConcurrentDictionary&lt; string, object &gt;',['../class_system_1_1_collections_1_1_concurrent_1_1_concurrent_dictionary.html',1,'System::Collections::Concurrent']]],
  ['concurrentdictionary_3c_20system_3a_3aguid_2c_20int_20_3e',['ConcurrentDictionary&lt; System::Guid, int &gt;',['../class_system_1_1_collections_1_1_concurrent_1_1_concurrent_dictionary.html',1,'System::Collections::Concurrent']]],
  ['concurrentdictionary_3c_20system_3a_3aguid_2c_20system_3a_3atuple_3c_20system_3a_3aguid_2c_20int_20_3e_20_3e',['ConcurrentDictionary&lt; System::Guid, System::Tuple&lt; System::Guid, int &gt; &gt;',['../class_system_1_1_collections_1_1_concurrent_1_1_concurrent_dictionary.html',1,'System::Collections::Concurrent']]],
  ['concurrentdictionary_3c_20system_3a_3aruntime_3a_3aserialization_3a_3amemberholder_2c_20memberinfo_5b_5d_3e',['ConcurrentDictionary&lt; System::Runtime::Serialization::MemberHolder, MemberInfo[]&gt;',['../class_system_1_1_collections_1_1_concurrent_1_1_concurrent_dictionary.html',1,'System::Collections::Concurrent']]],
  ['concurrentexclusiveschedulerpair',['ConcurrentExclusiveSchedulerPair',['../class_system_1_1_threading_1_1_tasks_1_1_concurrent_exclusive_scheduler_pair.html',1,'System::Threading::Tasks']]],
  ['concurrentqueue',['ConcurrentQueue',['../class_system_1_1_collections_1_1_concurrent_1_1_concurrent_queue.html',1,'System::Collections::Concurrent']]],
  ['concurrentset',['ConcurrentSet',['../struct_system_1_1_diagnostics_1_1_tracing_1_1_concurrent_set.html',1,'System::Diagnostics::Tracing']]],
  ['concurrentset_3c_20keyvaluepair_3c_20string_2c_20eventtags_20_3e_2c_20system_3a_3adiagnostics_3a_3atracing_3a_3anameinfo_20_3e',['ConcurrentSet&lt; KeyValuePair&lt; string, EventTags &gt;, System::Diagnostics::Tracing::NameInfo &gt;',['../struct_system_1_1_diagnostics_1_1_tracing_1_1_concurrent_set.html',1,'System::Diagnostics::Tracing']]],
  ['concurrentsetitem',['ConcurrentSetItem',['../class_system_1_1_diagnostics_1_1_tracing_1_1_concurrent_set_item.html',1,'System::Diagnostics::Tracing']]],
  ['concurrentsetitem_3c_20keyvaluepair_3c_20string_2c_20eventtags_20_3e_2c_20nameinfo_20_3e',['ConcurrentSetItem&lt; KeyValuePair&lt; string, EventTags &gt;, NameInfo &gt;',['../class_system_1_1_diagnostics_1_1_tracing_1_1_concurrent_set_item.html',1,'System::Diagnostics::Tracing']]],
  ['concurrentstack',['ConcurrentStack',['../class_system_1_1_collections_1_1_concurrent_1_1_concurrent_stack.html',1,'System::Collections::Concurrent']]],
  ['concurrentstack_3c_20object_20_3e',['ConcurrentStack&lt; object &gt;',['../class_system_1_1_collections_1_1_concurrent_1_1_concurrent_stack.html',1,'System::Collections::Concurrent']]],
  ['conditionalattribute',['ConditionalAttribute',['../class_system_1_1_diagnostics_1_1_conditional_attribute.html',1,'System::Diagnostics']]],
  ['conditionalweaktable',['ConditionalWeakTable',['../class_system_1_1_runtime_1_1_compiler_services_1_1_conditional_weak_table.html',1,'System::Runtime::CompilerServices']]],
  ['conditionalweaktable_3c_20object_2c_20dictionary_3c_20methodinfo_2c_20dictionary_3c_20object_2c_20eventregistrationtokenlist_20_3e_20_3e_20_3e',['ConditionalWeakTable&lt; object, Dictionary&lt; MethodInfo, Dictionary&lt; object, EventRegistrationTokenList &gt; &gt; &gt;',['../class_system_1_1_runtime_1_1_compiler_services_1_1_conditional_weak_table.html',1,'System::Runtime::CompilerServices']]],
  ['conditionalweaktable_3c_20object_2c_20eventregistrationtokenlistwithcount_20_3e',['ConditionalWeakTable&lt; object, EventRegistrationTokenListWithCount &gt;',['../class_system_1_1_runtime_1_1_compiler_services_1_1_conditional_weak_table.html',1,'System::Runtime::CompilerServices']]],
  ['conditionalweaktable_3c_20object_2c_20serializationinfo_20_3e',['ConditionalWeakTable&lt; object, SerializationInfo &gt;',['../class_system_1_1_runtime_1_1_compiler_services_1_1_conditional_weak_table.html',1,'System::Runtime::CompilerServices']]],
  ['conditionalweaktable_3c_20system_3a_3athreading_3a_3atasks_3a_3ataskscheduler_2c_20object_20_3e',['ConditionalWeakTable&lt; System::Threading::Tasks::TaskScheduler, object &gt;',['../class_system_1_1_runtime_1_1_compiler_services_1_1_conditional_weak_table.html',1,'System::Runtime::CompilerServices']]],
  ['config',['Config',['../class_system_1_1_security_1_1_util_1_1_config.html',1,'System::Security::Util']]],
  ['confignode',['ConfigNode',['../class_system_1_1_config_node.html',1,'System']]],
  ['configtreeparser',['ConfigTreeParser',['../class_system_1_1_config_tree_parser.html',1,'System']]],
  ['configuredtaskawaitable',['ConfiguredTaskAwaitable',['../struct_system_1_1_runtime_1_1_compiler_services_1_1_configured_task_awaitable.html',1,'System.Runtime.CompilerServices.ConfiguredTaskAwaitable'],['../struct_system_1_1_runtime_1_1_compiler_services_1_1_configured_task_awaitable.html',1,'System.Runtime.CompilerServices.ConfiguredTaskAwaitable&lt; TResult &gt;']]],
  ['configuredtaskawaiter',['ConfiguredTaskAwaiter',['../struct_system_1_1_runtime_1_1_compiler_services_1_1_configured_task_awaitable_1_1_configured_task_awaiter.html',1,'System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter'],['../struct_system_1_1_runtime_1_1_compiler_services_1_1_configured_task_awaitable_1_1_configured_task_awaiter.html',1,'System.Runtime.CompilerServices.ConfiguredTaskAwaitable&lt; TResult &gt;.ConfiguredTaskAwaiter']]],
  ['connectdata',['CONNECTDATA',['../struct_system_1_1_runtime_1_1_interop_services_1_1_c_o_n_n_e_c_t_d_a_t_a.html',1,'System.Runtime.InteropServices.CONNECTDATA'],['../struct_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_c_o_n_n_e_c_t_d_a_t_a.html',1,'System.Runtime.InteropServices.ComTypes.CONNECTDATA']]],
  ['console',['Console',['../class_system_1_1_console.html',1,'System']]],
  ['consolecanceleventargs',['ConsoleCancelEventArgs',['../class_system_1_1_console_cancel_event_args.html',1,'System']]],
  ['consolekeyinfo',['ConsoleKeyInfo',['../struct_system_1_1_console_key_info.html',1,'System']]],
  ['constants',['Constants',['../class_system_1_1_security_1_1_cryptography_1_1_constants.html',1,'System::Security::Cryptography']]],
  ['constantsplittablemap',['ConstantSplittableMap',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_constant_splittable_map.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['constarray',['ConstArray',['../struct_system_1_1_reflection_1_1_const_array.html',1,'System::Reflection']]],
  ['constructioncall',['ConstructionCall',['../class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_construction_call.html',1,'System::Runtime::Remoting::Messaging']]],
  ['constructionlevelactivator',['ConstructionLevelActivator',['../class_system_1_1_runtime_1_1_remoting_1_1_activation_1_1_construction_level_activator.html',1,'System::Runtime::Remoting::Activation']]],
  ['constructionresponse',['ConstructionResponse',['../class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_construction_response.html',1,'System::Runtime::Remoting::Messaging']]],
  ['constructorbuilder',['ConstructorBuilder',['../class_system_1_1_reflection_1_1_emit_1_1_constructor_builder.html',1,'System::Reflection::Emit']]],
  ['constructorcallmessage',['ConstructorCallMessage',['../class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_constructor_call_message.html',1,'System::Runtime::Remoting::Messaging']]],
  ['constructorinfo',['ConstructorInfo',['../class_system_1_1_reflection_1_1_constructor_info.html',1,'System::Reflection']]],
  ['constructorontypebuilderinstantiation',['ConstructorOnTypeBuilderInstantiation',['../class_system_1_1_reflection_1_1_emit_1_1_constructor_on_type_builder_instantiation.html',1,'System::Reflection::Emit']]],
  ['constructorreturnmessage',['ConstructorReturnMessage',['../class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_constructor_return_message.html',1,'System::Runtime::Remoting::Messaging']]],
  ['context',['Context',['../class_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_context.html',1,'System::Runtime::Remoting::Contexts']]],
  ['contextattribute',['ContextAttribute',['../class_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_context_attribute.html',1,'System::Runtime::Remoting::Contexts']]],
  ['contextboundobject',['ContextBoundObject',['../class_system_1_1_context_bound_object.html',1,'System']]],
  ['contextlevelactivator',['ContextLevelActivator',['../class_system_1_1_runtime_1_1_remoting_1_1_activation_1_1_context_level_activator.html',1,'System::Runtime::Remoting::Activation']]],
  ['contextmarshalexception',['ContextMarshalException',['../class_system_1_1_context_marshal_exception.html',1,'System']]],
  ['contextproperty',['ContextProperty',['../class_system_1_1_runtime_1_1_remoting_1_1_contexts_1_1_context_property.html',1,'System::Runtime::Remoting::Contexts']]],
  ['contextstaticattribute',['ContextStaticAttribute',['../class_system_1_1_context_static_attribute.html',1,'System']]],
  ['continuationresulttaskfromresulttask',['ContinuationResultTaskFromResultTask',['../class_system_1_1_threading_1_1_tasks_1_1_continuation_result_task_from_result_task.html',1,'System::Threading::Tasks']]],
  ['continuationresulttaskfromtask',['ContinuationResultTaskFromTask',['../class_system_1_1_threading_1_1_tasks_1_1_continuation_result_task_from_task.html',1,'System::Threading::Tasks']]],
  ['continuationtaskfromresulttask',['ContinuationTaskFromResultTask',['../class_system_1_1_threading_1_1_tasks_1_1_continuation_task_from_result_task.html',1,'System::Threading::Tasks']]],
  ['continuationtaskfromtask',['ContinuationTaskFromTask',['../class_system_1_1_threading_1_1_tasks_1_1_continuation_task_from_task.html',1,'System::Threading::Tasks']]],
  ['contract',['Contract',['../class_system_1_1_diagnostics_1_1_contracts_1_1_contract.html',1,'System::Diagnostics::Contracts']]],
  ['contractabbreviatorattribute',['ContractAbbreviatorAttribute',['../class_system_1_1_diagnostics_1_1_contracts_1_1_contract_abbreviator_attribute.html',1,'System::Diagnostics::Contracts']]],
  ['contractargumentvalidatorattribute',['ContractArgumentValidatorAttribute',['../class_system_1_1_diagnostics_1_1_contracts_1_1_contract_argument_validator_attribute.html',1,'System::Diagnostics::Contracts']]],
  ['contractclassattribute',['ContractClassAttribute',['../class_system_1_1_diagnostics_1_1_contracts_1_1_contract_class_attribute.html',1,'System::Diagnostics::Contracts']]],
  ['contractclassforattribute',['ContractClassForAttribute',['../class_system_1_1_diagnostics_1_1_contracts_1_1_contract_class_for_attribute.html',1,'System::Diagnostics::Contracts']]],
  ['contractexception',['ContractException',['../class_system_1_1_diagnostics_1_1_contracts_1_1_contract_exception.html',1,'System::Diagnostics::Contracts']]],
  ['contractfailedeventargs',['ContractFailedEventArgs',['../class_system_1_1_diagnostics_1_1_contracts_1_1_contract_failed_event_args.html',1,'System::Diagnostics::Contracts']]],
  ['contracthelper',['ContractHelper',['../class_system_1_1_runtime_1_1_compiler_services_1_1_contract_helper.html',1,'System.Runtime.CompilerServices.ContractHelper'],['../class_system_1_1_diagnostics_1_1_contracts_1_1_internal_1_1_contract_helper.html',1,'System.Diagnostics.Contracts.Internal.ContractHelper']]],
  ['contractinvariantmethodattribute',['ContractInvariantMethodAttribute',['../class_system_1_1_diagnostics_1_1_contracts_1_1_contract_invariant_method_attribute.html',1,'System::Diagnostics::Contracts']]],
  ['contractoptionattribute',['ContractOptionAttribute',['../class_system_1_1_diagnostics_1_1_contracts_1_1_contract_option_attribute.html',1,'System::Diagnostics::Contracts']]],
  ['contractpublicpropertynameattribute',['ContractPublicPropertyNameAttribute',['../class_system_1_1_diagnostics_1_1_contracts_1_1_contract_public_property_name_attribute.html',1,'System::Diagnostics::Contracts']]],
  ['contractreferenceassemblyattribute',['ContractReferenceAssemblyAttribute',['../class_system_1_1_diagnostics_1_1_contracts_1_1_contract_reference_assembly_attribute.html',1,'System::Diagnostics::Contracts']]],
  ['contractruntimeignoredattribute',['ContractRuntimeIgnoredAttribute',['../class_system_1_1_diagnostics_1_1_contracts_1_1_contract_runtime_ignored_attribute.html',1,'System::Diagnostics::Contracts']]],
  ['contractverificationattribute',['ContractVerificationAttribute',['../class_system_1_1_diagnostics_1_1_contracts_1_1_contract_verification_attribute.html',1,'System::Diagnostics::Contracts']]],
  ['convert',['Convert',['../class_system_1_1_convert.html',1,'System']]],
  ['converter',['Converter',['../class_system_1_1_runtime_1_1_serialization_1_1_formatters_1_1_binary_1_1_converter.html',1,'System::Runtime::Serialization::Formatters::Binary']]],
  ['countdownevent',['CountdownEvent',['../class_system_1_1_threading_1_1_countdown_event.html',1,'System::Threading']]],
  ['criticalfinalizerobject',['CriticalFinalizerObject',['../class_system_1_1_runtime_1_1_constrained_execution_1_1_critical_finalizer_object.html',1,'System::Runtime::ConstrainedExecution']]],
  ['criticalhandle',['CriticalHandle',['../class_system_1_1_runtime_1_1_interop_services_1_1_critical_handle.html',1,'System::Runtime::InteropServices']]],
  ['criticalhandleminusoneisinvalid',['CriticalHandleMinusOneIsInvalid',['../class_microsoft_1_1_win32_1_1_safe_handles_1_1_critical_handle_minus_one_is_invalid.html',1,'Microsoft::Win32::SafeHandles']]],
  ['criticalhandlezeroorminusoneisinvalid',['CriticalHandleZeroOrMinusOneIsInvalid',['../class_microsoft_1_1_win32_1_1_safe_handles_1_1_critical_handle_zero_or_minus_one_is_invalid.html',1,'Microsoft::Win32::SafeHandles']]],
  ['crmdictionary',['CRMDictionary',['../class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_c_r_m_dictionary.html',1,'System::Runtime::Remoting::Messaging']]],
  ['crossappdomainchannel',['CrossAppDomainChannel',['../class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_cross_app_domain_channel.html',1,'System::Runtime::Remoting::Channels']]],
  ['crossappdomaindata',['CrossAppDomainData',['../class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_cross_app_domain_data.html',1,'System::Runtime::Remoting::Channels']]],
  ['crossappdomainserializer',['CrossAppDomainSerializer',['../class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_cross_app_domain_serializer.html',1,'System::Runtime::Remoting::Channels']]],
  ['crossappdomainsink',['CrossAppDomainSink',['../class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_cross_app_domain_sink.html',1,'System::Runtime::Remoting::Channels']]],
  ['crosscontextchannel',['CrossContextChannel',['../class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_cross_context_channel.html',1,'System::Runtime::Remoting::Channels']]],
  ['crypt_5foid_5finfo',['CRYPT_OID_INFO',['../struct_system_1_1_security_1_1_cryptography_1_1_x509_certificates_1_1_c_r_y_p_t___o_i_d___i_n_f_o.html',1,'System::Security::Cryptography::X509Certificates']]],
  ['cryptoapitransform',['CryptoAPITransform',['../class_system_1_1_security_1_1_cryptography_1_1_crypto_a_p_i_transform.html',1,'System::Security::Cryptography']]],
  ['cryptoconfig',['CryptoConfig',['../class_system_1_1_security_1_1_cryptography_1_1_crypto_config.html',1,'System::Security::Cryptography']]],
  ['cryptographicexception',['CryptographicException',['../class_system_1_1_security_1_1_cryptography_1_1_cryptographic_exception.html',1,'System::Security::Cryptography']]],
  ['cryptographicunexpectedoperationexception',['CryptographicUnexpectedOperationException',['../class_system_1_1_security_1_1_cryptography_1_1_cryptographic_unexpected_operation_exception.html',1,'System::Security::Cryptography']]],
  ['cryptokeyaccessrule',['CryptoKeyAccessRule',['../class_system_1_1_security_1_1_access_control_1_1_crypto_key_access_rule.html',1,'System::Security::AccessControl']]],
  ['cryptokeyauditrule',['CryptoKeyAuditRule',['../class_system_1_1_security_1_1_access_control_1_1_crypto_key_audit_rule.html',1,'System::Security::AccessControl']]],
  ['cryptokeysecurity',['CryptoKeySecurity',['../class_system_1_1_security_1_1_access_control_1_1_crypto_key_security.html',1,'System::Security::AccessControl']]],
  ['cryptostream',['CryptoStream',['../class_system_1_1_security_1_1_cryptography_1_1_crypto_stream.html',1,'System::Security::Cryptography']]],
  ['cspkeycontainerinfo',['CspKeyContainerInfo',['../class_system_1_1_security_1_1_cryptography_1_1_csp_key_container_info.html',1,'System::Security::Cryptography']]],
  ['cspparameters',['CspParameters',['../class_system_1_1_security_1_1_cryptography_1_1_csp_parameters.html',1,'System::Security::Cryptography']]],
  ['cstrmarshaler',['CSTRMarshaler',['../class_system_1_1_stub_helpers_1_1_c_s_t_r_marshaler.html',1,'System::StubHelpers']]],
  ['cultureawarecomparer',['CultureAwareComparer',['../class_system_1_1_culture_aware_comparer.html',1,'System']]],
  ['cultureawarerandomizedcomparer',['CultureAwareRandomizedComparer',['../class_system_1_1_culture_aware_randomized_comparer.html',1,'System']]],
  ['culturedata',['CultureData',['../class_system_1_1_globalization_1_1_culture_data.html',1,'System::Globalization']]],
  ['cultureinfo',['CultureInfo',['../class_system_1_1_globalization_1_1_culture_info.html',1,'System::Globalization']]],
  ['culturenotfoundexception',['CultureNotFoundException',['../class_system_1_1_globalization_1_1_culture_not_found_exception.html',1,'System::Globalization']]],
  ['currency',['Currency',['../struct_system_1_1_currency.html',1,'System']]],
  ['currencywrapper',['CurrencyWrapper',['../class_system_1_1_runtime_1_1_interop_services_1_1_currency_wrapper.html',1,'System::Runtime::InteropServices']]],
  ['currentsystemtimezone',['CurrentSystemTimeZone',['../class_system_1_1_current_system_time_zone.html',1,'System']]],
  ['customace',['CustomAce',['../class_system_1_1_security_1_1_access_control_1_1_custom_ace.html',1,'System::Security::AccessControl']]],
  ['customattribute',['CustomAttribute',['../class_system_1_1_reflection_1_1_custom_attribute.html',1,'System::Reflection']]],
  ['customattributebuilder',['CustomAttributeBuilder',['../class_system_1_1_reflection_1_1_emit_1_1_custom_attribute_builder.html',1,'System::Reflection::Emit']]],
  ['customattributectorparameter',['CustomAttributeCtorParameter',['../struct_system_1_1_reflection_1_1_custom_attribute_ctor_parameter.html',1,'System::Reflection']]],
  ['customattributedata',['CustomAttributeData',['../class_system_1_1_reflection_1_1_custom_attribute_data.html',1,'System::Reflection']]],
  ['customattributeencodedargument',['CustomAttributeEncodedArgument',['../struct_system_1_1_reflection_1_1_custom_attribute_encoded_argument.html',1,'System::Reflection']]],
  ['customattributeextensions',['CustomAttributeExtensions',['../class_system_1_1_reflection_1_1_custom_attribute_extensions.html',1,'System::Reflection']]],
  ['customattributeformatexception',['CustomAttributeFormatException',['../class_system_1_1_reflection_1_1_custom_attribute_format_exception.html',1,'System::Reflection']]],
  ['customattributenamedargument',['CustomAttributeNamedArgument',['../struct_system_1_1_reflection_1_1_custom_attribute_named_argument.html',1,'System::Reflection']]],
  ['customattributenamedparameter',['CustomAttributeNamedParameter',['../struct_system_1_1_reflection_1_1_custom_attribute_named_parameter.html',1,'System::Reflection']]],
  ['customattributerecord',['CustomAttributeRecord',['../struct_system_1_1_reflection_1_1_custom_attribute_record.html',1,'System::Reflection']]],
  ['customattributetype',['CustomAttributeType',['../struct_system_1_1_reflection_1_1_custom_attribute_type.html',1,'System::Reflection']]],
  ['customattributetypedargument',['CustomAttributeTypedArgument',['../struct_system_1_1_reflection_1_1_custom_attribute_typed_argument.html',1,'System::Reflection']]],
  ['customconstantattribute',['CustomConstantAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_custom_constant_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['custompropertyimpl',['CustomPropertyImpl',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_custom_property_impl.html',1,'System::Runtime::InteropServices::WindowsRuntime']]]
];
