var searchData=
[
  ['dataerrorschangedeventargs',['DataErrorsChangedEventArgs',['../class_system_1_1_component_model_1_1_data_errors_changed_event_args.html',1,'System::ComponentModel']]],
  ['datamisalignedexception',['DataMisalignedException',['../class_system_1_1_data_misaligned_exception.html',1,'System']]],
  ['dataobjectattribute',['DataObjectAttribute',['../class_system_1_1_component_model_1_1_data_object_attribute.html',1,'System::ComponentModel']]],
  ['dataobjectfieldattribute',['DataObjectFieldAttribute',['../class_system_1_1_component_model_1_1_data_object_field_attribute.html',1,'System::ComponentModel']]],
  ['dataobjectmethodattribute',['DataObjectMethodAttribute',['../class_system_1_1_component_model_1_1_data_object_method_attribute.html',1,'System::ComponentModel']]],
  ['datareceivedeventargs',['DataReceivedEventArgs',['../class_system_1_1_diagnostics_1_1_data_received_event_args.html',1,'System::Diagnostics']]],
  ['datetime',['DateTime',['../struct_system_1_1_date_time.html',1,'System']]],
  ['datetimeconstantattribute',['DateTimeConstantAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_date_time_constant_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['datetimeconverter',['DateTimeConverter',['../class_system_1_1_component_model_1_1_date_time_converter.html',1,'System::ComponentModel']]],
  ['datetimeformatinfo',['DateTimeFormatInfo',['../class_system_1_1_globalization_1_1_date_time_format_info.html',1,'System::Globalization']]],
  ['datetimeoffset',['DateTimeOffset',['../struct_system_1_1_date_time_offset.html',1,'System']]],
  ['datetimeoffsetconverter',['DateTimeOffsetConverter',['../class_system_1_1_component_model_1_1_date_time_offset_converter.html',1,'System::ComponentModel']]],
  ['datetimeserializationsection',['DateTimeSerializationSection',['../class_system_1_1_xml_1_1_serialization_1_1_configuration_1_1_date_time_serialization_section.html',1,'System::Xml::Serialization::Configuration']]],
  ['daylighttime',['DaylightTime',['../class_system_1_1_globalization_1_1_daylight_time.html',1,'System::Globalization']]],
  ['dbnull',['DBNull',['../class_system_1_1_d_b_null.html',1,'System']]],
  ['debug',['Debug',['../class_system_1_1_diagnostics_1_1_debug.html',1,'System::Diagnostics']]],
  ['debuggableattribute',['DebuggableAttribute',['../class_system_1_1_diagnostics_1_1_debuggable_attribute.html',1,'System::Diagnostics']]],
  ['debugger',['Debugger',['../class_system_1_1_diagnostics_1_1_debugger.html',1,'System::Diagnostics']]],
  ['debuggerbrowsableattribute',['DebuggerBrowsableAttribute',['../class_system_1_1_diagnostics_1_1_debugger_browsable_attribute.html',1,'System::Diagnostics']]],
  ['debuggerdisplayattribute',['DebuggerDisplayAttribute',['../class_system_1_1_diagnostics_1_1_debugger_display_attribute.html',1,'System::Diagnostics']]],
  ['debuggerhiddenattribute',['DebuggerHiddenAttribute',['../class_system_1_1_diagnostics_1_1_debugger_hidden_attribute.html',1,'System::Diagnostics']]],
  ['debuggernonusercodeattribute',['DebuggerNonUserCodeAttribute',['../class_system_1_1_diagnostics_1_1_debugger_non_user_code_attribute.html',1,'System::Diagnostics']]],
  ['debuggerstepperboundaryattribute',['DebuggerStepperBoundaryAttribute',['../class_system_1_1_diagnostics_1_1_debugger_stepper_boundary_attribute.html',1,'System::Diagnostics']]],
  ['debuggerstepthroughattribute',['DebuggerStepThroughAttribute',['../class_system_1_1_diagnostics_1_1_debugger_step_through_attribute.html',1,'System::Diagnostics']]],
  ['debuggertypeproxyattribute',['DebuggerTypeProxyAttribute',['../class_system_1_1_diagnostics_1_1_debugger_type_proxy_attribute.html',1,'System::Diagnostics']]],
  ['debuggervisualizerattribute',['DebuggerVisualizerAttribute',['../class_system_1_1_diagnostics_1_1_debugger_visualizer_attribute.html',1,'System::Diagnostics']]],
  ['debuginfoexpression',['DebugInfoExpression',['../class_system_1_1_linq_1_1_expressions_1_1_debug_info_expression.html',1,'System::Linq::Expressions']]],
  ['debuginfogenerator',['DebugInfoGenerator',['../class_system_1_1_runtime_1_1_compiler_services_1_1_debug_info_generator.html',1,'System::Runtime::CompilerServices']]],
  ['decimal',['Decimal',['../struct_system_1_1_decimal.html',1,'System']]],
  ['decimalconstantattribute',['DecimalConstantAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_decimal_constant_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['decimalconverter',['DecimalConverter',['../class_system_1_1_component_model_1_1_decimal_converter.html',1,'System::ComponentModel']]],
  ['decoder',['Decoder',['../class_system_1_1_text_1_1_decoder.html',1,'System::Text']]],
  ['decoderexceptionfallback',['DecoderExceptionFallback',['../class_system_1_1_text_1_1_decoder_exception_fallback.html',1,'System::Text']]],
  ['decoderexceptionfallbackbuffer',['DecoderExceptionFallbackBuffer',['../class_system_1_1_text_1_1_decoder_exception_fallback_buffer.html',1,'System::Text']]],
  ['decoderfallback',['DecoderFallback',['../class_system_1_1_text_1_1_decoder_fallback.html',1,'System::Text']]],
  ['decoderfallbackbuffer',['DecoderFallbackBuffer',['../class_system_1_1_text_1_1_decoder_fallback_buffer.html',1,'System::Text']]],
  ['decoderfallbackexception',['DecoderFallbackException',['../class_system_1_1_text_1_1_decoder_fallback_exception.html',1,'System::Text']]],
  ['decoderreplacementfallback',['DecoderReplacementFallback',['../class_system_1_1_text_1_1_decoder_replacement_fallback.html',1,'System::Text']]],
  ['decoderreplacementfallbackbuffer',['DecoderReplacementFallbackBuffer',['../class_system_1_1_text_1_1_decoder_replacement_fallback_buffer.html',1,'System::Text']]],
  ['defaultbindingpropertyattribute',['DefaultBindingPropertyAttribute',['../class_system_1_1_component_model_1_1_default_binding_property_attribute.html',1,'System::ComponentModel']]],
  ['defaultcharsetattribute',['DefaultCharSetAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_default_char_set_attribute.html',1,'System::Runtime::InteropServices']]],
  ['defaultdependencyattribute',['DefaultDependencyAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_default_dependency_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['defaultdllimportsearchpathsattribute',['DefaultDllImportSearchPathsAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_default_dll_import_search_paths_attribute.html',1,'System::Runtime::InteropServices']]],
  ['defaulteventattribute',['DefaultEventAttribute',['../class_system_1_1_component_model_1_1_default_event_attribute.html',1,'System::ComponentModel']]],
  ['defaultexpression',['DefaultExpression',['../class_system_1_1_linq_1_1_expressions_1_1_default_expression.html',1,'System::Linq::Expressions']]],
  ['defaultinterfaceattribute',['DefaultInterfaceAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_default_interface_attribute.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['defaultmemberattribute',['DefaultMemberAttribute',['../class_system_1_1_reflection_1_1_default_member_attribute.html',1,'System::Reflection']]],
  ['defaultparametervalueattribute',['DefaultParameterValueAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_default_parameter_value_attribute.html',1,'System::Runtime::InteropServices']]],
  ['defaultpropertyattribute',['DefaultPropertyAttribute',['../class_system_1_1_component_model_1_1_default_property_attribute.html',1,'System::ComponentModel']]],
  ['defaultproxysection',['DefaultProxySection',['../class_system_1_1_net_1_1_configuration_1_1_default_proxy_section.html',1,'System::Net::Configuration']]],
  ['defaultserializationproviderattribute',['DefaultSerializationProviderAttribute',['../class_system_1_1_component_model_1_1_design_1_1_serialization_1_1_default_serialization_provider_attribute.html',1,'System::ComponentModel::Design::Serialization']]],
  ['defaultsettingvalueattribute',['DefaultSettingValueAttribute',['../class_system_1_1_configuration_1_1_default_setting_value_attribute.html',1,'System::Configuration']]],
  ['defaulttracelistener',['DefaultTraceListener',['../class_system_1_1_diagnostics_1_1_default_trace_listener.html',1,'System::Diagnostics']]],
  ['defaultvalueattribute',['DefaultValueAttribute',['../class_system_1_1_component_model_1_1_default_value_attribute.html',1,'System::ComponentModel']]],
  ['deflatestream',['DeflateStream',['../class_system_1_1_i_o_1_1_compression_1_1_deflate_stream.html',1,'System::IO::Compression']]],
  ['delegate',['Delegate',['../class_system_1_1_delegate.html',1,'System']]],
  ['deleteindexbinder',['DeleteIndexBinder',['../class_system_1_1_dynamic_1_1_delete_index_binder.html',1,'System::Dynamic']]],
  ['deletememberbinder',['DeleteMemberBinder',['../class_system_1_1_dynamic_1_1_delete_member_binder.html',1,'System::Dynamic']]],
  ['delimitedlisttracelistener',['DelimitedListTraceListener',['../class_system_1_1_diagnostics_1_1_delimited_list_trace_listener.html',1,'System::Diagnostics']]],
  ['dependencyattribute',['DependencyAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_dependency_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['derivebytes',['DeriveBytes',['../class_system_1_1_security_1_1_cryptography_1_1_derive_bytes.html',1,'System::Security::Cryptography']]],
  ['des',['DES',['../class_system_1_1_security_1_1_cryptography_1_1_d_e_s.html',1,'System::Security::Cryptography']]],
  ['descriptionattribute',['DescriptionAttribute',['../class_system_1_1_component_model_1_1_description_attribute.html',1,'System::ComponentModel']]],
  ['descryptoserviceprovider',['DESCryptoServiceProvider',['../class_system_1_1_security_1_1_cryptography_1_1_d_e_s_crypto_service_provider.html',1,'System::Security::Cryptography']]],
  ['descunion',['DESCUNION',['../struct_system_1_1_runtime_1_1_interop_services_1_1_e_l_e_m_d_e_s_c_1_1_d_e_s_c_u_n_i_o_n.html',1,'System.Runtime.InteropServices.ELEMDESC.DESCUNION'],['../struct_system_1_1_runtime_1_1_interop_services_1_1_v_a_r_d_e_s_c_1_1_d_e_s_c_u_n_i_o_n.html',1,'System.Runtime.InteropServices.VARDESC.DESCUNION'],['../struct_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_e_l_e_m_d_e_s_c_1_1_d_e_s_c_u_n_i_o_n.html',1,'System.Runtime.InteropServices.ComTypes.ELEMDESC.DESCUNION'],['../struct_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_v_a_r_d_e_s_c_1_1_d_e_s_c_u_n_i_o_n.html',1,'System.Runtime.InteropServices.ComTypes.VARDESC.DESCUNION']]],
  ['designerattribute',['DesignerAttribute',['../class_system_1_1_component_model_1_1_designer_attribute.html',1,'System::ComponentModel']]],
  ['designercategoryattribute',['DesignerCategoryAttribute',['../class_system_1_1_component_model_1_1_designer_category_attribute.html',1,'System::ComponentModel']]],
  ['designercollection',['DesignerCollection',['../class_system_1_1_component_model_1_1_design_1_1_designer_collection.html',1,'System::ComponentModel::Design']]],
  ['designereventargs',['DesignerEventArgs',['../class_system_1_1_component_model_1_1_design_1_1_designer_event_args.html',1,'System::ComponentModel::Design']]],
  ['designerloader',['DesignerLoader',['../class_system_1_1_component_model_1_1_design_1_1_serialization_1_1_designer_loader.html',1,'System::ComponentModel::Design::Serialization']]],
  ['designernamespaceresolveeventargs',['DesignerNamespaceResolveEventArgs',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_designer_namespace_resolve_event_args.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['designeroptioncollection',['DesignerOptionCollection',['../class_system_1_1_component_model_1_1_design_1_1_designer_option_service_1_1_designer_option_collection.html',1,'System::ComponentModel::Design::DesignerOptionService']]],
  ['designeroptionservice',['DesignerOptionService',['../class_system_1_1_component_model_1_1_design_1_1_designer_option_service.html',1,'System::ComponentModel::Design']]],
  ['designerserializationvisibilityattribute',['DesignerSerializationVisibilityAttribute',['../class_system_1_1_component_model_1_1_designer_serialization_visibility_attribute.html',1,'System::ComponentModel']]],
  ['designerserializerattribute',['DesignerSerializerAttribute',['../class_system_1_1_component_model_1_1_design_1_1_serialization_1_1_designer_serializer_attribute.html',1,'System::ComponentModel::Design::Serialization']]],
  ['designertransaction',['DesignerTransaction',['../class_system_1_1_component_model_1_1_design_1_1_designer_transaction.html',1,'System::ComponentModel::Design']]],
  ['designertransactioncloseeventargs',['DesignerTransactionCloseEventArgs',['../class_system_1_1_component_model_1_1_design_1_1_designer_transaction_close_event_args.html',1,'System::ComponentModel::Design']]],
  ['designerverb',['DesignerVerb',['../class_system_1_1_component_model_1_1_design_1_1_designer_verb.html',1,'System::ComponentModel::Design']]],
  ['designerverbcollection',['DesignerVerbCollection',['../class_system_1_1_component_model_1_1_design_1_1_designer_verb_collection.html',1,'System::ComponentModel::Design']]],
  ['designonlyattribute',['DesignOnlyAttribute',['../class_system_1_1_component_model_1_1_design_only_attribute.html',1,'System::ComponentModel']]],
  ['designtimelicensecontext',['DesigntimeLicenseContext',['../class_system_1_1_component_model_1_1_design_1_1_designtime_license_context.html',1,'System::ComponentModel::Design']]],
  ['designtimelicensecontextserializer',['DesigntimeLicenseContextSerializer',['../class_system_1_1_component_model_1_1_design_1_1_designtime_license_context_serializer.html',1,'System::ComponentModel::Design']]],
  ['designtimevisibleattribute',['DesignTimeVisibleAttribute',['../class_system_1_1_component_model_1_1_design_time_visible_attribute.html',1,'System::ComponentModel']]],
  ['diagnosticsconfigurationhandler',['DiagnosticsConfigurationHandler',['../class_system_1_1_diagnostics_1_1_diagnostics_configuration_handler.html',1,'System::Diagnostics']]],
  ['dictionary',['Dictionary',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20eventcachekey_2c_20eventcacheentry_20_3e',['Dictionary&lt; EventCacheKey, EventCacheEntry &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20iasynclocal_2c_20object_20_3e',['Dictionary&lt; IAsyncLocal, object &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20idtdentityinfo_2c_20idtdentityinfo_20_3e',['Dictionary&lt; IDtdEntityInfo, IDtdEntityInfo &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20int_2c_20channelinfo_20_3e',['Dictionary&lt; int, ChannelInfo &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20int_2c_20countertype_20_3e',['Dictionary&lt; int, CounterType &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20int_2c_20list_3c_20system_3a_3aweakreference_20_3e_20_3e',['Dictionary&lt; int, List&lt; System::WeakReference &gt; &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20int_2c_20string_20_3e',['Dictionary&lt; int, string &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20int_2c_20system_3a_3adiagnostics_3a_3aperformancedata_3a_3acounterdata_20_3e',['Dictionary&lt; int, System::Diagnostics::PerformanceData::CounterData &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20int_2c_20system_3a_3athreading_3a_3atasks_3a_3atask_20_3e',['Dictionary&lt; int, System::Threading::Tasks::Task &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20k_2c_20queue_3c_20v_20_3e_20_3e',['Dictionary&lt; K, Queue&lt; V &gt; &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20object_2c_20compilerscope_20_3e',['Dictionary&lt; object, CompilerScope &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20object_2c_20int_20_3e',['Dictionary&lt; object, int &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20providermetadataid_2c_20cacheitem_20_3e',['Dictionary&lt; ProviderMetadataId, CacheItem &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20relationshipentry_2c_20relationshipentry_20_3e',['Dictionary&lt; RelationshipEntry, RelationshipEntry &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20runtimetype_2c_20runtimetype_20_3e',['Dictionary&lt; RuntimeType, RuntimeType &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20argbuilder_20_3e',['Dictionary&lt; string, ArgBuilder &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20bool_20_3e',['Dictionary&lt; string, bool &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20char_20_3e',['Dictionary&lt; string, char &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20culturedata_20_3e',['Dictionary&lt; string, CultureData &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20fieldbuilder_20_3e',['Dictionary&lt; string, FieldBuilder &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20int_20_3e',['Dictionary&lt; string, int &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20list_3c_20int_20_3e_20_3e',['Dictionary&lt; string, List&lt; int &gt; &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20localbuilder_20_3e',['Dictionary&lt; string, LocalBuilder &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20memberinfo_20_3e',['Dictionary&lt; string, MemberInfo &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20methodbuilderinfo_20_3e',['Dictionary&lt; string, MethodBuilderInfo &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20namespacedecl_20_3e',['Dictionary&lt; string, NamespaceDecl &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20object_20_3e',['Dictionary&lt; string, object &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20object_5b_5d_3e',['Dictionary&lt; string, object[]&gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20precannedresource_20_3e',['Dictionary&lt; string, PrecannedResource &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20regex_20_3e',['Dictionary&lt; string, Regex &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20resourcelocator_20_3e',['Dictionary&lt; string, ResourceLocator &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20schemanotation_20_3e',['Dictionary&lt; string, SchemaNotation &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20schemesettinginternal_20_3e',['Dictionary&lt; string, SchemeSettingInternal &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20string_20_3e',['Dictionary&lt; string, string &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20switchvaluestate_20_3e',['Dictionary&lt; string, SwitchValueState &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20system_3a_3alocaldatastoreslot_20_3e',['Dictionary&lt; string, System::LocalDataStoreSlot &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20system_3a_3aresources_3a_3aresourceset_20_3e',['Dictionary&lt; string, System::Resources::ResourceSet &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20system_3a_3atimezoneinfo_20_3e',['Dictionary&lt; string, System::TimeZoneInfo &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20system_3a_3atype_20_3e',['Dictionary&lt; string, System::Type &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20system_3a_3auriparser_20_3e',['Dictionary&lt; string, System::UriParser &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20system_3a_3aweakreference_20_3e',['Dictionary&lt; string, System::WeakReference &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20undeclarednotation_20_3e',['Dictionary&lt; string, UndeclaredNotation &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20string_2c_20xpathnoderef_20_3e',['Dictionary&lt; string, XPathNodeRef &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20symboldocumentinfo_2c_20isymboldocumentwriter_20_3e',['Dictionary&lt; SymbolDocumentInfo, ISymbolDocumentWriter &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3aintptr_2c_20metadatareaderprovider_20_3e',['Dictionary&lt; System::IntPtr, MetadataReaderProvider &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3aintptr_2c_20system_3a_3aintptr_20_3e',['Dictionary&lt; System::IntPtr, System::IntPtr &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3alinq_3a_3aexpressions_3a_3alabeltarget_2c_20int_20_3e',['Dictionary&lt; System::Linq::Expressions::LabelTarget, int &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3alinq_3a_3aexpressions_3a_3alabeltarget_2c_20labelinfo_20_3e',['Dictionary&lt; System::Linq::Expressions::LabelTarget, LabelInfo &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3alinq_3a_3aexpressions_3a_3alambdaexpression_2c_20boundconstants_20_3e',['Dictionary&lt; System::Linq::Expressions::LambdaExpression, BoundConstants &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3alinq_3a_3aexpressions_3a_3alambdaexpression_2c_20int_20_3e',['Dictionary&lt; System::Linq::Expressions::LambdaExpression, int &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3alinq_3a_3aexpressions_3a_3aparameterexpression_2c_20int_20_3e',['Dictionary&lt; System::Linq::Expressions::ParameterExpression, int &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3alinq_3a_3aexpressions_3a_3aparameterexpression_2c_20storage_20_3e',['Dictionary&lt; System::Linq::Expressions::ParameterExpression, Storage &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3alinq_3a_3aexpressions_3a_3aparameterexpression_2c_20variablestoragekind_20_3e',['Dictionary&lt; System::Linq::Expressions::ParameterExpression, VariableStorageKind &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3aruntime_3a_3ainteropservices_3a_3awindowsruntime_3a_3aeventregistrationtoken_2c_20t_20_3e',['Dictionary&lt; System::Runtime::InteropServices::WindowsRuntime::EventRegistrationToken, T &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3atuple_3c_20system_3a_3atype_2c_20string_20_3e_2c_20queue_3c_20localbuilder_20_3e_20_3e',['Dictionary&lt; System::Tuple&lt; System::Type, string &gt;, Queue&lt; LocalBuilder &gt; &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3atype_2c_20byte_5b_5d_3e',['Dictionary&lt; System::Type, byte[]&gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3atype_2c_20evidencetypedescriptor_20_3e',['Dictionary&lt; System::Type, EvidenceTypeDescriptor &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3atype_2c_20localbuilder_20_3e',['Dictionary&lt; System::Type, LocalBuilder &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3atype_2c_20object_20_3e',['Dictionary&lt; System::Type, object &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3atype_2c_20typeinfo_20_3e',['Dictionary&lt; System::Type, TypeInfo &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3atype_2c_20typeinformation_20_3e',['Dictionary&lt; System::Type, TypeInformation &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3auri_2c_20preloadeddata_20_3e',['Dictionary&lt; System::Uri, PreloadedData &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3axml_3a_3axmlqualifiedname_2c_20int_20_3e',['Dictionary&lt; System::Xml::XmlQualifiedName, int &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3axml_3a_3axmlqualifiedname_2c_20schemaattdef_20_3e',['Dictionary&lt; System::Xml::XmlQualifiedName, SchemaAttDef &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3axml_3a_3axmlqualifiedname_2c_20schemaelementdecl_20_3e',['Dictionary&lt; System::Xml::XmlQualifiedName, SchemaElementDecl &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3axml_3a_3axmlqualifiedname_2c_20schemaentity_20_3e',['Dictionary&lt; System::Xml::XmlQualifiedName, SchemaEntity &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3axml_3a_3axmlqualifiedname_2c_20system_3a_3axml_3a_3aschema_3a_3axmlschemaobject_20_3e',['Dictionary&lt; System::Xml::XmlQualifiedName, System::Xml::Schema::XmlSchemaObject &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20system_3a_3axml_3a_3axmlqualifiedname_2c_20system_3a_3axml_3a_3axmlqualifiedname_20_3e',['Dictionary&lt; System::Xml::XmlQualifiedName, System::Xml::XmlQualifiedName &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20t_2c_20object_20_3e',['Dictionary&lt; T, object &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20tkey_2c_20titem_20_3e',['Dictionary&lt; TKey, TItem &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20type_2c_20t_20_3e',['Dictionary&lt; Type, T &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20typedconstant_2c_20int_20_3e',['Dictionary&lt; TypedConstant, int &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20typedconstant_2c_20localbuilder_20_3e',['Dictionary&lt; TypedConstant, LocalBuilder &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20ulong_2c_20string_20_3e',['Dictionary&lt; ulong, string &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20wrapper_3c_20tinputoutput_20_3e_2c_20pair_3c_20tinputoutput_2c_20tleftkey_20_3e_20_3e',['Dictionary&lt; Wrapper&lt; TInputOutput &gt;, Pair&lt; TInputOutput, TLeftKey &gt; &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20wrapper_3c_20tinputoutput_20_3e_2c_20tkey_20_3e',['Dictionary&lt; Wrapper&lt; TInputOutput &gt;, TKey &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionary_3c_20xpathnoderef_2c_20xpathnoderef_20_3e',['Dictionary&lt; XPathNodeRef, XPathNodeRef &gt;',['../class_system_1_1_collections_1_1_generic_1_1_dictionary.html',1,'System::Collections::Generic']]],
  ['dictionarybase',['DictionaryBase',['../class_system_1_1_collections_1_1_dictionary_base.html',1,'System::Collections']]],
  ['dictionaryentry',['DictionaryEntry',['../struct_system_1_1_collections_1_1_dictionary_entry.html',1,'System::Collections']]],
  ['dictionarysectionhandler',['DictionarySectionHandler',['../class_system_1_1_configuration_1_1_dictionary_section_handler.html',1,'System::Configuration']]],
  ['directory',['Directory',['../class_system_1_1_i_o_1_1_directory.html',1,'System::IO']]],
  ['directoryinfo',['DirectoryInfo',['../class_system_1_1_i_o_1_1_directory_info.html',1,'System::IO']]],
  ['directorynotfoundexception',['DirectoryNotFoundException',['../class_system_1_1_i_o_1_1_directory_not_found_exception.html',1,'System::IO']]],
  ['directoryobjectsecurity',['DirectoryObjectSecurity',['../class_system_1_1_security_1_1_access_control_1_1_directory_object_security.html',1,'System::Security::AccessControl']]],
  ['directorysecurity',['DirectorySecurity',['../class_system_1_1_security_1_1_access_control_1_1_directory_security.html',1,'System::Security::AccessControl']]],
  ['disableprivatereflectionattribute',['DisablePrivateReflectionAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_disable_private_reflection_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['discardableattribute',['DiscardableAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_discardable_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['discretionaryacl',['DiscretionaryAcl',['../class_system_1_1_security_1_1_access_control_1_1_discretionary_acl.html',1,'System::Security::AccessControl']]],
  ['dispatchwrapper',['DispatchWrapper',['../class_system_1_1_runtime_1_1_interop_services_1_1_dispatch_wrapper.html',1,'System::Runtime::InteropServices']]],
  ['dispidattribute',['DispIdAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_disp_id_attribute.html',1,'System::Runtime::InteropServices']]],
  ['displaynameattribute',['DisplayNameAttribute',['../class_system_1_1_component_model_1_1_display_name_attribute.html',1,'System::ComponentModel']]],
  ['dispositiontypenames',['DispositionTypeNames',['../class_system_1_1_net_1_1_mime_1_1_disposition_type_names.html',1,'System::Net::Mime']]],
  ['dispparams',['DISPPARAMS',['../struct_system_1_1_runtime_1_1_interop_services_1_1_d_i_s_p_p_a_r_a_m_s.html',1,'System.Runtime.InteropServices.DISPPARAMS'],['../struct_system_1_1_runtime_1_1_interop_services_1_1_com_types_1_1_d_i_s_p_p_a_r_a_m_s.html',1,'System.Runtime.InteropServices.ComTypes.DISPPARAMS']]],
  ['dividebyzeroexception',['DivideByZeroException',['../class_system_1_1_divide_by_zero_exception.html',1,'System']]],
  ['dllimportattribute',['DllImportAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_dll_import_attribute.html',1,'System::Runtime::InteropServices']]],
  ['dllnotfoundexception',['DllNotFoundException',['../class_system_1_1_dll_not_found_exception.html',1,'System']]],
  ['dns',['Dns',['../class_system_1_1_net_1_1_dns.html',1,'System::Net']]],
  ['dnsendpoint',['DnsEndPoint',['../class_system_1_1_net_1_1_dns_end_point.html',1,'System::Net']]],
  ['dnspermission',['DnsPermission',['../class_system_1_1_net_1_1_dns_permission.html',1,'System::Net']]],
  ['dnspermissionattribute',['DnsPermissionAttribute',['../class_system_1_1_net_1_1_dns_permission_attribute.html',1,'System::Net']]],
  ['double',['Double',['../struct_system_1_1_double.html',1,'System']]],
  ['doubleconverter',['DoubleConverter',['../class_system_1_1_component_model_1_1_double_converter.html',1,'System::ComponentModel']]],
  ['downloaddatacompletedeventargs',['DownloadDataCompletedEventArgs',['../class_system_1_1_net_1_1_download_data_completed_event_args.html',1,'System::Net']]],
  ['downloadprogresschangedeventargs',['DownloadProgressChangedEventArgs',['../class_system_1_1_net_1_1_download_progress_changed_event_args.html',1,'System::Net']]],
  ['downloadstringcompletedeventargs',['DownloadStringCompletedEventArgs',['../class_system_1_1_net_1_1_download_string_completed_event_args.html',1,'System::Net']]],
  ['doworkeventargs',['DoWorkEventArgs',['../class_system_1_1_component_model_1_1_do_work_event_args.html',1,'System::ComponentModel']]],
  ['driveinfo',['DriveInfo',['../class_system_1_1_i_o_1_1_drive_info.html',1,'System::IO']]],
  ['drivenotfoundexception',['DriveNotFoundException',['../class_system_1_1_i_o_1_1_drive_not_found_exception.html',1,'System::IO']]],
  ['dsa',['DSA',['../class_system_1_1_security_1_1_cryptography_1_1_d_s_a.html',1,'System::Security::Cryptography']]],
  ['dsacertificateextensions',['DSACertificateExtensions',['../class_system_1_1_security_1_1_cryptography_1_1_x509_certificates_1_1_d_s_a_certificate_extensions.html',1,'System::Security::Cryptography::X509Certificates']]],
  ['dsacng',['DSACng',['../class_system_1_1_security_1_1_cryptography_1_1_d_s_a_cng.html',1,'System::Security::Cryptography']]],
  ['dsacryptoserviceprovider',['DSACryptoServiceProvider',['../class_system_1_1_security_1_1_cryptography_1_1_d_s_a_crypto_service_provider.html',1,'System::Security::Cryptography']]],
  ['dsaparameters',['DSAParameters',['../struct_system_1_1_security_1_1_cryptography_1_1_d_s_a_parameters.html',1,'System::Security::Cryptography']]],
  ['dsasignaturedeformatter',['DSASignatureDeformatter',['../class_system_1_1_security_1_1_cryptography_1_1_d_s_a_signature_deformatter.html',1,'System::Security::Cryptography']]],
  ['dsasignatureformatter',['DSASignatureFormatter',['../class_system_1_1_security_1_1_cryptography_1_1_d_s_a_signature_formatter.html',1,'System::Security::Cryptography']]],
  ['duplicatewaitobjectexception',['DuplicateWaitObjectException',['../class_system_1_1_duplicate_wait_object_exception.html',1,'System']]],
  ['dynamicattribute',['DynamicAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_dynamic_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['dynamicexpression',['DynamicExpression',['../class_system_1_1_linq_1_1_expressions_1_1_dynamic_expression.html',1,'System::Linq::Expressions']]],
  ['dynamicexpressionvisitor',['DynamicExpressionVisitor',['../class_system_1_1_linq_1_1_expressions_1_1_dynamic_expression_visitor.html',1,'System::Linq::Expressions']]],
  ['dynamicilinfo',['DynamicILInfo',['../class_system_1_1_reflection_1_1_emit_1_1_dynamic_i_l_info.html',1,'System::Reflection::Emit']]],
  ['dynamicmetaobject',['DynamicMetaObject',['../class_system_1_1_dynamic_1_1_dynamic_meta_object.html',1,'System::Dynamic']]],
  ['dynamicmetaobjectbinder',['DynamicMetaObjectBinder',['../class_system_1_1_dynamic_1_1_dynamic_meta_object_binder.html',1,'System::Dynamic']]],
  ['dynamicmethod',['DynamicMethod',['../class_system_1_1_reflection_1_1_emit_1_1_dynamic_method.html',1,'System::Reflection::Emit']]],
  ['dynamicobject',['DynamicObject',['../class_system_1_1_dynamic_1_1_dynamic_object.html',1,'System::Dynamic']]],
  ['dynamicroleclaimprovider',['DynamicRoleClaimProvider',['../class_system_1_1_security_1_1_claims_1_1_dynamic_role_claim_provider.html',1,'System::Security::Claims']]]
];
