var searchData=
[
  ['random',['Random',['../class_system_1_1_random.html',1,'System']]],
  ['randomnumbergenerator',['RandomNumberGenerator',['../class_system_1_1_security_1_1_cryptography_1_1_random_number_generator.html',1,'System::Security::Cryptography']]],
  ['rankexception',['RankException',['../class_system_1_1_rank_exception.html',1,'System']]],
  ['rawacl',['RawAcl',['../class_system_1_1_security_1_1_access_control_1_1_raw_acl.html',1,'System::Security::AccessControl']]],
  ['rawsecuritydescriptor',['RawSecurityDescriptor',['../class_system_1_1_security_1_1_access_control_1_1_raw_security_descriptor.html',1,'System::Security::AccessControl']]],
  ['rc2',['RC2',['../class_system_1_1_security_1_1_cryptography_1_1_r_c2.html',1,'System::Security::Cryptography']]],
  ['rc2cryptoserviceprovider',['RC2CryptoServiceProvider',['../class_system_1_1_security_1_1_cryptography_1_1_r_c2_crypto_service_provider.html',1,'System::Security::Cryptography']]],
  ['readerwriterlock',['ReaderWriterLock',['../class_system_1_1_threading_1_1_reader_writer_lock.html',1,'System::Threading']]],
  ['readerwriterlockslim',['ReaderWriterLockSlim',['../class_system_1_1_threading_1_1_reader_writer_lock_slim.html',1,'System::Threading']]],
  ['readonlyarrayattribute',['ReadOnlyArrayAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_read_only_array_attribute.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['readonlyattribute',['ReadOnlyAttribute',['../class_system_1_1_component_model_1_1_read_only_attribute.html',1,'System::ComponentModel']]],
  ['readonlycollection',['ReadOnlyCollection',['../class_system_1_1_collections_1_1_object_model_1_1_read_only_collection.html',1,'System::Collections::ObjectModel']]],
  ['readonlycollection_3c_20manifestsignatureinformation_20_3e',['ReadOnlyCollection&lt; ManifestSignatureInformation &gt;',['../class_system_1_1_collections_1_1_object_model_1_1_read_only_collection.html',1,'System::Collections::ObjectModel']]],
  ['readonlycollection_3c_20memberinfo_20_3e',['ReadOnlyCollection&lt; MemberInfo &gt;',['../class_system_1_1_collections_1_1_object_model_1_1_read_only_collection.html',1,'System::Collections::ObjectModel']]],
  ['readonlycollection_3c_20parameterexpression_20_3e',['ReadOnlyCollection&lt; ParameterExpression &gt;',['../class_system_1_1_collections_1_1_object_model_1_1_read_only_collection.html',1,'System::Collections::ObjectModel']]],
  ['readonlycollection_3c_20string_20_3e',['ReadOnlyCollection&lt; string &gt;',['../class_system_1_1_collections_1_1_object_model_1_1_read_only_collection.html',1,'System::Collections::ObjectModel']]],
  ['readonlycollection_3c_20system_3a_3aexception_20_3e',['ReadOnlyCollection&lt; System::Exception &gt;',['../class_system_1_1_collections_1_1_object_model_1_1_read_only_collection.html',1,'System::Collections::ObjectModel']]],
  ['readonlycollection_3c_20system_3a_3alinq_3a_3aexpressions_3a_3acatchblock_20_3e',['ReadOnlyCollection&lt; System::Linq::Expressions::CatchBlock &gt;',['../class_system_1_1_collections_1_1_object_model_1_1_read_only_collection.html',1,'System::Collections::ObjectModel']]],
  ['readonlycollection_3c_20system_3a_3alinq_3a_3aexpressions_3a_3aelementinit_20_3e',['ReadOnlyCollection&lt; System::Linq::Expressions::ElementInit &gt;',['../class_system_1_1_collections_1_1_object_model_1_1_read_only_collection.html',1,'System::Collections::ObjectModel']]],
  ['readonlycollection_3c_20system_3a_3alinq_3a_3aexpressions_3a_3aexpression_20_3e',['ReadOnlyCollection&lt; System::Linq::Expressions::Expression &gt;',['../class_system_1_1_collections_1_1_object_model_1_1_read_only_collection.html',1,'System::Collections::ObjectModel']]],
  ['readonlycollection_3c_20system_3a_3alinq_3a_3aexpressions_3a_3amemberbinding_20_3e',['ReadOnlyCollection&lt; System::Linq::Expressions::MemberBinding &gt;',['../class_system_1_1_collections_1_1_object_model_1_1_read_only_collection.html',1,'System::Collections::ObjectModel']]],
  ['readonlycollection_3c_20system_3a_3alinq_3a_3aexpressions_3a_3aparameterexpression_20_3e',['ReadOnlyCollection&lt; System::Linq::Expressions::ParameterExpression &gt;',['../class_system_1_1_collections_1_1_object_model_1_1_read_only_collection.html',1,'System::Collections::ObjectModel']]],
  ['readonlycollection_3c_20system_3a_3alinq_3a_3aexpressions_3a_3aswitchcase_20_3e',['ReadOnlyCollection&lt; System::Linq::Expressions::SwitchCase &gt;',['../class_system_1_1_collections_1_1_object_model_1_1_read_only_collection.html',1,'System::Collections::ObjectModel']]],
  ['readonlycollection_3c_20system_3a_3atimezoneinfo_20_3e',['ReadOnlyCollection&lt; System::TimeZoneInfo &gt;',['../class_system_1_1_collections_1_1_object_model_1_1_read_only_collection.html',1,'System::Collections::ObjectModel']]],
  ['readonlycollectionbase',['ReadOnlyCollectionBase',['../class_system_1_1_collections_1_1_read_only_collection_base.html',1,'System::Collections']]],
  ['readonlycollectionbuilder',['ReadOnlyCollectionBuilder',['../class_system_1_1_runtime_1_1_compiler_services_1_1_read_only_collection_builder.html',1,'System::Runtime::CompilerServices']]],
  ['readonlydictionary',['ReadOnlyDictionary',['../class_system_1_1_collections_1_1_object_model_1_1_read_only_dictionary.html',1,'System::Collections::ObjectModel']]],
  ['readonlydictionary_3c_20system_3a_3alinq_3a_3aexpressions_3a_3aexpression_2c_20int_20_3e',['ReadOnlyDictionary&lt; System::Linq::Expressions::Expression, int &gt;',['../class_system_1_1_collections_1_1_object_model_1_1_read_only_dictionary.html',1,'System::Collections::ObjectModel']]],
  ['readonlyobservablecollection',['ReadOnlyObservableCollection',['../class_system_1_1_collections_1_1_object_model_1_1_read_only_observable_collection.html',1,'System::Collections::ObjectModel']]],
  ['readonlypermissionset',['ReadOnlyPermissionSet',['../class_system_1_1_security_1_1_read_only_permission_set.html',1,'System::Security']]],
  ['realproxy',['RealProxy',['../class_system_1_1_runtime_1_1_remoting_1_1_proxies_1_1_real_proxy.html',1,'System::Runtime::Remoting::Proxies']]],
  ['recommendedasconfigurableattribute',['RecommendedAsConfigurableAttribute',['../class_system_1_1_component_model_1_1_recommended_as_configurable_attribute.html',1,'System::ComponentModel']]],
  ['referenceassemblyattribute',['ReferenceAssemblyAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_reference_assembly_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['referenceconverter',['ReferenceConverter',['../class_system_1_1_component_model_1_1_reference_converter.html',1,'System::ComponentModel']]],
  ['reflectioncontext',['ReflectionContext',['../class_system_1_1_reflection_1_1_reflection_context.html',1,'System::Reflection']]],
  ['reflectionpermission',['ReflectionPermission',['../class_system_1_1_security_1_1_permissions_1_1_reflection_permission.html',1,'System::Security::Permissions']]],
  ['reflectionpermissionattribute',['ReflectionPermissionAttribute',['../class_system_1_1_security_1_1_permissions_1_1_reflection_permission_attribute.html',1,'System::Security::Permissions']]],
  ['reflectiontypeloadexception',['ReflectionTypeLoadException',['../class_system_1_1_reflection_1_1_reflection_type_load_exception.html',1,'System::Reflection']]],
  ['refresheventargs',['RefreshEventArgs',['../class_system_1_1_component_model_1_1_refresh_event_args.html',1,'System::ComponentModel']]],
  ['refreshpropertiesattribute',['RefreshPropertiesAttribute',['../class_system_1_1_component_model_1_1_refresh_properties_attribute.html',1,'System::ComponentModel']]],
  ['regex',['Regex',['../class_system_1_1_text_1_1_regular_expressions_1_1_regex.html',1,'System::Text::RegularExpressions']]],
  ['regexcompilationinfo',['RegexCompilationInfo',['../class_system_1_1_text_1_1_regular_expressions_1_1_regex_compilation_info.html',1,'System::Text::RegularExpressions']]],
  ['regexmatchtimeoutexception',['RegexMatchTimeoutException',['../class_system_1_1_text_1_1_regular_expressions_1_1_regex_match_timeout_exception.html',1,'System::Text::RegularExpressions']]],
  ['regexrunner',['RegexRunner',['../class_system_1_1_text_1_1_regular_expressions_1_1_regex_runner.html',1,'System::Text::RegularExpressions']]],
  ['regexrunnerfactory',['RegexRunnerFactory',['../class_system_1_1_text_1_1_regular_expressions_1_1_regex_runner_factory.html',1,'System::Text::RegularExpressions']]],
  ['regioninfo',['RegionInfo',['../class_system_1_1_globalization_1_1_region_info.html',1,'System::Globalization']]],
  ['registeredwaithandle',['RegisteredWaitHandle',['../class_system_1_1_threading_1_1_registered_wait_handle.html',1,'System::Threading']]],
  ['registrationservices',['RegistrationServices',['../class_system_1_1_runtime_1_1_interop_services_1_1_registration_services.html',1,'System::Runtime::InteropServices']]],
  ['registryaccessrule',['RegistryAccessRule',['../class_system_1_1_security_1_1_access_control_1_1_registry_access_rule.html',1,'System::Security::AccessControl']]],
  ['registryauditrule',['RegistryAuditRule',['../class_system_1_1_security_1_1_access_control_1_1_registry_audit_rule.html',1,'System::Security::AccessControl']]],
  ['registrypermission',['RegistryPermission',['../class_system_1_1_security_1_1_permissions_1_1_registry_permission.html',1,'System::Security::Permissions']]],
  ['registrypermissionattribute',['RegistryPermissionAttribute',['../class_system_1_1_security_1_1_permissions_1_1_registry_permission_attribute.html',1,'System::Security::Permissions']]],
  ['registrysecurity',['RegistrySecurity',['../class_system_1_1_security_1_1_access_control_1_1_registry_security.html',1,'System::Security::AccessControl']]],
  ['reliabilitycontractattribute',['ReliabilityContractAttribute',['../class_system_1_1_runtime_1_1_constrained_execution_1_1_reliability_contract_attribute.html',1,'System::Runtime::ConstrainedExecution']]],
  ['remotingconfiguration',['RemotingConfiguration',['../class_system_1_1_runtime_1_1_remoting_1_1_remoting_configuration.html',1,'System::Runtime::Remoting']]],
  ['remotingexception',['RemotingException',['../class_system_1_1_runtime_1_1_remoting_1_1_remoting_exception.html',1,'System::Runtime::Remoting']]],
  ['remotingservices',['RemotingServices',['../class_system_1_1_runtime_1_1_remoting_1_1_remoting_services.html',1,'System::Runtime::Remoting']]],
  ['remotingsurrogateselector',['RemotingSurrogateSelector',['../class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_remoting_surrogate_selector.html',1,'System::Runtime::Remoting::Messaging']]],
  ['remotingtimeoutexception',['RemotingTimeoutException',['../class_system_1_1_runtime_1_1_remoting_1_1_remoting_timeout_exception.html',1,'System::Runtime::Remoting']]],
  ['renamedeventargs',['RenamedEventArgs',['../class_system_1_1_i_o_1_1_renamed_event_args.html',1,'System::IO']]],
  ['requestcachepolicy',['RequestCachePolicy',['../class_system_1_1_net_1_1_cache_1_1_request_cache_policy.html',1,'System::Net::Cache']]],
  ['requestcachingsection',['RequestCachingSection',['../class_system_1_1_net_1_1_configuration_1_1_request_caching_section.html',1,'System::Net::Configuration']]],
  ['requiredattributeattribute',['RequiredAttributeAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_required_attribute_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['resolveeventargs',['ResolveEventArgs',['../class_system_1_1_resolve_event_args.html',1,'System']]],
  ['resolvenameeventargs',['ResolveNameEventArgs',['../class_system_1_1_component_model_1_1_design_1_1_serialization_1_1_resolve_name_event_args.html',1,'System::ComponentModel::Design::Serialization']]],
  ['resourceconsumptionattribute',['ResourceConsumptionAttribute',['../class_system_1_1_runtime_1_1_versioning_1_1_resource_consumption_attribute.html',1,'System::Runtime::Versioning']]],
  ['resourceexposureattribute',['ResourceExposureAttribute',['../class_system_1_1_runtime_1_1_versioning_1_1_resource_exposure_attribute.html',1,'System::Runtime::Versioning']]],
  ['resourcemanager',['ResourceManager',['../class_system_1_1_resources_1_1_resource_manager.html',1,'System::Resources']]],
  ['resourcepermissionbase',['ResourcePermissionBase',['../class_system_1_1_security_1_1_permissions_1_1_resource_permission_base.html',1,'System::Security::Permissions']]],
  ['resourcepermissionbaseentry',['ResourcePermissionBaseEntry',['../class_system_1_1_security_1_1_permissions_1_1_resource_permission_base_entry.html',1,'System::Security::Permissions']]],
  ['resourcereader',['ResourceReader',['../class_system_1_1_resources_1_1_resource_reader.html',1,'System::Resources']]],
  ['resourceset',['ResourceSet',['../class_system_1_1_resources_1_1_resource_set.html',1,'System::Resources']]],
  ['resourcewriter',['ResourceWriter',['../class_system_1_1_resources_1_1_resource_writer.html',1,'System::Resources']]],
  ['returnmessage',['ReturnMessage',['../class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_return_message.html',1,'System::Runtime::Remoting::Messaging']]],
  ['returnvaluenameattribute',['ReturnValueNameAttribute',['../class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_return_value_name_attribute.html',1,'System::Runtime::InteropServices::WindowsRuntime']]],
  ['rfc2898derivebytes',['Rfc2898DeriveBytes',['../class_system_1_1_security_1_1_cryptography_1_1_rfc2898_derive_bytes.html',1,'System::Security::Cryptography']]],
  ['rijndael',['Rijndael',['../class_system_1_1_security_1_1_cryptography_1_1_rijndael.html',1,'System::Security::Cryptography']]],
  ['rijndaelmanaged',['RijndaelManaged',['../class_system_1_1_security_1_1_cryptography_1_1_rijndael_managed.html',1,'System::Security::Cryptography']]],
  ['rijndaelmanagedtransform',['RijndaelManagedTransform',['../class_system_1_1_security_1_1_cryptography_1_1_rijndael_managed_transform.html',1,'System::Security::Cryptography']]],
  ['ripemd160',['RIPEMD160',['../class_system_1_1_security_1_1_cryptography_1_1_r_i_p_e_m_d160.html',1,'System::Security::Cryptography']]],
  ['ripemd160managed',['RIPEMD160Managed',['../class_system_1_1_security_1_1_cryptography_1_1_r_i_p_e_m_d160_managed.html',1,'System::Security::Cryptography']]],
  ['rngcryptoserviceprovider',['RNGCryptoServiceProvider',['../class_system_1_1_security_1_1_cryptography_1_1_r_n_g_crypto_service_provider.html',1,'System::Security::Cryptography']]],
  ['rootdesignerserializerattribute',['RootDesignerSerializerAttribute',['../class_system_1_1_component_model_1_1_design_1_1_serialization_1_1_root_designer_serializer_attribute.html',1,'System::ComponentModel::Design::Serialization']]],
  ['rootedpathvalidator',['RootedPathValidator',['../class_system_1_1_xml_1_1_serialization_1_1_configuration_1_1_rooted_path_validator.html',1,'System::Xml::Serialization::Configuration']]],
  ['rsa',['RSA',['../class_system_1_1_security_1_1_cryptography_1_1_r_s_a.html',1,'System::Security::Cryptography']]],
  ['rsacertificateextensions',['RSACertificateExtensions',['../class_system_1_1_security_1_1_cryptography_1_1_x509_certificates_1_1_r_s_a_certificate_extensions.html',1,'System::Security::Cryptography::X509Certificates']]],
  ['rsacng',['RSACng',['../class_system_1_1_security_1_1_cryptography_1_1_r_s_a_cng.html',1,'System::Security::Cryptography']]],
  ['rsacryptoserviceprovider',['RSACryptoServiceProvider',['../class_system_1_1_security_1_1_cryptography_1_1_r_s_a_crypto_service_provider.html',1,'System::Security::Cryptography']]],
  ['rsaencryptionpadding',['RSAEncryptionPadding',['../class_system_1_1_security_1_1_cryptography_1_1_r_s_a_encryption_padding.html',1,'System::Security::Cryptography']]],
  ['rsaoaepkeyexchangedeformatter',['RSAOAEPKeyExchangeDeformatter',['../class_system_1_1_security_1_1_cryptography_1_1_r_s_a_o_a_e_p_key_exchange_deformatter.html',1,'System::Security::Cryptography']]],
  ['rsaoaepkeyexchangeformatter',['RSAOAEPKeyExchangeFormatter',['../class_system_1_1_security_1_1_cryptography_1_1_r_s_a_o_a_e_p_key_exchange_formatter.html',1,'System::Security::Cryptography']]],
  ['rsaparameters',['RSAParameters',['../struct_system_1_1_security_1_1_cryptography_1_1_r_s_a_parameters.html',1,'System::Security::Cryptography']]],
  ['rsapkcs1keyexchangedeformatter',['RSAPKCS1KeyExchangeDeformatter',['../class_system_1_1_security_1_1_cryptography_1_1_r_s_a_p_k_c_s1_key_exchange_deformatter.html',1,'System::Security::Cryptography']]],
  ['rsapkcs1keyexchangeformatter',['RSAPKCS1KeyExchangeFormatter',['../class_system_1_1_security_1_1_cryptography_1_1_r_s_a_p_k_c_s1_key_exchange_formatter.html',1,'System::Security::Cryptography']]],
  ['rsapkcs1signaturedeformatter',['RSAPKCS1SignatureDeformatter',['../class_system_1_1_security_1_1_cryptography_1_1_r_s_a_p_k_c_s1_signature_deformatter.html',1,'System::Security::Cryptography']]],
  ['rsapkcs1signatureformatter',['RSAPKCS1SignatureFormatter',['../class_system_1_1_security_1_1_cryptography_1_1_r_s_a_p_k_c_s1_signature_formatter.html',1,'System::Security::Cryptography']]],
  ['rsasignaturepadding',['RSASignaturePadding',['../class_system_1_1_security_1_1_cryptography_1_1_r_s_a_signature_padding.html',1,'System::Security::Cryptography']]],
  ['rulecache',['RuleCache',['../class_system_1_1_runtime_1_1_compiler_services_1_1_rule_cache.html',1,'System::Runtime::CompilerServices']]],
  ['runinstallerattribute',['RunInstallerAttribute',['../class_system_1_1_component_model_1_1_run_installer_attribute.html',1,'System::ComponentModel']]],
  ['runtimeargumenthandle',['RuntimeArgumentHandle',['../struct_system_1_1_runtime_argument_handle.html',1,'System']]],
  ['runtimecompatibilityattribute',['RuntimeCompatibilityAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_runtime_compatibility_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['runtimeenvironment',['RuntimeEnvironment',['../class_system_1_1_runtime_1_1_interop_services_1_1_runtime_environment.html',1,'System::Runtime::InteropServices']]],
  ['runtimefeature',['RuntimeFeature',['../class_system_1_1_runtime_1_1_compiler_services_1_1_runtime_feature.html',1,'System::Runtime::CompilerServices']]],
  ['runtimefieldhandle',['RuntimeFieldHandle',['../struct_system_1_1_runtime_field_handle.html',1,'System']]],
  ['runtimehelpers',['RuntimeHelpers',['../class_system_1_1_runtime_1_1_compiler_services_1_1_runtime_helpers.html',1,'System::Runtime::CompilerServices']]],
  ['runtimeinformation',['RuntimeInformation',['../class_system_1_1_runtime_1_1_interop_services_1_1_runtime_information.html',1,'System::Runtime::InteropServices']]],
  ['runtimemethodhandle',['RuntimeMethodHandle',['../struct_system_1_1_runtime_method_handle.html',1,'System']]],
  ['runtimeops',['RuntimeOps',['../class_system_1_1_runtime_1_1_compiler_services_1_1_runtime_ops.html',1,'System::Runtime::CompilerServices']]],
  ['runtimereflectionextensions',['RuntimeReflectionExtensions',['../class_system_1_1_reflection_1_1_runtime_reflection_extensions.html',1,'System::Reflection']]],
  ['runtimetypehandle',['RuntimeTypeHandle',['../struct_system_1_1_runtime_type_handle.html',1,'System']]],
  ['runtimevariablesexpression',['RuntimeVariablesExpression',['../class_system_1_1_linq_1_1_expressions_1_1_runtime_variables_expression.html',1,'System::Linq::Expressions']]],
  ['runtimewrappedexception',['RuntimeWrappedException',['../class_system_1_1_runtime_1_1_compiler_services_1_1_runtime_wrapped_exception.html',1,'System::Runtime::CompilerServices']]],
  ['runworkercompletedeventargs',['RunWorkerCompletedEventArgs',['../class_system_1_1_component_model_1_1_run_worker_completed_event_args.html',1,'System::ComponentModel']]]
];
