var dir_7a8aa85ca50f1e5cbbf6f51739e61869 =
[
    [ "ISoapXsd.cs", "_i_soap_xsd_8cs_source.html", null ],
    [ "SoapAnyUri.cs", "_soap_any_uri_8cs_source.html", null ],
    [ "SoapBase64Binary.cs", "_soap_base64_binary_8cs_source.html", null ],
    [ "SoapDate.cs", "_soap_date_8cs_source.html", null ],
    [ "SoapDateTime.cs", "_soap_date_time_8cs_source.html", null ],
    [ "SoapDay.cs", "_soap_day_8cs_source.html", null ],
    [ "SoapDuration.cs", "_soap_duration_8cs_source.html", null ],
    [ "SoapEntities.cs", "_soap_entities_8cs_source.html", null ],
    [ "SoapEntity.cs", "_soap_entity_8cs_source.html", null ],
    [ "SoapHexBinary.cs", "_soap_hex_binary_8cs_source.html", null ],
    [ "SoapId.cs", "_soap_id_8cs_source.html", null ],
    [ "SoapIdref.cs", "_soap_idref_8cs_source.html", null ],
    [ "SoapIdrefs.cs", "_soap_idrefs_8cs_source.html", null ],
    [ "SoapInteger.cs", "_soap_integer_8cs_source.html", null ],
    [ "SoapLanguage.cs", "_soap_language_8cs_source.html", null ],
    [ "SoapMonth.cs", "_soap_month_8cs_source.html", null ],
    [ "SoapMonthDay.cs", "_soap_month_day_8cs_source.html", null ],
    [ "SoapName.cs", "_soap_name_8cs_source.html", null ],
    [ "SoapNcName.cs", "_soap_nc_name_8cs_source.html", null ],
    [ "SoapNegativeInteger.cs", "_soap_negative_integer_8cs_source.html", null ],
    [ "SoapNmtoken.cs", "_soap_nmtoken_8cs_source.html", null ],
    [ "SoapNmtokens.cs", "_soap_nmtokens_8cs_source.html", null ],
    [ "SoapNonNegativeInteger.cs", "_soap_non_negative_integer_8cs_source.html", null ],
    [ "SoapNonPositiveInteger.cs", "_soap_non_positive_integer_8cs_source.html", null ],
    [ "SoapNormalizedString.cs", "_soap_normalized_string_8cs_source.html", null ],
    [ "SoapNotation.cs", "_soap_notation_8cs_source.html", null ],
    [ "SoapPositiveInteger.cs", "_soap_positive_integer_8cs_source.html", null ],
    [ "SoapQName.cs", "_soap_q_name_8cs_source.html", null ],
    [ "SoapTime.cs", "_soap_time_8cs_source.html", null ],
    [ "SoapToken.cs", "_soap_token_8cs_source.html", null ],
    [ "SoapType.cs", "_soap_type_8cs_source.html", null ],
    [ "SoapYear.cs", "_soap_year_8cs_source.html", null ],
    [ "SoapYearMonth.cs", "_soap_year_month_8cs_source.html", null ]
];