var dir_d57dcf0596c8edb7e8462966fa30a31e =
[
    [ "BlockType.cs", "_block_type_8cs_source.html", null ],
    [ "CompressionLevel.cs", "_compression_level_8cs_source.html", null ],
    [ "CompressionMode.cs", "_compression_mode_8cs_source.html", null ],
    [ "CompressionTracingSwitch.cs", "_compression_tracing_switch_8cs_source.html", null ],
    [ "CompressionTracingSwitchLevel.cs", "_compression_tracing_switch_level_8cs_source.html", null ],
    [ "CopyEncoder.cs", "_copy_encoder_8cs_source.html", null ],
    [ "Crc32Helper.cs", "_crc32_helper_8cs_source.html", null ],
    [ "DeflateInput.cs", "_deflate_input_8cs_source.html", null ],
    [ "DeflaterManaged.cs", "_deflater_managed_8cs_source.html", null ],
    [ "DeflaterZLib.cs", "_deflater_z_lib_8cs_source.html", null ],
    [ "DeflateStream.cs", "_deflate_stream_8cs_source.html", null ],
    [ "DeflateStreamAsyncResult.cs", "_deflate_stream_async_result_8cs_source.html", null ],
    [ "FastEncoder.cs", "_fast_encoder_8cs_source.html", null ],
    [ "FastEncoderStatics.cs", "_fast_encoder_statics_8cs_source.html", null ],
    [ "FastEncoderWindow.cs", "_fast_encoder_window_8cs_source.html", null ],
    [ "GZipConstants.cs", "_g_zip_constants_8cs_source.html", null ],
    [ "GZipDecoder.cs", "_g_zip_decoder_8cs_source.html", null ],
    [ "GZipFormatter.cs", "_g_zip_formatter_8cs_source.html", null ],
    [ "GZipStream.cs", "_g_zip_stream_8cs_source.html", null ],
    [ "HuffmanTree.cs", "_huffman_tree_8cs_source.html", null ],
    [ "IDeflater.cs", "_i_deflater_8cs_source.html", null ],
    [ "IFileFormatReader.cs", "_i_file_format_reader_8cs_source.html", null ],
    [ "IFileFormatWriter.cs", "_i_file_format_writer_8cs_source.html", null ],
    [ "Inflater.cs", "_inflater_8cs_source.html", null ],
    [ "InflaterState.cs", "_inflater_state_8cs_source.html", null ],
    [ "InputBuffer.cs", "_input_buffer_8cs_source.html", null ],
    [ "Match.cs", "_system_8_i_o_8_compression_2_match_8cs_source.html", null ],
    [ "OutputBuffer.cs", "_output_buffer_8cs_source.html", null ],
    [ "OutputWindow.cs", "_output_window_8cs_source.html", null ],
    [ "ZLibException.cs", "_z_lib_exception_8cs_source.html", null ],
    [ "ZLibNative.cs", "_z_lib_native_8cs_source.html", null ]
];