var dir_5f8ec8ebacc15497fb4db9515cdd01d8 =
[
    [ "ArrayList.cs", "_array_list_8cs_source.html", null ],
    [ "BitArray.cs", "_bit_array_8cs_source.html", null ],
    [ "CaseInsensitiveComparer.cs", "_case_insensitive_comparer_8cs_source.html", null ],
    [ "CaseInsensitiveHashCodeProvider.cs", "_case_insensitive_hash_code_provider_8cs_source.html", null ],
    [ "CollectionBase.cs", "_collection_base_8cs_source.html", null ],
    [ "Comparer.cs", "_system_8_collections_2_comparer_8cs_source.html", null ],
    [ "CompatibleComparer.cs", "_compatible_comparer_8cs_source.html", null ],
    [ "DictionaryBase.cs", "_dictionary_base_8cs_source.html", null ],
    [ "DictionaryEntry.cs", "_dictionary_entry_8cs_source.html", null ],
    [ "EmptyReadOnlyDictionaryInternal.cs", "_empty_read_only_dictionary_internal_8cs_source.html", null ],
    [ "HashHelpers.cs", "_system_8_collections_2_hash_helpers_8cs_source.html", null ],
    [ "Hashtable.cs", "_hashtable_8cs_source.html", null ],
    [ "ICollection.cs", "_i_collection_8cs_source.html", null ],
    [ "IComparer.cs", "_i_comparer_8cs_source.html", null ],
    [ "IDictionary.cs", "_i_dictionary_8cs_source.html", null ],
    [ "IDictionaryEnumerator.cs", "_i_dictionary_enumerator_8cs_source.html", null ],
    [ "IEnumerable.cs", "_system_8_collections_2_i_enumerable_8cs_source.html", null ],
    [ "IEnumerator.cs", "_system_8_collections_2_i_enumerator_8cs_source.html", null ],
    [ "IEqualityComparer.cs", "_i_equality_comparer_8cs_source.html", null ],
    [ "IHashCodeProvider.cs", "_i_hash_code_provider_8cs_source.html", null ],
    [ "IList.cs", "_i_list_8cs_source.html", null ],
    [ "IStructuralComparable.cs", "_i_structural_comparable_8cs_source.html", null ],
    [ "IStructuralEquatable.cs", "_i_structural_equatable_8cs_source.html", null ],
    [ "KeyValuePairs.cs", "_key_value_pairs_8cs_source.html", null ],
    [ "ListDictionaryInternal.cs", "_list_dictionary_internal_8cs_source.html", null ],
    [ "Queue.cs", "_queue_8cs_source.html", null ],
    [ "ReadOnlyCollectionBase.cs", "_read_only_collection_base_8cs_source.html", null ],
    [ "SortedList.cs", "_sorted_list_8cs_source.html", null ],
    [ "Stack.cs", "_stack_8cs_source.html", null ],
    [ "StructuralComparer.cs", "_structural_comparer_8cs_source.html", null ],
    [ "StructuralComparisons.cs", "_structural_comparisons_8cs_source.html", null ],
    [ "StructuralEqualityComparer.cs", "_structural_equality_comparer_8cs_source.html", null ]
];