var dir_80ff8fa5c1179e3f6829a56a22e44655 =
[
    [ "GenericIdentity.cs", "_generic_identity_8cs_source.html", null ],
    [ "GenericPrincipal.cs", "_generic_principal_8cs_source.html", null ],
    [ "IdentifierAuthority.cs", "_identifier_authority_8cs_source.html", null ],
    [ "IdentityNotMappedException.cs", "_identity_not_mapped_exception_8cs_source.html", null ],
    [ "IdentityReference.cs", "_identity_reference_8cs_source.html", null ],
    [ "IdentityReferenceCollection.cs", "_identity_reference_collection_8cs_source.html", null ],
    [ "IdentityReferenceEnumerator.cs", "_identity_reference_enumerator_8cs_source.html", null ],
    [ "IIdentity.cs", "_i_identity_8cs_source.html", null ],
    [ "ImpersonationQueryResult.cs", "_impersonation_query_result_8cs_source.html", null ],
    [ "IPrincipal.cs", "_i_principal_8cs_source.html", null ],
    [ "KerbLogonSubmitType.cs", "_kerb_logon_submit_type_8cs_source.html", null ],
    [ "NTAccount.cs", "_n_t_account_8cs_source.html", null ],
    [ "PolicyRights.cs", "_policy_rights_8cs_source.html", null ],
    [ "PrincipalPolicy.cs", "_principal_policy_8cs_source.html", null ],
    [ "SecurityIdentifier.cs", "_security_identifier_8cs_source.html", null ],
    [ "SecurityLogonType.cs", "_security_logon_type_8cs_source.html", null ],
    [ "SidNameUse.cs", "_sid_name_use_8cs_source.html", null ],
    [ "TokenAccessLevels.cs", "_token_access_levels_8cs_source.html", null ],
    [ "TokenImpersonationLevel.cs", "_token_impersonation_level_8cs_source.html", null ],
    [ "TokenInformationClass.cs", "_token_information_class_8cs_source.html", null ],
    [ "TokenType.cs", "_security_8_principal_2_token_type_8cs_source.html", null ],
    [ "WellKnownSidType.cs", "_well_known_sid_type_8cs_source.html", null ],
    [ "Win32.cs", "_system_8_security_8_principal_2_win32_8cs_source.html", null ],
    [ "WindowsAccountType.cs", "_windows_account_type_8cs_source.html", null ],
    [ "WindowsBuiltInRole.cs", "_windows_built_in_role_8cs_source.html", null ],
    [ "WindowsIdentity.cs", "_windows_identity_8cs_source.html", null ],
    [ "WindowsImpersonationContext.cs", "_windows_impersonation_context_8cs_source.html", null ],
    [ "WindowsPrincipal.cs", "_windows_principal_8cs_source.html", null ],
    [ "WinSecurityContext.cs", "_win_security_context_8cs_source.html", null ]
];