var namespace_system_1_1_runtime_1_1_serialization =
[
    [ "Formatters", "namespace_system_1_1_runtime_1_1_serialization_1_1_formatters.html", "namespace_system_1_1_runtime_1_1_serialization_1_1_formatters" ],
    [ "Formatter", "class_system_1_1_runtime_1_1_serialization_1_1_formatter.html", "class_system_1_1_runtime_1_1_serialization_1_1_formatter" ],
    [ "FormatterConverter", "class_system_1_1_runtime_1_1_serialization_1_1_formatter_converter.html", "class_system_1_1_runtime_1_1_serialization_1_1_formatter_converter" ],
    [ "FormatterServices", "class_system_1_1_runtime_1_1_serialization_1_1_formatter_services.html", "class_system_1_1_runtime_1_1_serialization_1_1_formatter_services" ],
    [ "IDeserializationCallback", "interface_system_1_1_runtime_1_1_serialization_1_1_i_deserialization_callback.html", "interface_system_1_1_runtime_1_1_serialization_1_1_i_deserialization_callback" ],
    [ "IFormatter", "interface_system_1_1_runtime_1_1_serialization_1_1_i_formatter.html", "interface_system_1_1_runtime_1_1_serialization_1_1_i_formatter" ],
    [ "IFormatterConverter", "interface_system_1_1_runtime_1_1_serialization_1_1_i_formatter_converter.html", "interface_system_1_1_runtime_1_1_serialization_1_1_i_formatter_converter" ],
    [ "IObjectReference", "interface_system_1_1_runtime_1_1_serialization_1_1_i_object_reference.html", "interface_system_1_1_runtime_1_1_serialization_1_1_i_object_reference" ],
    [ "ISafeSerializationData", "interface_system_1_1_runtime_1_1_serialization_1_1_i_safe_serialization_data.html", "interface_system_1_1_runtime_1_1_serialization_1_1_i_safe_serialization_data" ],
    [ "ISerializable", "interface_system_1_1_runtime_1_1_serialization_1_1_i_serializable.html", "interface_system_1_1_runtime_1_1_serialization_1_1_i_serializable" ],
    [ "ISerializationSurrogate", "interface_system_1_1_runtime_1_1_serialization_1_1_i_serialization_surrogate.html", "interface_system_1_1_runtime_1_1_serialization_1_1_i_serialization_surrogate" ],
    [ "ISurrogateSelector", "interface_system_1_1_runtime_1_1_serialization_1_1_i_surrogate_selector.html", "interface_system_1_1_runtime_1_1_serialization_1_1_i_surrogate_selector" ],
    [ "ObjectIDGenerator", "class_system_1_1_runtime_1_1_serialization_1_1_object_i_d_generator.html", "class_system_1_1_runtime_1_1_serialization_1_1_object_i_d_generator" ],
    [ "ObjectManager", "class_system_1_1_runtime_1_1_serialization_1_1_object_manager.html", "class_system_1_1_runtime_1_1_serialization_1_1_object_manager" ],
    [ "OnDeserializedAttribute", "class_system_1_1_runtime_1_1_serialization_1_1_on_deserialized_attribute.html", "class_system_1_1_runtime_1_1_serialization_1_1_on_deserialized_attribute" ],
    [ "OnDeserializingAttribute", "class_system_1_1_runtime_1_1_serialization_1_1_on_deserializing_attribute.html", "class_system_1_1_runtime_1_1_serialization_1_1_on_deserializing_attribute" ],
    [ "OnSerializedAttribute", "class_system_1_1_runtime_1_1_serialization_1_1_on_serialized_attribute.html", "class_system_1_1_runtime_1_1_serialization_1_1_on_serialized_attribute" ],
    [ "OnSerializingAttribute", "class_system_1_1_runtime_1_1_serialization_1_1_on_serializing_attribute.html", "class_system_1_1_runtime_1_1_serialization_1_1_on_serializing_attribute" ],
    [ "OptionalFieldAttribute", "class_system_1_1_runtime_1_1_serialization_1_1_optional_field_attribute.html", "class_system_1_1_runtime_1_1_serialization_1_1_optional_field_attribute" ],
    [ "SafeSerializationEventArgs", "class_system_1_1_runtime_1_1_serialization_1_1_safe_serialization_event_args.html", "class_system_1_1_runtime_1_1_serialization_1_1_safe_serialization_event_args" ],
    [ "SerializationBinder", "class_system_1_1_runtime_1_1_serialization_1_1_serialization_binder.html", "class_system_1_1_runtime_1_1_serialization_1_1_serialization_binder" ],
    [ "SerializationEntry", "struct_system_1_1_runtime_1_1_serialization_1_1_serialization_entry.html", "struct_system_1_1_runtime_1_1_serialization_1_1_serialization_entry" ],
    [ "SerializationException", "class_system_1_1_runtime_1_1_serialization_1_1_serialization_exception.html", "class_system_1_1_runtime_1_1_serialization_1_1_serialization_exception" ],
    [ "SerializationInfo", "class_system_1_1_runtime_1_1_serialization_1_1_serialization_info.html", "class_system_1_1_runtime_1_1_serialization_1_1_serialization_info" ],
    [ "SerializationInfoEnumerator", "class_system_1_1_runtime_1_1_serialization_1_1_serialization_info_enumerator.html", "class_system_1_1_runtime_1_1_serialization_1_1_serialization_info_enumerator" ],
    [ "SerializationObjectManager", "class_system_1_1_runtime_1_1_serialization_1_1_serialization_object_manager.html", "class_system_1_1_runtime_1_1_serialization_1_1_serialization_object_manager" ],
    [ "StreamingContext", "struct_system_1_1_runtime_1_1_serialization_1_1_streaming_context.html", "struct_system_1_1_runtime_1_1_serialization_1_1_streaming_context" ],
    [ "SurrogateSelector", "class_system_1_1_runtime_1_1_serialization_1_1_surrogate_selector.html", "class_system_1_1_runtime_1_1_serialization_1_1_surrogate_selector" ]
];