var namespace_system_1_1_collections_1_1_generic =
[
    [ "Comparer", "class_system_1_1_collections_1_1_generic_1_1_comparer.html", "class_system_1_1_collections_1_1_generic_1_1_comparer" ],
    [ "Dictionary", "class_system_1_1_collections_1_1_generic_1_1_dictionary.html", "class_system_1_1_collections_1_1_generic_1_1_dictionary" ],
    [ "EqualityComparer", "class_system_1_1_collections_1_1_generic_1_1_equality_comparer.html", "class_system_1_1_collections_1_1_generic_1_1_equality_comparer" ],
    [ "HashSet", "class_system_1_1_collections_1_1_generic_1_1_hash_set.html", "class_system_1_1_collections_1_1_generic_1_1_hash_set" ],
    [ "ICollection", "interface_system_1_1_collections_1_1_generic_1_1_i_collection.html", "interface_system_1_1_collections_1_1_generic_1_1_i_collection" ],
    [ "IComparer", "interface_system_1_1_collections_1_1_generic_1_1_i_comparer.html", "interface_system_1_1_collections_1_1_generic_1_1_i_comparer" ],
    [ "IDictionary", "interface_system_1_1_collections_1_1_generic_1_1_i_dictionary.html", "interface_system_1_1_collections_1_1_generic_1_1_i_dictionary" ],
    [ "IEnumerable", "interface_system_1_1_collections_1_1_generic_1_1_i_enumerable.html", "interface_system_1_1_collections_1_1_generic_1_1_i_enumerable" ],
    [ "IEnumerator", "interface_system_1_1_collections_1_1_generic_1_1_i_enumerator.html", "interface_system_1_1_collections_1_1_generic_1_1_i_enumerator" ],
    [ "IEqualityComparer", "interface_system_1_1_collections_1_1_generic_1_1_i_equality_comparer.html", "interface_system_1_1_collections_1_1_generic_1_1_i_equality_comparer" ],
    [ "IList", "interface_system_1_1_collections_1_1_generic_1_1_i_list.html", "interface_system_1_1_collections_1_1_generic_1_1_i_list" ],
    [ "IReadOnlyCollection", "interface_system_1_1_collections_1_1_generic_1_1_i_read_only_collection.html", "interface_system_1_1_collections_1_1_generic_1_1_i_read_only_collection" ],
    [ "IReadOnlyDictionary", "interface_system_1_1_collections_1_1_generic_1_1_i_read_only_dictionary.html", "interface_system_1_1_collections_1_1_generic_1_1_i_read_only_dictionary" ],
    [ "IReadOnlyList", "interface_system_1_1_collections_1_1_generic_1_1_i_read_only_list.html", "interface_system_1_1_collections_1_1_generic_1_1_i_read_only_list" ],
    [ "ISet", "interface_system_1_1_collections_1_1_generic_1_1_i_set.html", "interface_system_1_1_collections_1_1_generic_1_1_i_set" ],
    [ "KeyNotFoundException", "class_system_1_1_collections_1_1_generic_1_1_key_not_found_exception.html", "class_system_1_1_collections_1_1_generic_1_1_key_not_found_exception" ],
    [ "KeyValuePair", "struct_system_1_1_collections_1_1_generic_1_1_key_value_pair.html", "struct_system_1_1_collections_1_1_generic_1_1_key_value_pair" ],
    [ "LinkedList", "class_system_1_1_collections_1_1_generic_1_1_linked_list.html", "class_system_1_1_collections_1_1_generic_1_1_linked_list" ],
    [ "LinkedListNode", "class_system_1_1_collections_1_1_generic_1_1_linked_list_node.html", "class_system_1_1_collections_1_1_generic_1_1_linked_list_node" ],
    [ "List", "class_system_1_1_collections_1_1_generic_1_1_list.html", "class_system_1_1_collections_1_1_generic_1_1_list" ],
    [ "Queue", "class_system_1_1_collections_1_1_generic_1_1_queue.html", "class_system_1_1_collections_1_1_generic_1_1_queue" ],
    [ "SortedDictionary", "class_system_1_1_collections_1_1_generic_1_1_sorted_dictionary.html", "class_system_1_1_collections_1_1_generic_1_1_sorted_dictionary" ],
    [ "SortedList", "class_system_1_1_collections_1_1_generic_1_1_sorted_list.html", "class_system_1_1_collections_1_1_generic_1_1_sorted_list" ],
    [ "SortedSet", "class_system_1_1_collections_1_1_generic_1_1_sorted_set.html", "class_system_1_1_collections_1_1_generic_1_1_sorted_set" ],
    [ "Stack", "class_system_1_1_collections_1_1_generic_1_1_stack.html", "class_system_1_1_collections_1_1_generic_1_1_stack" ]
];