var namespace_system_1_1_text =
[
    [ "RegularExpressions", "namespace_system_1_1_text_1_1_regular_expressions.html", "namespace_system_1_1_text_1_1_regular_expressions" ],
    [ "ASCIIEncoding", "class_system_1_1_text_1_1_a_s_c_i_i_encoding.html", "class_system_1_1_text_1_1_a_s_c_i_i_encoding" ],
    [ "Decoder", "class_system_1_1_text_1_1_decoder.html", "class_system_1_1_text_1_1_decoder" ],
    [ "DecoderExceptionFallback", "class_system_1_1_text_1_1_decoder_exception_fallback.html", "class_system_1_1_text_1_1_decoder_exception_fallback" ],
    [ "DecoderExceptionFallbackBuffer", "class_system_1_1_text_1_1_decoder_exception_fallback_buffer.html", "class_system_1_1_text_1_1_decoder_exception_fallback_buffer" ],
    [ "DecoderFallback", "class_system_1_1_text_1_1_decoder_fallback.html", "class_system_1_1_text_1_1_decoder_fallback" ],
    [ "DecoderFallbackBuffer", "class_system_1_1_text_1_1_decoder_fallback_buffer.html", "class_system_1_1_text_1_1_decoder_fallback_buffer" ],
    [ "DecoderFallbackException", "class_system_1_1_text_1_1_decoder_fallback_exception.html", "class_system_1_1_text_1_1_decoder_fallback_exception" ],
    [ "DecoderReplacementFallback", "class_system_1_1_text_1_1_decoder_replacement_fallback.html", "class_system_1_1_text_1_1_decoder_replacement_fallback" ],
    [ "DecoderReplacementFallbackBuffer", "class_system_1_1_text_1_1_decoder_replacement_fallback_buffer.html", "class_system_1_1_text_1_1_decoder_replacement_fallback_buffer" ],
    [ "Encoder", "class_system_1_1_text_1_1_encoder.html", "class_system_1_1_text_1_1_encoder" ],
    [ "EncoderExceptionFallback", "class_system_1_1_text_1_1_encoder_exception_fallback.html", "class_system_1_1_text_1_1_encoder_exception_fallback" ],
    [ "EncoderExceptionFallbackBuffer", "class_system_1_1_text_1_1_encoder_exception_fallback_buffer.html", "class_system_1_1_text_1_1_encoder_exception_fallback_buffer" ],
    [ "EncoderFallback", "class_system_1_1_text_1_1_encoder_fallback.html", "class_system_1_1_text_1_1_encoder_fallback" ],
    [ "EncoderFallbackBuffer", "class_system_1_1_text_1_1_encoder_fallback_buffer.html", "class_system_1_1_text_1_1_encoder_fallback_buffer" ],
    [ "EncoderFallbackException", "class_system_1_1_text_1_1_encoder_fallback_exception.html", "class_system_1_1_text_1_1_encoder_fallback_exception" ],
    [ "EncoderReplacementFallback", "class_system_1_1_text_1_1_encoder_replacement_fallback.html", "class_system_1_1_text_1_1_encoder_replacement_fallback" ],
    [ "EncoderReplacementFallbackBuffer", "class_system_1_1_text_1_1_encoder_replacement_fallback_buffer.html", "class_system_1_1_text_1_1_encoder_replacement_fallback_buffer" ],
    [ "Encoding", "class_system_1_1_text_1_1_encoding.html", "class_system_1_1_text_1_1_encoding" ],
    [ "EncodingInfo", "class_system_1_1_text_1_1_encoding_info.html", "class_system_1_1_text_1_1_encoding_info" ],
    [ "EncodingProvider", "class_system_1_1_text_1_1_encoding_provider.html", "class_system_1_1_text_1_1_encoding_provider" ],
    [ "StringBuilder", "class_system_1_1_text_1_1_string_builder.html", "class_system_1_1_text_1_1_string_builder" ],
    [ "UnicodeEncoding", "class_system_1_1_text_1_1_unicode_encoding.html", "class_system_1_1_text_1_1_unicode_encoding" ],
    [ "UTF32Encoding", "class_system_1_1_text_1_1_u_t_f32_encoding.html", "class_system_1_1_text_1_1_u_t_f32_encoding" ],
    [ "UTF7Encoding", "class_system_1_1_text_1_1_u_t_f7_encoding.html", "class_system_1_1_text_1_1_u_t_f7_encoding" ],
    [ "UTF8Encoding", "class_system_1_1_text_1_1_u_t_f8_encoding.html", "class_system_1_1_text_1_1_u_t_f8_encoding" ]
];