var namespace_system_1_1_collections =
[
    [ "Concurrent", "namespace_system_1_1_collections_1_1_concurrent.html", "namespace_system_1_1_collections_1_1_concurrent" ],
    [ "Generic", "namespace_system_1_1_collections_1_1_generic.html", "namespace_system_1_1_collections_1_1_generic" ],
    [ "ObjectModel", "namespace_system_1_1_collections_1_1_object_model.html", "namespace_system_1_1_collections_1_1_object_model" ],
    [ "Specialized", "namespace_system_1_1_collections_1_1_specialized.html", "namespace_system_1_1_collections_1_1_specialized" ],
    [ "ArrayList", "class_system_1_1_collections_1_1_array_list.html", "class_system_1_1_collections_1_1_array_list" ],
    [ "BitArray", "class_system_1_1_collections_1_1_bit_array.html", "class_system_1_1_collections_1_1_bit_array" ],
    [ "CaseInsensitiveComparer", "class_system_1_1_collections_1_1_case_insensitive_comparer.html", "class_system_1_1_collections_1_1_case_insensitive_comparer" ],
    [ "CaseInsensitiveHashCodeProvider", "class_system_1_1_collections_1_1_case_insensitive_hash_code_provider.html", "class_system_1_1_collections_1_1_case_insensitive_hash_code_provider" ],
    [ "CollectionBase", "class_system_1_1_collections_1_1_collection_base.html", "class_system_1_1_collections_1_1_collection_base" ],
    [ "Comparer", "class_system_1_1_collections_1_1_comparer.html", "class_system_1_1_collections_1_1_comparer" ],
    [ "DictionaryBase", "class_system_1_1_collections_1_1_dictionary_base.html", "class_system_1_1_collections_1_1_dictionary_base" ],
    [ "DictionaryEntry", "struct_system_1_1_collections_1_1_dictionary_entry.html", "struct_system_1_1_collections_1_1_dictionary_entry" ],
    [ "Hashtable", "class_system_1_1_collections_1_1_hashtable.html", "class_system_1_1_collections_1_1_hashtable" ],
    [ "ICollection", "interface_system_1_1_collections_1_1_i_collection.html", "interface_system_1_1_collections_1_1_i_collection" ],
    [ "IComparer", "interface_system_1_1_collections_1_1_i_comparer.html", "interface_system_1_1_collections_1_1_i_comparer" ],
    [ "IDictionary", "interface_system_1_1_collections_1_1_i_dictionary.html", "interface_system_1_1_collections_1_1_i_dictionary" ],
    [ "IDictionaryEnumerator", "interface_system_1_1_collections_1_1_i_dictionary_enumerator.html", "interface_system_1_1_collections_1_1_i_dictionary_enumerator" ],
    [ "IEnumerable", "interface_system_1_1_collections_1_1_i_enumerable.html", "interface_system_1_1_collections_1_1_i_enumerable" ],
    [ "IEnumerator", "interface_system_1_1_collections_1_1_i_enumerator.html", "interface_system_1_1_collections_1_1_i_enumerator" ],
    [ "IEqualityComparer", "interface_system_1_1_collections_1_1_i_equality_comparer.html", "interface_system_1_1_collections_1_1_i_equality_comparer" ],
    [ "IHashCodeProvider", "interface_system_1_1_collections_1_1_i_hash_code_provider.html", "interface_system_1_1_collections_1_1_i_hash_code_provider" ],
    [ "IList", "interface_system_1_1_collections_1_1_i_list.html", "interface_system_1_1_collections_1_1_i_list" ],
    [ "IStructuralComparable", "interface_system_1_1_collections_1_1_i_structural_comparable.html", "interface_system_1_1_collections_1_1_i_structural_comparable" ],
    [ "IStructuralEquatable", "interface_system_1_1_collections_1_1_i_structural_equatable.html", "interface_system_1_1_collections_1_1_i_structural_equatable" ],
    [ "Queue", "class_system_1_1_collections_1_1_queue.html", "class_system_1_1_collections_1_1_queue" ],
    [ "ReadOnlyCollectionBase", "class_system_1_1_collections_1_1_read_only_collection_base.html", "class_system_1_1_collections_1_1_read_only_collection_base" ],
    [ "SortedList", "class_system_1_1_collections_1_1_sorted_list.html", "class_system_1_1_collections_1_1_sorted_list" ],
    [ "Stack", "class_system_1_1_collections_1_1_stack.html", "class_system_1_1_collections_1_1_stack" ],
    [ "StructuralComparisons", "class_system_1_1_collections_1_1_structural_comparisons.html", "class_system_1_1_collections_1_1_structural_comparisons" ]
];