var namespace_system_1_1_runtime_1_1_serialization_1_1_formatters_1_1_binary =
[
    [ "BinaryFormatter", "class_system_1_1_runtime_1_1_serialization_1_1_formatters_1_1_binary_1_1_binary_formatter.html", "class_system_1_1_runtime_1_1_serialization_1_1_formatters_1_1_binary_1_1_binary_formatter" ]
];