var namespace_system_1_1_stub_helpers =
[
    [ "AnsiBSTRMarshaler", "class_system_1_1_stub_helpers_1_1_ansi_b_s_t_r_marshaler.html", null ],
    [ "AnsiCharMarshaler", "class_system_1_1_stub_helpers_1_1_ansi_char_marshaler.html", null ],
    [ "AsAnyMarshaler", "struct_system_1_1_stub_helpers_1_1_as_any_marshaler.html", "struct_system_1_1_stub_helpers_1_1_as_any_marshaler" ],
    [ "BSTRMarshaler", "class_system_1_1_stub_helpers_1_1_b_s_t_r_marshaler.html", null ],
    [ "CleanupWorkList", "class_system_1_1_stub_helpers_1_1_cleanup_work_list.html", "class_system_1_1_stub_helpers_1_1_cleanup_work_list" ],
    [ "CleanupWorkListElement", "class_system_1_1_stub_helpers_1_1_cleanup_work_list_element.html", "class_system_1_1_stub_helpers_1_1_cleanup_work_list_element" ],
    [ "CSTRMarshaler", "class_system_1_1_stub_helpers_1_1_c_s_t_r_marshaler.html", null ],
    [ "DateMarshaler", "class_system_1_1_stub_helpers_1_1_date_marshaler.html", null ],
    [ "DateTimeNative", "struct_system_1_1_stub_helpers_1_1_date_time_native.html", "struct_system_1_1_stub_helpers_1_1_date_time_native" ],
    [ "DateTimeOffsetMarshaler", "class_system_1_1_stub_helpers_1_1_date_time_offset_marshaler.html", null ],
    [ "EventArgsMarshaler", "class_system_1_1_stub_helpers_1_1_event_args_marshaler.html", null ],
    [ "HResultExceptionMarshaler", "class_system_1_1_stub_helpers_1_1_h_result_exception_marshaler.html", null ],
    [ "HStringMarshaler", "class_system_1_1_stub_helpers_1_1_h_string_marshaler.html", null ],
    [ "InterfaceMarshaler", "class_system_1_1_stub_helpers_1_1_interface_marshaler.html", null ],
    [ "KeyValuePairMarshaler", "class_system_1_1_stub_helpers_1_1_key_value_pair_marshaler.html", null ],
    [ "MngdHiddenLengthArrayMarshaler", "class_system_1_1_stub_helpers_1_1_mngd_hidden_length_array_marshaler.html", null ],
    [ "MngdNativeArrayMarshaler", "class_system_1_1_stub_helpers_1_1_mngd_native_array_marshaler.html", null ],
    [ "MngdRefCustomMarshaler", "class_system_1_1_stub_helpers_1_1_mngd_ref_custom_marshaler.html", null ],
    [ "MngdSafeArrayMarshaler", "class_system_1_1_stub_helpers_1_1_mngd_safe_array_marshaler.html", null ],
    [ "NativeVariant", "struct_system_1_1_stub_helpers_1_1_native_variant.html", null ],
    [ "NullableMarshaler", "class_system_1_1_stub_helpers_1_1_nullable_marshaler.html", null ],
    [ "ObjectMarshaler", "class_system_1_1_stub_helpers_1_1_object_marshaler.html", null ],
    [ "StubHelpers", "class_system_1_1_stub_helpers_1_1_stub_helpers.html", null ],
    [ "SystemTypeMarshaler", "class_system_1_1_stub_helpers_1_1_system_type_marshaler.html", null ],
    [ "TypeNameNative", "struct_system_1_1_stub_helpers_1_1_type_name_native.html", "struct_system_1_1_stub_helpers_1_1_type_name_native" ],
    [ "UriMarshaler", "class_system_1_1_stub_helpers_1_1_uri_marshaler.html", null ],
    [ "UTF8BufferMarshaler", "class_system_1_1_stub_helpers_1_1_u_t_f8_buffer_marshaler.html", null ],
    [ "UTF8Marshaler", "class_system_1_1_stub_helpers_1_1_u_t_f8_marshaler.html", null ],
    [ "ValueClassMarshaler", "class_system_1_1_stub_helpers_1_1_value_class_marshaler.html", null ],
    [ "VBByValStrMarshaler", "class_system_1_1_stub_helpers_1_1_v_b_by_val_str_marshaler.html", null ],
    [ "WinRTTypeNameConverter", "class_system_1_1_stub_helpers_1_1_win_r_t_type_name_converter.html", null ],
    [ "WSTRBufferMarshaler", "class_system_1_1_stub_helpers_1_1_w_s_t_r_buffer_marshaler.html", null ]
];