var namespace_system_1_1_runtime_1_1_remoting_1_1_channels =
[
    [ "BaseChannelObjectWithProperties", "class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_base_channel_object_with_properties.html", "class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_base_channel_object_with_properties" ],
    [ "BaseChannelSinkWithProperties", "class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_base_channel_sink_with_properties.html", null ],
    [ "BaseChannelWithProperties", "class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_base_channel_with_properties.html", "class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_base_channel_with_properties" ],
    [ "ChannelDataStore", "class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_channel_data_store.html", "class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_channel_data_store" ],
    [ "ChannelServices", "class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_channel_services.html", "class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_channel_services" ],
    [ "ClientChannelSinkStack", "class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_client_channel_sink_stack.html", "class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_client_channel_sink_stack" ],
    [ "IChannel", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel.html", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel" ],
    [ "IChannelDataStore", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_data_store.html", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_data_store" ],
    [ "IChannelReceiver", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_receiver.html", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_receiver" ],
    [ "IChannelReceiverHook", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_receiver_hook.html", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_receiver_hook" ],
    [ "IChannelSender", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_sender.html", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_sender" ],
    [ "IChannelSinkBase", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_sink_base.html", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_channel_sink_base" ],
    [ "IClientChannelSink", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_channel_sink.html", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_channel_sink" ],
    [ "IClientChannelSinkProvider", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_channel_sink_provider.html", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_channel_sink_provider" ],
    [ "IClientChannelSinkStack", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_channel_sink_stack.html", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_channel_sink_stack" ],
    [ "IClientFormatterSink", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_formatter_sink.html", null ],
    [ "IClientFormatterSinkProvider", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_formatter_sink_provider.html", null ],
    [ "IClientResponseChannelSinkStack", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_response_channel_sink_stack.html", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_client_response_channel_sink_stack" ],
    [ "ISecurableChannel", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_securable_channel.html", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_securable_channel" ],
    [ "IServerChannelSink", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_server_channel_sink.html", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_server_channel_sink" ],
    [ "IServerChannelSinkProvider", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_server_channel_sink_provider.html", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_server_channel_sink_provider" ],
    [ "IServerChannelSinkStack", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_server_channel_sink_stack.html", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_server_channel_sink_stack" ],
    [ "IServerFormatterSinkProvider", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_server_formatter_sink_provider.html", null ],
    [ "IServerResponseChannelSinkStack", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_server_response_channel_sink_stack.html", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_server_response_channel_sink_stack" ],
    [ "ITransportHeaders", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_transport_headers.html", "interface_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_i_transport_headers" ],
    [ "ServerChannelSinkStack", "class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_server_channel_sink_stack.html", "class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_server_channel_sink_stack" ],
    [ "SinkProviderData", "class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_sink_provider_data.html", "class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_sink_provider_data" ],
    [ "TransportHeaders", "class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_transport_headers.html", "class_system_1_1_runtime_1_1_remoting_1_1_channels_1_1_transport_headers" ]
];