var namespace_system_1_1_runtime_1_1_remoting_1_1_messaging =
[
    [ "AsyncResult", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_async_result.html", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_async_result" ],
    [ "CallContext", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_call_context.html", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_call_context" ],
    [ "ConstructionCall", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_construction_call.html", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_construction_call" ],
    [ "ConstructionResponse", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_construction_response.html", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_construction_response" ],
    [ "Header", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_header.html", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_header" ],
    [ "ILogicalThreadAffinative", "interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_logical_thread_affinative.html", null ],
    [ "IMessage", "interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_message.html", "interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_message" ],
    [ "IMessageCtrl", "interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_message_ctrl.html", "interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_message_ctrl" ],
    [ "IMessageSink", "interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_message_sink.html", "interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_message_sink" ],
    [ "IMethodCallMessage", "interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_method_call_message.html", "interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_method_call_message" ],
    [ "IMethodMessage", "interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_method_message.html", "interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_method_message" ],
    [ "IMethodReturnMessage", "interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_method_return_message.html", "interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_method_return_message" ],
    [ "InternalMessageWrapper", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_internal_message_wrapper.html", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_internal_message_wrapper" ],
    [ "IRemotingFormatter", "interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_remoting_formatter.html", "interface_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_i_remoting_formatter" ],
    [ "LogicalCallContext", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_logical_call_context.html", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_logical_call_context" ],
    [ "MethodCall", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_method_call.html", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_method_call" ],
    [ "MethodCallMessageWrapper", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_method_call_message_wrapper.html", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_method_call_message_wrapper" ],
    [ "MethodResponse", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_method_response.html", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_method_response" ],
    [ "MethodReturnMessageWrapper", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_method_return_message_wrapper.html", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_method_return_message_wrapper" ],
    [ "OneWayAttribute", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_one_way_attribute.html", null ],
    [ "RemotingSurrogateSelector", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_remoting_surrogate_selector.html", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_remoting_surrogate_selector" ],
    [ "ReturnMessage", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_return_message.html", "class_system_1_1_runtime_1_1_remoting_1_1_messaging_1_1_return_message" ]
];