var namespace_system_1_1_security =
[
    [ "AccessControl", "namespace_system_1_1_security_1_1_access_control.html", "namespace_system_1_1_security_1_1_access_control" ],
    [ "Authentication", "namespace_system_1_1_security_1_1_authentication.html", "namespace_system_1_1_security_1_1_authentication" ],
    [ "Claims", "namespace_system_1_1_security_1_1_claims.html", "namespace_system_1_1_security_1_1_claims" ],
    [ "Cryptography", "namespace_system_1_1_security_1_1_cryptography.html", "namespace_system_1_1_security_1_1_cryptography" ],
    [ "Permissions", "namespace_system_1_1_security_1_1_permissions.html", "namespace_system_1_1_security_1_1_permissions" ],
    [ "Policy", "namespace_system_1_1_security_1_1_policy.html", "namespace_system_1_1_security_1_1_policy" ],
    [ "Principal", "namespace_system_1_1_security_1_1_principal.html", "namespace_system_1_1_security_1_1_principal" ],
    [ "AllowPartiallyTrustedCallersAttribute", "class_system_1_1_security_1_1_allow_partially_trusted_callers_attribute.html", "class_system_1_1_security_1_1_allow_partially_trusted_callers_attribute" ],
    [ "CodeAccessPermission", "class_system_1_1_security_1_1_code_access_permission.html", "class_system_1_1_security_1_1_code_access_permission" ],
    [ "HostProtectionException", "class_system_1_1_security_1_1_host_protection_exception.html", "class_system_1_1_security_1_1_host_protection_exception" ],
    [ "HostSecurityManager", "class_system_1_1_security_1_1_host_security_manager.html", "class_system_1_1_security_1_1_host_security_manager" ],
    [ "IEvidenceFactory", "interface_system_1_1_security_1_1_i_evidence_factory.html", "interface_system_1_1_security_1_1_i_evidence_factory" ],
    [ "IPermission", "interface_system_1_1_security_1_1_i_permission.html", "interface_system_1_1_security_1_1_i_permission" ],
    [ "ISecurityEncodable", "interface_system_1_1_security_1_1_i_security_encodable.html", "interface_system_1_1_security_1_1_i_security_encodable" ],
    [ "ISecurityPolicyEncodable", "interface_system_1_1_security_1_1_i_security_policy_encodable.html", "interface_system_1_1_security_1_1_i_security_policy_encodable" ],
    [ "IStackWalk", "interface_system_1_1_security_1_1_i_stack_walk.html", "interface_system_1_1_security_1_1_i_stack_walk" ],
    [ "NamedPermissionSet", "class_system_1_1_security_1_1_named_permission_set.html", "class_system_1_1_security_1_1_named_permission_set" ],
    [ "PermissionSet", "class_system_1_1_security_1_1_permission_set.html", "class_system_1_1_security_1_1_permission_set" ],
    [ "ReadOnlyPermissionSet", "class_system_1_1_security_1_1_read_only_permission_set.html", "class_system_1_1_security_1_1_read_only_permission_set" ],
    [ "SecureString", "class_system_1_1_security_1_1_secure_string.html", "class_system_1_1_security_1_1_secure_string" ],
    [ "SecureStringMarshal", "class_system_1_1_security_1_1_secure_string_marshal.html", "class_system_1_1_security_1_1_secure_string_marshal" ],
    [ "SecurityContext", "class_system_1_1_security_1_1_security_context.html", "class_system_1_1_security_1_1_security_context" ],
    [ "SecurityCriticalAttribute", "class_system_1_1_security_1_1_security_critical_attribute.html", "class_system_1_1_security_1_1_security_critical_attribute" ],
    [ "SecurityElement", "class_system_1_1_security_1_1_security_element.html", "class_system_1_1_security_1_1_security_element" ],
    [ "SecurityException", "class_system_1_1_security_1_1_security_exception.html", "class_system_1_1_security_1_1_security_exception" ],
    [ "SecurityManager", "class_system_1_1_security_1_1_security_manager.html", "class_system_1_1_security_1_1_security_manager" ],
    [ "SecurityRulesAttribute", "class_system_1_1_security_1_1_security_rules_attribute.html", "class_system_1_1_security_1_1_security_rules_attribute" ],
    [ "SecuritySafeCriticalAttribute", "class_system_1_1_security_1_1_security_safe_critical_attribute.html", "class_system_1_1_security_1_1_security_safe_critical_attribute" ],
    [ "SecurityState", "class_system_1_1_security_1_1_security_state.html", "class_system_1_1_security_1_1_security_state" ],
    [ "SecurityTransparentAttribute", "class_system_1_1_security_1_1_security_transparent_attribute.html", "class_system_1_1_security_1_1_security_transparent_attribute" ],
    [ "SecurityTreatAsSafeAttribute", "class_system_1_1_security_1_1_security_treat_as_safe_attribute.html", null ],
    [ "SuppressUnmanagedCodeSecurityAttribute", "class_system_1_1_security_1_1_suppress_unmanaged_code_security_attribute.html", null ],
    [ "UnverifiableCodeAttribute", "class_system_1_1_security_1_1_unverifiable_code_attribute.html", null ],
    [ "VerificationException", "class_system_1_1_security_1_1_verification_exception.html", "class_system_1_1_security_1_1_verification_exception" ],
    [ "XmlSyntaxException", "class_system_1_1_security_1_1_xml_syntax_exception.html", "class_system_1_1_security_1_1_xml_syntax_exception" ]
];